
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CharacterResources` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model CharacterResources
 * 
 */
export type CharacterResourcesModel = runtime.Types.Result.DefaultSelection<Prisma.$CharacterResourcesPayload>

export type AggregateCharacterResources = {
  _count: CharacterResourcesCountAggregateOutputType | null
  _avg: CharacterResourcesAvgAggregateOutputType | null
  _sum: CharacterResourcesSumAggregateOutputType | null
  _min: CharacterResourcesMinAggregateOutputType | null
  _max: CharacterResourcesMaxAggregateOutputType | null
}

export type CharacterResourcesAvgAggregateOutputType = {
  healthCurrent: number | null
  healthMax: number | null
  focusCurrent: number | null
  focusMax: number | null
  investitureCurrent: number | null
  investitureMax: number | null
}

export type CharacterResourcesSumAggregateOutputType = {
  healthCurrent: number | null
  healthMax: number | null
  focusCurrent: number | null
  focusMax: number | null
  investitureCurrent: number | null
  investitureMax: number | null
}

export type CharacterResourcesMinAggregateOutputType = {
  id: string | null
  characterId: string | null
  healthCurrent: number | null
  healthMax: number | null
  focusCurrent: number | null
  focusMax: number | null
  investitureCurrent: number | null
  investitureMax: number | null
  investitureActive: boolean | null
}

export type CharacterResourcesMaxAggregateOutputType = {
  id: string | null
  characterId: string | null
  healthCurrent: number | null
  healthMax: number | null
  focusCurrent: number | null
  focusMax: number | null
  investitureCurrent: number | null
  investitureMax: number | null
  investitureActive: boolean | null
}

export type CharacterResourcesCountAggregateOutputType = {
  id: number
  characterId: number
  healthCurrent: number
  healthMax: number
  focusCurrent: number
  focusMax: number
  investitureCurrent: number
  investitureMax: number
  investitureActive: number
  _all: number
}


export type CharacterResourcesAvgAggregateInputType = {
  healthCurrent?: true
  healthMax?: true
  focusCurrent?: true
  focusMax?: true
  investitureCurrent?: true
  investitureMax?: true
}

export type CharacterResourcesSumAggregateInputType = {
  healthCurrent?: true
  healthMax?: true
  focusCurrent?: true
  focusMax?: true
  investitureCurrent?: true
  investitureMax?: true
}

export type CharacterResourcesMinAggregateInputType = {
  id?: true
  characterId?: true
  healthCurrent?: true
  healthMax?: true
  focusCurrent?: true
  focusMax?: true
  investitureCurrent?: true
  investitureMax?: true
  investitureActive?: true
}

export type CharacterResourcesMaxAggregateInputType = {
  id?: true
  characterId?: true
  healthCurrent?: true
  healthMax?: true
  focusCurrent?: true
  focusMax?: true
  investitureCurrent?: true
  investitureMax?: true
  investitureActive?: true
}

export type CharacterResourcesCountAggregateInputType = {
  id?: true
  characterId?: true
  healthCurrent?: true
  healthMax?: true
  focusCurrent?: true
  focusMax?: true
  investitureCurrent?: true
  investitureMax?: true
  investitureActive?: true
  _all?: true
}

export type CharacterResourcesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CharacterResources to aggregate.
   */
  where?: Prisma.CharacterResourcesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CharacterResources to fetch.
   */
  orderBy?: Prisma.CharacterResourcesOrderByWithRelationInput | Prisma.CharacterResourcesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CharacterResourcesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CharacterResources from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CharacterResources.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CharacterResources
  **/
  _count?: true | CharacterResourcesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CharacterResourcesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CharacterResourcesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CharacterResourcesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CharacterResourcesMaxAggregateInputType
}

export type GetCharacterResourcesAggregateType<T extends CharacterResourcesAggregateArgs> = {
      [P in keyof T & keyof AggregateCharacterResources]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCharacterResources[P]>
    : Prisma.GetScalarType<T[P], AggregateCharacterResources[P]>
}




export type CharacterResourcesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CharacterResourcesWhereInput
  orderBy?: Prisma.CharacterResourcesOrderByWithAggregationInput | Prisma.CharacterResourcesOrderByWithAggregationInput[]
  by: Prisma.CharacterResourcesScalarFieldEnum[] | Prisma.CharacterResourcesScalarFieldEnum
  having?: Prisma.CharacterResourcesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CharacterResourcesCountAggregateInputType | true
  _avg?: CharacterResourcesAvgAggregateInputType
  _sum?: CharacterResourcesSumAggregateInputType
  _min?: CharacterResourcesMinAggregateInputType
  _max?: CharacterResourcesMaxAggregateInputType
}

export type CharacterResourcesGroupByOutputType = {
  id: string
  characterId: string
  healthCurrent: number
  healthMax: number
  focusCurrent: number
  focusMax: number
  investitureCurrent: number
  investitureMax: number
  investitureActive: boolean
  _count: CharacterResourcesCountAggregateOutputType | null
  _avg: CharacterResourcesAvgAggregateOutputType | null
  _sum: CharacterResourcesSumAggregateOutputType | null
  _min: CharacterResourcesMinAggregateOutputType | null
  _max: CharacterResourcesMaxAggregateOutputType | null
}

type GetCharacterResourcesGroupByPayload<T extends CharacterResourcesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CharacterResourcesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CharacterResourcesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CharacterResourcesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CharacterResourcesGroupByOutputType[P]>
      }
    >
  >



export type CharacterResourcesWhereInput = {
  AND?: Prisma.CharacterResourcesWhereInput | Prisma.CharacterResourcesWhereInput[]
  OR?: Prisma.CharacterResourcesWhereInput[]
  NOT?: Prisma.CharacterResourcesWhereInput | Prisma.CharacterResourcesWhereInput[]
  id?: Prisma.StringFilter<"CharacterResources"> | string
  characterId?: Prisma.StringFilter<"CharacterResources"> | string
  healthCurrent?: Prisma.IntFilter<"CharacterResources"> | number
  healthMax?: Prisma.IntFilter<"CharacterResources"> | number
  focusCurrent?: Prisma.IntFilter<"CharacterResources"> | number
  focusMax?: Prisma.IntFilter<"CharacterResources"> | number
  investitureCurrent?: Prisma.IntFilter<"CharacterResources"> | number
  investitureMax?: Prisma.IntFilter<"CharacterResources"> | number
  investitureActive?: Prisma.BoolFilter<"CharacterResources"> | boolean
  character?: Prisma.XOR<Prisma.CharacterScalarRelationFilter, Prisma.CharacterWhereInput>
}

export type CharacterResourcesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  healthCurrent?: Prisma.SortOrder
  healthMax?: Prisma.SortOrder
  focusCurrent?: Prisma.SortOrder
  focusMax?: Prisma.SortOrder
  investitureCurrent?: Prisma.SortOrder
  investitureMax?: Prisma.SortOrder
  investitureActive?: Prisma.SortOrder
  character?: Prisma.CharacterOrderByWithRelationInput
}

export type CharacterResourcesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  characterId?: string
  AND?: Prisma.CharacterResourcesWhereInput | Prisma.CharacterResourcesWhereInput[]
  OR?: Prisma.CharacterResourcesWhereInput[]
  NOT?: Prisma.CharacterResourcesWhereInput | Prisma.CharacterResourcesWhereInput[]
  healthCurrent?: Prisma.IntFilter<"CharacterResources"> | number
  healthMax?: Prisma.IntFilter<"CharacterResources"> | number
  focusCurrent?: Prisma.IntFilter<"CharacterResources"> | number
  focusMax?: Prisma.IntFilter<"CharacterResources"> | number
  investitureCurrent?: Prisma.IntFilter<"CharacterResources"> | number
  investitureMax?: Prisma.IntFilter<"CharacterResources"> | number
  investitureActive?: Prisma.BoolFilter<"CharacterResources"> | boolean
  character?: Prisma.XOR<Prisma.CharacterScalarRelationFilter, Prisma.CharacterWhereInput>
}, "id" | "characterId">

export type CharacterResourcesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  healthCurrent?: Prisma.SortOrder
  healthMax?: Prisma.SortOrder
  focusCurrent?: Prisma.SortOrder
  focusMax?: Prisma.SortOrder
  investitureCurrent?: Prisma.SortOrder
  investitureMax?: Prisma.SortOrder
  investitureActive?: Prisma.SortOrder
  _count?: Prisma.CharacterResourcesCountOrderByAggregateInput
  _avg?: Prisma.CharacterResourcesAvgOrderByAggregateInput
  _max?: Prisma.CharacterResourcesMaxOrderByAggregateInput
  _min?: Prisma.CharacterResourcesMinOrderByAggregateInput
  _sum?: Prisma.CharacterResourcesSumOrderByAggregateInput
}

export type CharacterResourcesScalarWhereWithAggregatesInput = {
  AND?: Prisma.CharacterResourcesScalarWhereWithAggregatesInput | Prisma.CharacterResourcesScalarWhereWithAggregatesInput[]
  OR?: Prisma.CharacterResourcesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CharacterResourcesScalarWhereWithAggregatesInput | Prisma.CharacterResourcesScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CharacterResources"> | string
  characterId?: Prisma.StringWithAggregatesFilter<"CharacterResources"> | string
  healthCurrent?: Prisma.IntWithAggregatesFilter<"CharacterResources"> | number
  healthMax?: Prisma.IntWithAggregatesFilter<"CharacterResources"> | number
  focusCurrent?: Prisma.IntWithAggregatesFilter<"CharacterResources"> | number
  focusMax?: Prisma.IntWithAggregatesFilter<"CharacterResources"> | number
  investitureCurrent?: Prisma.IntWithAggregatesFilter<"CharacterResources"> | number
  investitureMax?: Prisma.IntWithAggregatesFilter<"CharacterResources"> | number
  investitureActive?: Prisma.BoolWithAggregatesFilter<"CharacterResources"> | boolean
}

export type CharacterResourcesCreateInput = {
  id?: string
  healthCurrent?: number
  healthMax?: number
  focusCurrent?: number
  focusMax?: number
  investitureCurrent?: number
  investitureMax?: number
  investitureActive?: boolean
  character: Prisma.CharacterCreateNestedOneWithoutResourcesInput
}

export type CharacterResourcesUncheckedCreateInput = {
  id?: string
  characterId: string
  healthCurrent?: number
  healthMax?: number
  focusCurrent?: number
  focusMax?: number
  investitureCurrent?: number
  investitureMax?: number
  investitureActive?: boolean
}

export type CharacterResourcesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  healthCurrent?: Prisma.IntFieldUpdateOperationsInput | number
  healthMax?: Prisma.IntFieldUpdateOperationsInput | number
  focusCurrent?: Prisma.IntFieldUpdateOperationsInput | number
  focusMax?: Prisma.IntFieldUpdateOperationsInput | number
  investitureCurrent?: Prisma.IntFieldUpdateOperationsInput | number
  investitureMax?: Prisma.IntFieldUpdateOperationsInput | number
  investitureActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  character?: Prisma.CharacterUpdateOneRequiredWithoutResourcesNestedInput
}

export type CharacterResourcesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  characterId?: Prisma.StringFieldUpdateOperationsInput | string
  healthCurrent?: Prisma.IntFieldUpdateOperationsInput | number
  healthMax?: Prisma.IntFieldUpdateOperationsInput | number
  focusCurrent?: Prisma.IntFieldUpdateOperationsInput | number
  focusMax?: Prisma.IntFieldUpdateOperationsInput | number
  investitureCurrent?: Prisma.IntFieldUpdateOperationsInput | number
  investitureMax?: Prisma.IntFieldUpdateOperationsInput | number
  investitureActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type CharacterResourcesCreateManyInput = {
  id?: string
  characterId: string
  healthCurrent?: number
  healthMax?: number
  focusCurrent?: number
  focusMax?: number
  investitureCurrent?: number
  investitureMax?: number
  investitureActive?: boolean
}

export type CharacterResourcesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  healthCurrent?: Prisma.IntFieldUpdateOperationsInput | number
  healthMax?: Prisma.IntFieldUpdateOperationsInput | number
  focusCurrent?: Prisma.IntFieldUpdateOperationsInput | number
  focusMax?: Prisma.IntFieldUpdateOperationsInput | number
  investitureCurrent?: Prisma.IntFieldUpdateOperationsInput | number
  investitureMax?: Prisma.IntFieldUpdateOperationsInput | number
  investitureActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type CharacterResourcesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  characterId?: Prisma.StringFieldUpdateOperationsInput | string
  healthCurrent?: Prisma.IntFieldUpdateOperationsInput | number
  healthMax?: Prisma.IntFieldUpdateOperationsInput | number
  focusCurrent?: Prisma.IntFieldUpdateOperationsInput | number
  focusMax?: Prisma.IntFieldUpdateOperationsInput | number
  investitureCurrent?: Prisma.IntFieldUpdateOperationsInput | number
  investitureMax?: Prisma.IntFieldUpdateOperationsInput | number
  investitureActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type CharacterResourcesNullableScalarRelationFilter = {
  is?: Prisma.CharacterResourcesWhereInput | null
  isNot?: Prisma.CharacterResourcesWhereInput | null
}

export type CharacterResourcesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  healthCurrent?: Prisma.SortOrder
  healthMax?: Prisma.SortOrder
  focusCurrent?: Prisma.SortOrder
  focusMax?: Prisma.SortOrder
  investitureCurrent?: Prisma.SortOrder
  investitureMax?: Prisma.SortOrder
  investitureActive?: Prisma.SortOrder
}

export type CharacterResourcesAvgOrderByAggregateInput = {
  healthCurrent?: Prisma.SortOrder
  healthMax?: Prisma.SortOrder
  focusCurrent?: Prisma.SortOrder
  focusMax?: Prisma.SortOrder
  investitureCurrent?: Prisma.SortOrder
  investitureMax?: Prisma.SortOrder
}

export type CharacterResourcesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  healthCurrent?: Prisma.SortOrder
  healthMax?: Prisma.SortOrder
  focusCurrent?: Prisma.SortOrder
  focusMax?: Prisma.SortOrder
  investitureCurrent?: Prisma.SortOrder
  investitureMax?: Prisma.SortOrder
  investitureActive?: Prisma.SortOrder
}

export type CharacterResourcesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  healthCurrent?: Prisma.SortOrder
  healthMax?: Prisma.SortOrder
  focusCurrent?: Prisma.SortOrder
  focusMax?: Prisma.SortOrder
  investitureCurrent?: Prisma.SortOrder
  investitureMax?: Prisma.SortOrder
  investitureActive?: Prisma.SortOrder
}

export type CharacterResourcesSumOrderByAggregateInput = {
  healthCurrent?: Prisma.SortOrder
  healthMax?: Prisma.SortOrder
  focusCurrent?: Prisma.SortOrder
  focusMax?: Prisma.SortOrder
  investitureCurrent?: Prisma.SortOrder
  investitureMax?: Prisma.SortOrder
}

export type CharacterResourcesCreateNestedOneWithoutCharacterInput = {
  create?: Prisma.XOR<Prisma.CharacterResourcesCreateWithoutCharacterInput, Prisma.CharacterResourcesUncheckedCreateWithoutCharacterInput>
  connectOrCreate?: Prisma.CharacterResourcesCreateOrConnectWithoutCharacterInput
  connect?: Prisma.CharacterResourcesWhereUniqueInput
}

export type CharacterResourcesUncheckedCreateNestedOneWithoutCharacterInput = {
  create?: Prisma.XOR<Prisma.CharacterResourcesCreateWithoutCharacterInput, Prisma.CharacterResourcesUncheckedCreateWithoutCharacterInput>
  connectOrCreate?: Prisma.CharacterResourcesCreateOrConnectWithoutCharacterInput
  connect?: Prisma.CharacterResourcesWhereUniqueInput
}

export type CharacterResourcesUpdateOneWithoutCharacterNestedInput = {
  create?: Prisma.XOR<Prisma.CharacterResourcesCreateWithoutCharacterInput, Prisma.CharacterResourcesUncheckedCreateWithoutCharacterInput>
  connectOrCreate?: Prisma.CharacterResourcesCreateOrConnectWithoutCharacterInput
  upsert?: Prisma.CharacterResourcesUpsertWithoutCharacterInput
  disconnect?: Prisma.CharacterResourcesWhereInput | boolean
  delete?: Prisma.CharacterResourcesWhereInput | boolean
  connect?: Prisma.CharacterResourcesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CharacterResourcesUpdateToOneWithWhereWithoutCharacterInput, Prisma.CharacterResourcesUpdateWithoutCharacterInput>, Prisma.CharacterResourcesUncheckedUpdateWithoutCharacterInput>
}

export type CharacterResourcesUncheckedUpdateOneWithoutCharacterNestedInput = {
  create?: Prisma.XOR<Prisma.CharacterResourcesCreateWithoutCharacterInput, Prisma.CharacterResourcesUncheckedCreateWithoutCharacterInput>
  connectOrCreate?: Prisma.CharacterResourcesCreateOrConnectWithoutCharacterInput
  upsert?: Prisma.CharacterResourcesUpsertWithoutCharacterInput
  disconnect?: Prisma.CharacterResourcesWhereInput | boolean
  delete?: Prisma.CharacterResourcesWhereInput | boolean
  connect?: Prisma.CharacterResourcesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CharacterResourcesUpdateToOneWithWhereWithoutCharacterInput, Prisma.CharacterResourcesUpdateWithoutCharacterInput>, Prisma.CharacterResourcesUncheckedUpdateWithoutCharacterInput>
}

export type CharacterResourcesCreateWithoutCharacterInput = {
  id?: string
  healthCurrent?: number
  healthMax?: number
  focusCurrent?: number
  focusMax?: number
  investitureCurrent?: number
  investitureMax?: number
  investitureActive?: boolean
}

export type CharacterResourcesUncheckedCreateWithoutCharacterInput = {
  id?: string
  healthCurrent?: number
  healthMax?: number
  focusCurrent?: number
  focusMax?: number
  investitureCurrent?: number
  investitureMax?: number
  investitureActive?: boolean
}

export type CharacterResourcesCreateOrConnectWithoutCharacterInput = {
  where: Prisma.CharacterResourcesWhereUniqueInput
  create: Prisma.XOR<Prisma.CharacterResourcesCreateWithoutCharacterInput, Prisma.CharacterResourcesUncheckedCreateWithoutCharacterInput>
}

export type CharacterResourcesUpsertWithoutCharacterInput = {
  update: Prisma.XOR<Prisma.CharacterResourcesUpdateWithoutCharacterInput, Prisma.CharacterResourcesUncheckedUpdateWithoutCharacterInput>
  create: Prisma.XOR<Prisma.CharacterResourcesCreateWithoutCharacterInput, Prisma.CharacterResourcesUncheckedCreateWithoutCharacterInput>
  where?: Prisma.CharacterResourcesWhereInput
}

export type CharacterResourcesUpdateToOneWithWhereWithoutCharacterInput = {
  where?: Prisma.CharacterResourcesWhereInput
  data: Prisma.XOR<Prisma.CharacterResourcesUpdateWithoutCharacterInput, Prisma.CharacterResourcesUncheckedUpdateWithoutCharacterInput>
}

export type CharacterResourcesUpdateWithoutCharacterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  healthCurrent?: Prisma.IntFieldUpdateOperationsInput | number
  healthMax?: Prisma.IntFieldUpdateOperationsInput | number
  focusCurrent?: Prisma.IntFieldUpdateOperationsInput | number
  focusMax?: Prisma.IntFieldUpdateOperationsInput | number
  investitureCurrent?: Prisma.IntFieldUpdateOperationsInput | number
  investitureMax?: Prisma.IntFieldUpdateOperationsInput | number
  investitureActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type CharacterResourcesUncheckedUpdateWithoutCharacterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  healthCurrent?: Prisma.IntFieldUpdateOperationsInput | number
  healthMax?: Prisma.IntFieldUpdateOperationsInput | number
  focusCurrent?: Prisma.IntFieldUpdateOperationsInput | number
  focusMax?: Prisma.IntFieldUpdateOperationsInput | number
  investitureCurrent?: Prisma.IntFieldUpdateOperationsInput | number
  investitureMax?: Prisma.IntFieldUpdateOperationsInput | number
  investitureActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}



export type CharacterResourcesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  characterId?: boolean
  healthCurrent?: boolean
  healthMax?: boolean
  focusCurrent?: boolean
  focusMax?: boolean
  investitureCurrent?: boolean
  investitureMax?: boolean
  investitureActive?: boolean
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["characterResources"]>

export type CharacterResourcesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  characterId?: boolean
  healthCurrent?: boolean
  healthMax?: boolean
  focusCurrent?: boolean
  focusMax?: boolean
  investitureCurrent?: boolean
  investitureMax?: boolean
  investitureActive?: boolean
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["characterResources"]>

export type CharacterResourcesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  characterId?: boolean
  healthCurrent?: boolean
  healthMax?: boolean
  focusCurrent?: boolean
  focusMax?: boolean
  investitureCurrent?: boolean
  investitureMax?: boolean
  investitureActive?: boolean
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["characterResources"]>

export type CharacterResourcesSelectScalar = {
  id?: boolean
  characterId?: boolean
  healthCurrent?: boolean
  healthMax?: boolean
  focusCurrent?: boolean
  focusMax?: boolean
  investitureCurrent?: boolean
  investitureMax?: boolean
  investitureActive?: boolean
}

export type CharacterResourcesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "characterId" | "healthCurrent" | "healthMax" | "focusCurrent" | "focusMax" | "investitureCurrent" | "investitureMax" | "investitureActive", ExtArgs["result"]["characterResources"]>
export type CharacterResourcesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}
export type CharacterResourcesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}
export type CharacterResourcesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}

export type $CharacterResourcesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CharacterResources"
  objects: {
    character: Prisma.$CharacterPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    characterId: string
    healthCurrent: number
    healthMax: number
    focusCurrent: number
    focusMax: number
    investitureCurrent: number
    investitureMax: number
    investitureActive: boolean
  }, ExtArgs["result"]["characterResources"]>
  composites: {}
}

export type CharacterResourcesGetPayload<S extends boolean | null | undefined | CharacterResourcesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CharacterResourcesPayload, S>

export type CharacterResourcesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CharacterResourcesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CharacterResourcesCountAggregateInputType | true
  }

export interface CharacterResourcesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CharacterResources'], meta: { name: 'CharacterResources' } }
  /**
   * Find zero or one CharacterResources that matches the filter.
   * @param {CharacterResourcesFindUniqueArgs} args - Arguments to find a CharacterResources
   * @example
   * // Get one CharacterResources
   * const characterResources = await prisma.characterResources.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CharacterResourcesFindUniqueArgs>(args: Prisma.SelectSubset<T, CharacterResourcesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CharacterResourcesClient<runtime.Types.Result.GetResult<Prisma.$CharacterResourcesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CharacterResources that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CharacterResourcesFindUniqueOrThrowArgs} args - Arguments to find a CharacterResources
   * @example
   * // Get one CharacterResources
   * const characterResources = await prisma.characterResources.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CharacterResourcesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CharacterResourcesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CharacterResourcesClient<runtime.Types.Result.GetResult<Prisma.$CharacterResourcesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CharacterResources that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CharacterResourcesFindFirstArgs} args - Arguments to find a CharacterResources
   * @example
   * // Get one CharacterResources
   * const characterResources = await prisma.characterResources.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CharacterResourcesFindFirstArgs>(args?: Prisma.SelectSubset<T, CharacterResourcesFindFirstArgs<ExtArgs>>): Prisma.Prisma__CharacterResourcesClient<runtime.Types.Result.GetResult<Prisma.$CharacterResourcesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CharacterResources that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CharacterResourcesFindFirstOrThrowArgs} args - Arguments to find a CharacterResources
   * @example
   * // Get one CharacterResources
   * const characterResources = await prisma.characterResources.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CharacterResourcesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CharacterResourcesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CharacterResourcesClient<runtime.Types.Result.GetResult<Prisma.$CharacterResourcesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CharacterResources that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CharacterResourcesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CharacterResources
   * const characterResources = await prisma.characterResources.findMany()
   * 
   * // Get first 10 CharacterResources
   * const characterResources = await prisma.characterResources.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const characterResourcesWithIdOnly = await prisma.characterResources.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CharacterResourcesFindManyArgs>(args?: Prisma.SelectSubset<T, CharacterResourcesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CharacterResourcesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CharacterResources.
   * @param {CharacterResourcesCreateArgs} args - Arguments to create a CharacterResources.
   * @example
   * // Create one CharacterResources
   * const CharacterResources = await prisma.characterResources.create({
   *   data: {
   *     // ... data to create a CharacterResources
   *   }
   * })
   * 
   */
  create<T extends CharacterResourcesCreateArgs>(args: Prisma.SelectSubset<T, CharacterResourcesCreateArgs<ExtArgs>>): Prisma.Prisma__CharacterResourcesClient<runtime.Types.Result.GetResult<Prisma.$CharacterResourcesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CharacterResources.
   * @param {CharacterResourcesCreateManyArgs} args - Arguments to create many CharacterResources.
   * @example
   * // Create many CharacterResources
   * const characterResources = await prisma.characterResources.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CharacterResourcesCreateManyArgs>(args?: Prisma.SelectSubset<T, CharacterResourcesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CharacterResources and returns the data saved in the database.
   * @param {CharacterResourcesCreateManyAndReturnArgs} args - Arguments to create many CharacterResources.
   * @example
   * // Create many CharacterResources
   * const characterResources = await prisma.characterResources.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CharacterResources and only return the `id`
   * const characterResourcesWithIdOnly = await prisma.characterResources.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CharacterResourcesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CharacterResourcesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CharacterResourcesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CharacterResources.
   * @param {CharacterResourcesDeleteArgs} args - Arguments to delete one CharacterResources.
   * @example
   * // Delete one CharacterResources
   * const CharacterResources = await prisma.characterResources.delete({
   *   where: {
   *     // ... filter to delete one CharacterResources
   *   }
   * })
   * 
   */
  delete<T extends CharacterResourcesDeleteArgs>(args: Prisma.SelectSubset<T, CharacterResourcesDeleteArgs<ExtArgs>>): Prisma.Prisma__CharacterResourcesClient<runtime.Types.Result.GetResult<Prisma.$CharacterResourcesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CharacterResources.
   * @param {CharacterResourcesUpdateArgs} args - Arguments to update one CharacterResources.
   * @example
   * // Update one CharacterResources
   * const characterResources = await prisma.characterResources.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CharacterResourcesUpdateArgs>(args: Prisma.SelectSubset<T, CharacterResourcesUpdateArgs<ExtArgs>>): Prisma.Prisma__CharacterResourcesClient<runtime.Types.Result.GetResult<Prisma.$CharacterResourcesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CharacterResources.
   * @param {CharacterResourcesDeleteManyArgs} args - Arguments to filter CharacterResources to delete.
   * @example
   * // Delete a few CharacterResources
   * const { count } = await prisma.characterResources.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CharacterResourcesDeleteManyArgs>(args?: Prisma.SelectSubset<T, CharacterResourcesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CharacterResources.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CharacterResourcesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CharacterResources
   * const characterResources = await prisma.characterResources.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CharacterResourcesUpdateManyArgs>(args: Prisma.SelectSubset<T, CharacterResourcesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CharacterResources and returns the data updated in the database.
   * @param {CharacterResourcesUpdateManyAndReturnArgs} args - Arguments to update many CharacterResources.
   * @example
   * // Update many CharacterResources
   * const characterResources = await prisma.characterResources.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CharacterResources and only return the `id`
   * const characterResourcesWithIdOnly = await prisma.characterResources.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CharacterResourcesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CharacterResourcesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CharacterResourcesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CharacterResources.
   * @param {CharacterResourcesUpsertArgs} args - Arguments to update or create a CharacterResources.
   * @example
   * // Update or create a CharacterResources
   * const characterResources = await prisma.characterResources.upsert({
   *   create: {
   *     // ... data to create a CharacterResources
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CharacterResources we want to update
   *   }
   * })
   */
  upsert<T extends CharacterResourcesUpsertArgs>(args: Prisma.SelectSubset<T, CharacterResourcesUpsertArgs<ExtArgs>>): Prisma.Prisma__CharacterResourcesClient<runtime.Types.Result.GetResult<Prisma.$CharacterResourcesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CharacterResources.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CharacterResourcesCountArgs} args - Arguments to filter CharacterResources to count.
   * @example
   * // Count the number of CharacterResources
   * const count = await prisma.characterResources.count({
   *   where: {
   *     // ... the filter for the CharacterResources we want to count
   *   }
   * })
  **/
  count<T extends CharacterResourcesCountArgs>(
    args?: Prisma.Subset<T, CharacterResourcesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CharacterResourcesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CharacterResources.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CharacterResourcesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CharacterResourcesAggregateArgs>(args: Prisma.Subset<T, CharacterResourcesAggregateArgs>): Prisma.PrismaPromise<GetCharacterResourcesAggregateType<T>>

  /**
   * Group by CharacterResources.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CharacterResourcesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CharacterResourcesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CharacterResourcesGroupByArgs['orderBy'] }
      : { orderBy?: CharacterResourcesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CharacterResourcesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCharacterResourcesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CharacterResources model
 */
readonly fields: CharacterResourcesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CharacterResources.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CharacterResourcesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  character<T extends Prisma.CharacterDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CharacterDefaultArgs<ExtArgs>>): Prisma.Prisma__CharacterClient<runtime.Types.Result.GetResult<Prisma.$CharacterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CharacterResources model
 */
export interface CharacterResourcesFieldRefs {
  readonly id: Prisma.FieldRef<"CharacterResources", 'String'>
  readonly characterId: Prisma.FieldRef<"CharacterResources", 'String'>
  readonly healthCurrent: Prisma.FieldRef<"CharacterResources", 'Int'>
  readonly healthMax: Prisma.FieldRef<"CharacterResources", 'Int'>
  readonly focusCurrent: Prisma.FieldRef<"CharacterResources", 'Int'>
  readonly focusMax: Prisma.FieldRef<"CharacterResources", 'Int'>
  readonly investitureCurrent: Prisma.FieldRef<"CharacterResources", 'Int'>
  readonly investitureMax: Prisma.FieldRef<"CharacterResources", 'Int'>
  readonly investitureActive: Prisma.FieldRef<"CharacterResources", 'Boolean'>
}
    

// Custom InputTypes
/**
 * CharacterResources findUnique
 */
export type CharacterResourcesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterResources
   */
  select?: Prisma.CharacterResourcesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterResources
   */
  omit?: Prisma.CharacterResourcesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterResourcesInclude<ExtArgs> | null
  /**
   * Filter, which CharacterResources to fetch.
   */
  where: Prisma.CharacterResourcesWhereUniqueInput
}

/**
 * CharacterResources findUniqueOrThrow
 */
export type CharacterResourcesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterResources
   */
  select?: Prisma.CharacterResourcesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterResources
   */
  omit?: Prisma.CharacterResourcesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterResourcesInclude<ExtArgs> | null
  /**
   * Filter, which CharacterResources to fetch.
   */
  where: Prisma.CharacterResourcesWhereUniqueInput
}

/**
 * CharacterResources findFirst
 */
export type CharacterResourcesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterResources
   */
  select?: Prisma.CharacterResourcesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterResources
   */
  omit?: Prisma.CharacterResourcesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterResourcesInclude<ExtArgs> | null
  /**
   * Filter, which CharacterResources to fetch.
   */
  where?: Prisma.CharacterResourcesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CharacterResources to fetch.
   */
  orderBy?: Prisma.CharacterResourcesOrderByWithRelationInput | Prisma.CharacterResourcesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CharacterResources.
   */
  cursor?: Prisma.CharacterResourcesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CharacterResources from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CharacterResources.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CharacterResources.
   */
  distinct?: Prisma.CharacterResourcesScalarFieldEnum | Prisma.CharacterResourcesScalarFieldEnum[]
}

/**
 * CharacterResources findFirstOrThrow
 */
export type CharacterResourcesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterResources
   */
  select?: Prisma.CharacterResourcesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterResources
   */
  omit?: Prisma.CharacterResourcesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterResourcesInclude<ExtArgs> | null
  /**
   * Filter, which CharacterResources to fetch.
   */
  where?: Prisma.CharacterResourcesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CharacterResources to fetch.
   */
  orderBy?: Prisma.CharacterResourcesOrderByWithRelationInput | Prisma.CharacterResourcesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CharacterResources.
   */
  cursor?: Prisma.CharacterResourcesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CharacterResources from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CharacterResources.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CharacterResources.
   */
  distinct?: Prisma.CharacterResourcesScalarFieldEnum | Prisma.CharacterResourcesScalarFieldEnum[]
}

/**
 * CharacterResources findMany
 */
export type CharacterResourcesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterResources
   */
  select?: Prisma.CharacterResourcesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterResources
   */
  omit?: Prisma.CharacterResourcesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterResourcesInclude<ExtArgs> | null
  /**
   * Filter, which CharacterResources to fetch.
   */
  where?: Prisma.CharacterResourcesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CharacterResources to fetch.
   */
  orderBy?: Prisma.CharacterResourcesOrderByWithRelationInput | Prisma.CharacterResourcesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CharacterResources.
   */
  cursor?: Prisma.CharacterResourcesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CharacterResources from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CharacterResources.
   */
  skip?: number
  distinct?: Prisma.CharacterResourcesScalarFieldEnum | Prisma.CharacterResourcesScalarFieldEnum[]
}

/**
 * CharacterResources create
 */
export type CharacterResourcesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterResources
   */
  select?: Prisma.CharacterResourcesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterResources
   */
  omit?: Prisma.CharacterResourcesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterResourcesInclude<ExtArgs> | null
  /**
   * The data needed to create a CharacterResources.
   */
  data: Prisma.XOR<Prisma.CharacterResourcesCreateInput, Prisma.CharacterResourcesUncheckedCreateInput>
}

/**
 * CharacterResources createMany
 */
export type CharacterResourcesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CharacterResources.
   */
  data: Prisma.CharacterResourcesCreateManyInput | Prisma.CharacterResourcesCreateManyInput[]
}

/**
 * CharacterResources createManyAndReturn
 */
export type CharacterResourcesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterResources
   */
  select?: Prisma.CharacterResourcesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterResources
   */
  omit?: Prisma.CharacterResourcesOmit<ExtArgs> | null
  /**
   * The data used to create many CharacterResources.
   */
  data: Prisma.CharacterResourcesCreateManyInput | Prisma.CharacterResourcesCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterResourcesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CharacterResources update
 */
export type CharacterResourcesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterResources
   */
  select?: Prisma.CharacterResourcesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterResources
   */
  omit?: Prisma.CharacterResourcesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterResourcesInclude<ExtArgs> | null
  /**
   * The data needed to update a CharacterResources.
   */
  data: Prisma.XOR<Prisma.CharacterResourcesUpdateInput, Prisma.CharacterResourcesUncheckedUpdateInput>
  /**
   * Choose, which CharacterResources to update.
   */
  where: Prisma.CharacterResourcesWhereUniqueInput
}

/**
 * CharacterResources updateMany
 */
export type CharacterResourcesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CharacterResources.
   */
  data: Prisma.XOR<Prisma.CharacterResourcesUpdateManyMutationInput, Prisma.CharacterResourcesUncheckedUpdateManyInput>
  /**
   * Filter which CharacterResources to update
   */
  where?: Prisma.CharacterResourcesWhereInput
  /**
   * Limit how many CharacterResources to update.
   */
  limit?: number
}

/**
 * CharacterResources updateManyAndReturn
 */
export type CharacterResourcesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterResources
   */
  select?: Prisma.CharacterResourcesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterResources
   */
  omit?: Prisma.CharacterResourcesOmit<ExtArgs> | null
  /**
   * The data used to update CharacterResources.
   */
  data: Prisma.XOR<Prisma.CharacterResourcesUpdateManyMutationInput, Prisma.CharacterResourcesUncheckedUpdateManyInput>
  /**
   * Filter which CharacterResources to update
   */
  where?: Prisma.CharacterResourcesWhereInput
  /**
   * Limit how many CharacterResources to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterResourcesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CharacterResources upsert
 */
export type CharacterResourcesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterResources
   */
  select?: Prisma.CharacterResourcesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterResources
   */
  omit?: Prisma.CharacterResourcesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterResourcesInclude<ExtArgs> | null
  /**
   * The filter to search for the CharacterResources to update in case it exists.
   */
  where: Prisma.CharacterResourcesWhereUniqueInput
  /**
   * In case the CharacterResources found by the `where` argument doesn't exist, create a new CharacterResources with this data.
   */
  create: Prisma.XOR<Prisma.CharacterResourcesCreateInput, Prisma.CharacterResourcesUncheckedCreateInput>
  /**
   * In case the CharacterResources was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CharacterResourcesUpdateInput, Prisma.CharacterResourcesUncheckedUpdateInput>
}

/**
 * CharacterResources delete
 */
export type CharacterResourcesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterResources
   */
  select?: Prisma.CharacterResourcesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterResources
   */
  omit?: Prisma.CharacterResourcesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterResourcesInclude<ExtArgs> | null
  /**
   * Filter which CharacterResources to delete.
   */
  where: Prisma.CharacterResourcesWhereUniqueInput
}

/**
 * CharacterResources deleteMany
 */
export type CharacterResourcesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CharacterResources to delete
   */
  where?: Prisma.CharacterResourcesWhereInput
  /**
   * Limit how many CharacterResources to delete.
   */
  limit?: number
}

/**
 * CharacterResources without action
 */
export type CharacterResourcesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterResources
   */
  select?: Prisma.CharacterResourcesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterResources
   */
  omit?: Prisma.CharacterResourcesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterResourcesInclude<ExtArgs> | null
}
