
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CharacterTalents` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model CharacterTalents
 * 
 */
export type CharacterTalentsModel = runtime.Types.Result.DefaultSelection<Prisma.$CharacterTalentsPayload>

export type AggregateCharacterTalents = {
  _count: CharacterTalentsCountAggregateOutputType | null
  _avg: CharacterTalentsAvgAggregateOutputType | null
  _sum: CharacterTalentsSumAggregateOutputType | null
  _min: CharacterTalentsMinAggregateOutputType | null
  _max: CharacterTalentsMaxAggregateOutputType | null
}

export type CharacterTalentsAvgAggregateOutputType = {
  totalPoints: number | null
  pointsSpent: number | null
  pointsRemaining: number | null
}

export type CharacterTalentsSumAggregateOutputType = {
  totalPoints: number | null
  pointsSpent: number | null
  pointsRemaining: number | null
}

export type CharacterTalentsMinAggregateOutputType = {
  id: string | null
  characterId: string | null
  totalPoints: number | null
  pointsSpent: number | null
  pointsRemaining: number | null
  finalized: boolean | null
  totalTalents: string | null
  pendingTalents: string | null
  pendingTrees: string | null
}

export type CharacterTalentsMaxAggregateOutputType = {
  id: string | null
  characterId: string | null
  totalPoints: number | null
  pointsSpent: number | null
  pointsRemaining: number | null
  finalized: boolean | null
  totalTalents: string | null
  pendingTalents: string | null
  pendingTrees: string | null
}

export type CharacterTalentsCountAggregateOutputType = {
  id: number
  characterId: number
  totalPoints: number
  pointsSpent: number
  pointsRemaining: number
  finalized: number
  totalTalents: number
  pendingTalents: number
  pendingTrees: number
  _all: number
}


export type CharacterTalentsAvgAggregateInputType = {
  totalPoints?: true
  pointsSpent?: true
  pointsRemaining?: true
}

export type CharacterTalentsSumAggregateInputType = {
  totalPoints?: true
  pointsSpent?: true
  pointsRemaining?: true
}

export type CharacterTalentsMinAggregateInputType = {
  id?: true
  characterId?: true
  totalPoints?: true
  pointsSpent?: true
  pointsRemaining?: true
  finalized?: true
  totalTalents?: true
  pendingTalents?: true
  pendingTrees?: true
}

export type CharacterTalentsMaxAggregateInputType = {
  id?: true
  characterId?: true
  totalPoints?: true
  pointsSpent?: true
  pointsRemaining?: true
  finalized?: true
  totalTalents?: true
  pendingTalents?: true
  pendingTrees?: true
}

export type CharacterTalentsCountAggregateInputType = {
  id?: true
  characterId?: true
  totalPoints?: true
  pointsSpent?: true
  pointsRemaining?: true
  finalized?: true
  totalTalents?: true
  pendingTalents?: true
  pendingTrees?: true
  _all?: true
}

export type CharacterTalentsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CharacterTalents to aggregate.
   */
  where?: Prisma.CharacterTalentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CharacterTalents to fetch.
   */
  orderBy?: Prisma.CharacterTalentsOrderByWithRelationInput | Prisma.CharacterTalentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CharacterTalentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CharacterTalents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CharacterTalents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CharacterTalents
  **/
  _count?: true | CharacterTalentsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CharacterTalentsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CharacterTalentsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CharacterTalentsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CharacterTalentsMaxAggregateInputType
}

export type GetCharacterTalentsAggregateType<T extends CharacterTalentsAggregateArgs> = {
      [P in keyof T & keyof AggregateCharacterTalents]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCharacterTalents[P]>
    : Prisma.GetScalarType<T[P], AggregateCharacterTalents[P]>
}




export type CharacterTalentsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CharacterTalentsWhereInput
  orderBy?: Prisma.CharacterTalentsOrderByWithAggregationInput | Prisma.CharacterTalentsOrderByWithAggregationInput[]
  by: Prisma.CharacterTalentsScalarFieldEnum[] | Prisma.CharacterTalentsScalarFieldEnum
  having?: Prisma.CharacterTalentsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CharacterTalentsCountAggregateInputType | true
  _avg?: CharacterTalentsAvgAggregateInputType
  _sum?: CharacterTalentsSumAggregateInputType
  _min?: CharacterTalentsMinAggregateInputType
  _max?: CharacterTalentsMaxAggregateInputType
}

export type CharacterTalentsGroupByOutputType = {
  id: string
  characterId: string
  totalPoints: number
  pointsSpent: number
  pointsRemaining: number
  finalized: boolean
  totalTalents: string
  pendingTalents: string
  pendingTrees: string
  _count: CharacterTalentsCountAggregateOutputType | null
  _avg: CharacterTalentsAvgAggregateOutputType | null
  _sum: CharacterTalentsSumAggregateOutputType | null
  _min: CharacterTalentsMinAggregateOutputType | null
  _max: CharacterTalentsMaxAggregateOutputType | null
}

type GetCharacterTalentsGroupByPayload<T extends CharacterTalentsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CharacterTalentsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CharacterTalentsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CharacterTalentsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CharacterTalentsGroupByOutputType[P]>
      }
    >
  >



export type CharacterTalentsWhereInput = {
  AND?: Prisma.CharacterTalentsWhereInput | Prisma.CharacterTalentsWhereInput[]
  OR?: Prisma.CharacterTalentsWhereInput[]
  NOT?: Prisma.CharacterTalentsWhereInput | Prisma.CharacterTalentsWhereInput[]
  id?: Prisma.StringFilter<"CharacterTalents"> | string
  characterId?: Prisma.StringFilter<"CharacterTalents"> | string
  totalPoints?: Prisma.IntFilter<"CharacterTalents"> | number
  pointsSpent?: Prisma.IntFilter<"CharacterTalents"> | number
  pointsRemaining?: Prisma.IntFilter<"CharacterTalents"> | number
  finalized?: Prisma.BoolFilter<"CharacterTalents"> | boolean
  totalTalents?: Prisma.StringFilter<"CharacterTalents"> | string
  pendingTalents?: Prisma.StringFilter<"CharacterTalents"> | string
  pendingTrees?: Prisma.StringFilter<"CharacterTalents"> | string
  character?: Prisma.XOR<Prisma.CharacterScalarRelationFilter, Prisma.CharacterWhereInput>
}

export type CharacterTalentsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  totalPoints?: Prisma.SortOrder
  pointsSpent?: Prisma.SortOrder
  pointsRemaining?: Prisma.SortOrder
  finalized?: Prisma.SortOrder
  totalTalents?: Prisma.SortOrder
  pendingTalents?: Prisma.SortOrder
  pendingTrees?: Prisma.SortOrder
  character?: Prisma.CharacterOrderByWithRelationInput
}

export type CharacterTalentsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  characterId?: string
  AND?: Prisma.CharacterTalentsWhereInput | Prisma.CharacterTalentsWhereInput[]
  OR?: Prisma.CharacterTalentsWhereInput[]
  NOT?: Prisma.CharacterTalentsWhereInput | Prisma.CharacterTalentsWhereInput[]
  totalPoints?: Prisma.IntFilter<"CharacterTalents"> | number
  pointsSpent?: Prisma.IntFilter<"CharacterTalents"> | number
  pointsRemaining?: Prisma.IntFilter<"CharacterTalents"> | number
  finalized?: Prisma.BoolFilter<"CharacterTalents"> | boolean
  totalTalents?: Prisma.StringFilter<"CharacterTalents"> | string
  pendingTalents?: Prisma.StringFilter<"CharacterTalents"> | string
  pendingTrees?: Prisma.StringFilter<"CharacterTalents"> | string
  character?: Prisma.XOR<Prisma.CharacterScalarRelationFilter, Prisma.CharacterWhereInput>
}, "id" | "characterId">

export type CharacterTalentsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  totalPoints?: Prisma.SortOrder
  pointsSpent?: Prisma.SortOrder
  pointsRemaining?: Prisma.SortOrder
  finalized?: Prisma.SortOrder
  totalTalents?: Prisma.SortOrder
  pendingTalents?: Prisma.SortOrder
  pendingTrees?: Prisma.SortOrder
  _count?: Prisma.CharacterTalentsCountOrderByAggregateInput
  _avg?: Prisma.CharacterTalentsAvgOrderByAggregateInput
  _max?: Prisma.CharacterTalentsMaxOrderByAggregateInput
  _min?: Prisma.CharacterTalentsMinOrderByAggregateInput
  _sum?: Prisma.CharacterTalentsSumOrderByAggregateInput
}

export type CharacterTalentsScalarWhereWithAggregatesInput = {
  AND?: Prisma.CharacterTalentsScalarWhereWithAggregatesInput | Prisma.CharacterTalentsScalarWhereWithAggregatesInput[]
  OR?: Prisma.CharacterTalentsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CharacterTalentsScalarWhereWithAggregatesInput | Prisma.CharacterTalentsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CharacterTalents"> | string
  characterId?: Prisma.StringWithAggregatesFilter<"CharacterTalents"> | string
  totalPoints?: Prisma.IntWithAggregatesFilter<"CharacterTalents"> | number
  pointsSpent?: Prisma.IntWithAggregatesFilter<"CharacterTalents"> | number
  pointsRemaining?: Prisma.IntWithAggregatesFilter<"CharacterTalents"> | number
  finalized?: Prisma.BoolWithAggregatesFilter<"CharacterTalents"> | boolean
  totalTalents?: Prisma.StringWithAggregatesFilter<"CharacterTalents"> | string
  pendingTalents?: Prisma.StringWithAggregatesFilter<"CharacterTalents"> | string
  pendingTrees?: Prisma.StringWithAggregatesFilter<"CharacterTalents"> | string
}

export type CharacterTalentsCreateInput = {
  id?: string
  totalPoints?: number
  pointsSpent?: number
  pointsRemaining?: number
  finalized?: boolean
  totalTalents?: string
  pendingTalents?: string
  pendingTrees?: string
  character: Prisma.CharacterCreateNestedOneWithoutTalentsStateInput
}

export type CharacterTalentsUncheckedCreateInput = {
  id?: string
  characterId: string
  totalPoints?: number
  pointsSpent?: number
  pointsRemaining?: number
  finalized?: boolean
  totalTalents?: string
  pendingTalents?: string
  pendingTrees?: string
}

export type CharacterTalentsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  totalPoints?: Prisma.IntFieldUpdateOperationsInput | number
  pointsSpent?: Prisma.IntFieldUpdateOperationsInput | number
  pointsRemaining?: Prisma.IntFieldUpdateOperationsInput | number
  finalized?: Prisma.BoolFieldUpdateOperationsInput | boolean
  totalTalents?: Prisma.StringFieldUpdateOperationsInput | string
  pendingTalents?: Prisma.StringFieldUpdateOperationsInput | string
  pendingTrees?: Prisma.StringFieldUpdateOperationsInput | string
  character?: Prisma.CharacterUpdateOneRequiredWithoutTalentsStateNestedInput
}

export type CharacterTalentsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  characterId?: Prisma.StringFieldUpdateOperationsInput | string
  totalPoints?: Prisma.IntFieldUpdateOperationsInput | number
  pointsSpent?: Prisma.IntFieldUpdateOperationsInput | number
  pointsRemaining?: Prisma.IntFieldUpdateOperationsInput | number
  finalized?: Prisma.BoolFieldUpdateOperationsInput | boolean
  totalTalents?: Prisma.StringFieldUpdateOperationsInput | string
  pendingTalents?: Prisma.StringFieldUpdateOperationsInput | string
  pendingTrees?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CharacterTalentsCreateManyInput = {
  id?: string
  characterId: string
  totalPoints?: number
  pointsSpent?: number
  pointsRemaining?: number
  finalized?: boolean
  totalTalents?: string
  pendingTalents?: string
  pendingTrees?: string
}

export type CharacterTalentsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  totalPoints?: Prisma.IntFieldUpdateOperationsInput | number
  pointsSpent?: Prisma.IntFieldUpdateOperationsInput | number
  pointsRemaining?: Prisma.IntFieldUpdateOperationsInput | number
  finalized?: Prisma.BoolFieldUpdateOperationsInput | boolean
  totalTalents?: Prisma.StringFieldUpdateOperationsInput | string
  pendingTalents?: Prisma.StringFieldUpdateOperationsInput | string
  pendingTrees?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CharacterTalentsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  characterId?: Prisma.StringFieldUpdateOperationsInput | string
  totalPoints?: Prisma.IntFieldUpdateOperationsInput | number
  pointsSpent?: Prisma.IntFieldUpdateOperationsInput | number
  pointsRemaining?: Prisma.IntFieldUpdateOperationsInput | number
  finalized?: Prisma.BoolFieldUpdateOperationsInput | boolean
  totalTalents?: Prisma.StringFieldUpdateOperationsInput | string
  pendingTalents?: Prisma.StringFieldUpdateOperationsInput | string
  pendingTrees?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CharacterTalentsNullableScalarRelationFilter = {
  is?: Prisma.CharacterTalentsWhereInput | null
  isNot?: Prisma.CharacterTalentsWhereInput | null
}

export type CharacterTalentsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  totalPoints?: Prisma.SortOrder
  pointsSpent?: Prisma.SortOrder
  pointsRemaining?: Prisma.SortOrder
  finalized?: Prisma.SortOrder
  totalTalents?: Prisma.SortOrder
  pendingTalents?: Prisma.SortOrder
  pendingTrees?: Prisma.SortOrder
}

export type CharacterTalentsAvgOrderByAggregateInput = {
  totalPoints?: Prisma.SortOrder
  pointsSpent?: Prisma.SortOrder
  pointsRemaining?: Prisma.SortOrder
}

export type CharacterTalentsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  totalPoints?: Prisma.SortOrder
  pointsSpent?: Prisma.SortOrder
  pointsRemaining?: Prisma.SortOrder
  finalized?: Prisma.SortOrder
  totalTalents?: Prisma.SortOrder
  pendingTalents?: Prisma.SortOrder
  pendingTrees?: Prisma.SortOrder
}

export type CharacterTalentsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  totalPoints?: Prisma.SortOrder
  pointsSpent?: Prisma.SortOrder
  pointsRemaining?: Prisma.SortOrder
  finalized?: Prisma.SortOrder
  totalTalents?: Prisma.SortOrder
  pendingTalents?: Prisma.SortOrder
  pendingTrees?: Prisma.SortOrder
}

export type CharacterTalentsSumOrderByAggregateInput = {
  totalPoints?: Prisma.SortOrder
  pointsSpent?: Prisma.SortOrder
  pointsRemaining?: Prisma.SortOrder
}

export type CharacterTalentsCreateNestedOneWithoutCharacterInput = {
  create?: Prisma.XOR<Prisma.CharacterTalentsCreateWithoutCharacterInput, Prisma.CharacterTalentsUncheckedCreateWithoutCharacterInput>
  connectOrCreate?: Prisma.CharacterTalentsCreateOrConnectWithoutCharacterInput
  connect?: Prisma.CharacterTalentsWhereUniqueInput
}

export type CharacterTalentsUncheckedCreateNestedOneWithoutCharacterInput = {
  create?: Prisma.XOR<Prisma.CharacterTalentsCreateWithoutCharacterInput, Prisma.CharacterTalentsUncheckedCreateWithoutCharacterInput>
  connectOrCreate?: Prisma.CharacterTalentsCreateOrConnectWithoutCharacterInput
  connect?: Prisma.CharacterTalentsWhereUniqueInput
}

export type CharacterTalentsUpdateOneWithoutCharacterNestedInput = {
  create?: Prisma.XOR<Prisma.CharacterTalentsCreateWithoutCharacterInput, Prisma.CharacterTalentsUncheckedCreateWithoutCharacterInput>
  connectOrCreate?: Prisma.CharacterTalentsCreateOrConnectWithoutCharacterInput
  upsert?: Prisma.CharacterTalentsUpsertWithoutCharacterInput
  disconnect?: Prisma.CharacterTalentsWhereInput | boolean
  delete?: Prisma.CharacterTalentsWhereInput | boolean
  connect?: Prisma.CharacterTalentsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CharacterTalentsUpdateToOneWithWhereWithoutCharacterInput, Prisma.CharacterTalentsUpdateWithoutCharacterInput>, Prisma.CharacterTalentsUncheckedUpdateWithoutCharacterInput>
}

export type CharacterTalentsUncheckedUpdateOneWithoutCharacterNestedInput = {
  create?: Prisma.XOR<Prisma.CharacterTalentsCreateWithoutCharacterInput, Prisma.CharacterTalentsUncheckedCreateWithoutCharacterInput>
  connectOrCreate?: Prisma.CharacterTalentsCreateOrConnectWithoutCharacterInput
  upsert?: Prisma.CharacterTalentsUpsertWithoutCharacterInput
  disconnect?: Prisma.CharacterTalentsWhereInput | boolean
  delete?: Prisma.CharacterTalentsWhereInput | boolean
  connect?: Prisma.CharacterTalentsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CharacterTalentsUpdateToOneWithWhereWithoutCharacterInput, Prisma.CharacterTalentsUpdateWithoutCharacterInput>, Prisma.CharacterTalentsUncheckedUpdateWithoutCharacterInput>
}

export type CharacterTalentsCreateWithoutCharacterInput = {
  id?: string
  totalPoints?: number
  pointsSpent?: number
  pointsRemaining?: number
  finalized?: boolean
  totalTalents?: string
  pendingTalents?: string
  pendingTrees?: string
}

export type CharacterTalentsUncheckedCreateWithoutCharacterInput = {
  id?: string
  totalPoints?: number
  pointsSpent?: number
  pointsRemaining?: number
  finalized?: boolean
  totalTalents?: string
  pendingTalents?: string
  pendingTrees?: string
}

export type CharacterTalentsCreateOrConnectWithoutCharacterInput = {
  where: Prisma.CharacterTalentsWhereUniqueInput
  create: Prisma.XOR<Prisma.CharacterTalentsCreateWithoutCharacterInput, Prisma.CharacterTalentsUncheckedCreateWithoutCharacterInput>
}

export type CharacterTalentsUpsertWithoutCharacterInput = {
  update: Prisma.XOR<Prisma.CharacterTalentsUpdateWithoutCharacterInput, Prisma.CharacterTalentsUncheckedUpdateWithoutCharacterInput>
  create: Prisma.XOR<Prisma.CharacterTalentsCreateWithoutCharacterInput, Prisma.CharacterTalentsUncheckedCreateWithoutCharacterInput>
  where?: Prisma.CharacterTalentsWhereInput
}

export type CharacterTalentsUpdateToOneWithWhereWithoutCharacterInput = {
  where?: Prisma.CharacterTalentsWhereInput
  data: Prisma.XOR<Prisma.CharacterTalentsUpdateWithoutCharacterInput, Prisma.CharacterTalentsUncheckedUpdateWithoutCharacterInput>
}

export type CharacterTalentsUpdateWithoutCharacterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  totalPoints?: Prisma.IntFieldUpdateOperationsInput | number
  pointsSpent?: Prisma.IntFieldUpdateOperationsInput | number
  pointsRemaining?: Prisma.IntFieldUpdateOperationsInput | number
  finalized?: Prisma.BoolFieldUpdateOperationsInput | boolean
  totalTalents?: Prisma.StringFieldUpdateOperationsInput | string
  pendingTalents?: Prisma.StringFieldUpdateOperationsInput | string
  pendingTrees?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CharacterTalentsUncheckedUpdateWithoutCharacterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  totalPoints?: Prisma.IntFieldUpdateOperationsInput | number
  pointsSpent?: Prisma.IntFieldUpdateOperationsInput | number
  pointsRemaining?: Prisma.IntFieldUpdateOperationsInput | number
  finalized?: Prisma.BoolFieldUpdateOperationsInput | boolean
  totalTalents?: Prisma.StringFieldUpdateOperationsInput | string
  pendingTalents?: Prisma.StringFieldUpdateOperationsInput | string
  pendingTrees?: Prisma.StringFieldUpdateOperationsInput | string
}



export type CharacterTalentsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  characterId?: boolean
  totalPoints?: boolean
  pointsSpent?: boolean
  pointsRemaining?: boolean
  finalized?: boolean
  totalTalents?: boolean
  pendingTalents?: boolean
  pendingTrees?: boolean
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["characterTalents"]>

export type CharacterTalentsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  characterId?: boolean
  totalPoints?: boolean
  pointsSpent?: boolean
  pointsRemaining?: boolean
  finalized?: boolean
  totalTalents?: boolean
  pendingTalents?: boolean
  pendingTrees?: boolean
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["characterTalents"]>

export type CharacterTalentsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  characterId?: boolean
  totalPoints?: boolean
  pointsSpent?: boolean
  pointsRemaining?: boolean
  finalized?: boolean
  totalTalents?: boolean
  pendingTalents?: boolean
  pendingTrees?: boolean
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["characterTalents"]>

export type CharacterTalentsSelectScalar = {
  id?: boolean
  characterId?: boolean
  totalPoints?: boolean
  pointsSpent?: boolean
  pointsRemaining?: boolean
  finalized?: boolean
  totalTalents?: boolean
  pendingTalents?: boolean
  pendingTrees?: boolean
}

export type CharacterTalentsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "characterId" | "totalPoints" | "pointsSpent" | "pointsRemaining" | "finalized" | "totalTalents" | "pendingTalents" | "pendingTrees", ExtArgs["result"]["characterTalents"]>
export type CharacterTalentsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}
export type CharacterTalentsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}
export type CharacterTalentsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}

export type $CharacterTalentsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CharacterTalents"
  objects: {
    character: Prisma.$CharacterPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    characterId: string
    totalPoints: number
    pointsSpent: number
    pointsRemaining: number
    finalized: boolean
    totalTalents: string
    pendingTalents: string
    pendingTrees: string
  }, ExtArgs["result"]["characterTalents"]>
  composites: {}
}

export type CharacterTalentsGetPayload<S extends boolean | null | undefined | CharacterTalentsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CharacterTalentsPayload, S>

export type CharacterTalentsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CharacterTalentsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CharacterTalentsCountAggregateInputType | true
  }

export interface CharacterTalentsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CharacterTalents'], meta: { name: 'CharacterTalents' } }
  /**
   * Find zero or one CharacterTalents that matches the filter.
   * @param {CharacterTalentsFindUniqueArgs} args - Arguments to find a CharacterTalents
   * @example
   * // Get one CharacterTalents
   * const characterTalents = await prisma.characterTalents.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CharacterTalentsFindUniqueArgs>(args: Prisma.SelectSubset<T, CharacterTalentsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CharacterTalentsClient<runtime.Types.Result.GetResult<Prisma.$CharacterTalentsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CharacterTalents that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CharacterTalentsFindUniqueOrThrowArgs} args - Arguments to find a CharacterTalents
   * @example
   * // Get one CharacterTalents
   * const characterTalents = await prisma.characterTalents.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CharacterTalentsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CharacterTalentsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CharacterTalentsClient<runtime.Types.Result.GetResult<Prisma.$CharacterTalentsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CharacterTalents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CharacterTalentsFindFirstArgs} args - Arguments to find a CharacterTalents
   * @example
   * // Get one CharacterTalents
   * const characterTalents = await prisma.characterTalents.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CharacterTalentsFindFirstArgs>(args?: Prisma.SelectSubset<T, CharacterTalentsFindFirstArgs<ExtArgs>>): Prisma.Prisma__CharacterTalentsClient<runtime.Types.Result.GetResult<Prisma.$CharacterTalentsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CharacterTalents that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CharacterTalentsFindFirstOrThrowArgs} args - Arguments to find a CharacterTalents
   * @example
   * // Get one CharacterTalents
   * const characterTalents = await prisma.characterTalents.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CharacterTalentsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CharacterTalentsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CharacterTalentsClient<runtime.Types.Result.GetResult<Prisma.$CharacterTalentsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CharacterTalents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CharacterTalentsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CharacterTalents
   * const characterTalents = await prisma.characterTalents.findMany()
   * 
   * // Get first 10 CharacterTalents
   * const characterTalents = await prisma.characterTalents.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const characterTalentsWithIdOnly = await prisma.characterTalents.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CharacterTalentsFindManyArgs>(args?: Prisma.SelectSubset<T, CharacterTalentsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CharacterTalentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CharacterTalents.
   * @param {CharacterTalentsCreateArgs} args - Arguments to create a CharacterTalents.
   * @example
   * // Create one CharacterTalents
   * const CharacterTalents = await prisma.characterTalents.create({
   *   data: {
   *     // ... data to create a CharacterTalents
   *   }
   * })
   * 
   */
  create<T extends CharacterTalentsCreateArgs>(args: Prisma.SelectSubset<T, CharacterTalentsCreateArgs<ExtArgs>>): Prisma.Prisma__CharacterTalentsClient<runtime.Types.Result.GetResult<Prisma.$CharacterTalentsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CharacterTalents.
   * @param {CharacterTalentsCreateManyArgs} args - Arguments to create many CharacterTalents.
   * @example
   * // Create many CharacterTalents
   * const characterTalents = await prisma.characterTalents.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CharacterTalentsCreateManyArgs>(args?: Prisma.SelectSubset<T, CharacterTalentsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CharacterTalents and returns the data saved in the database.
   * @param {CharacterTalentsCreateManyAndReturnArgs} args - Arguments to create many CharacterTalents.
   * @example
   * // Create many CharacterTalents
   * const characterTalents = await prisma.characterTalents.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CharacterTalents and only return the `id`
   * const characterTalentsWithIdOnly = await prisma.characterTalents.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CharacterTalentsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CharacterTalentsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CharacterTalentsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CharacterTalents.
   * @param {CharacterTalentsDeleteArgs} args - Arguments to delete one CharacterTalents.
   * @example
   * // Delete one CharacterTalents
   * const CharacterTalents = await prisma.characterTalents.delete({
   *   where: {
   *     // ... filter to delete one CharacterTalents
   *   }
   * })
   * 
   */
  delete<T extends CharacterTalentsDeleteArgs>(args: Prisma.SelectSubset<T, CharacterTalentsDeleteArgs<ExtArgs>>): Prisma.Prisma__CharacterTalentsClient<runtime.Types.Result.GetResult<Prisma.$CharacterTalentsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CharacterTalents.
   * @param {CharacterTalentsUpdateArgs} args - Arguments to update one CharacterTalents.
   * @example
   * // Update one CharacterTalents
   * const characterTalents = await prisma.characterTalents.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CharacterTalentsUpdateArgs>(args: Prisma.SelectSubset<T, CharacterTalentsUpdateArgs<ExtArgs>>): Prisma.Prisma__CharacterTalentsClient<runtime.Types.Result.GetResult<Prisma.$CharacterTalentsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CharacterTalents.
   * @param {CharacterTalentsDeleteManyArgs} args - Arguments to filter CharacterTalents to delete.
   * @example
   * // Delete a few CharacterTalents
   * const { count } = await prisma.characterTalents.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CharacterTalentsDeleteManyArgs>(args?: Prisma.SelectSubset<T, CharacterTalentsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CharacterTalents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CharacterTalentsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CharacterTalents
   * const characterTalents = await prisma.characterTalents.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CharacterTalentsUpdateManyArgs>(args: Prisma.SelectSubset<T, CharacterTalentsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CharacterTalents and returns the data updated in the database.
   * @param {CharacterTalentsUpdateManyAndReturnArgs} args - Arguments to update many CharacterTalents.
   * @example
   * // Update many CharacterTalents
   * const characterTalents = await prisma.characterTalents.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CharacterTalents and only return the `id`
   * const characterTalentsWithIdOnly = await prisma.characterTalents.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CharacterTalentsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CharacterTalentsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CharacterTalentsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CharacterTalents.
   * @param {CharacterTalentsUpsertArgs} args - Arguments to update or create a CharacterTalents.
   * @example
   * // Update or create a CharacterTalents
   * const characterTalents = await prisma.characterTalents.upsert({
   *   create: {
   *     // ... data to create a CharacterTalents
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CharacterTalents we want to update
   *   }
   * })
   */
  upsert<T extends CharacterTalentsUpsertArgs>(args: Prisma.SelectSubset<T, CharacterTalentsUpsertArgs<ExtArgs>>): Prisma.Prisma__CharacterTalentsClient<runtime.Types.Result.GetResult<Prisma.$CharacterTalentsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CharacterTalents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CharacterTalentsCountArgs} args - Arguments to filter CharacterTalents to count.
   * @example
   * // Count the number of CharacterTalents
   * const count = await prisma.characterTalents.count({
   *   where: {
   *     // ... the filter for the CharacterTalents we want to count
   *   }
   * })
  **/
  count<T extends CharacterTalentsCountArgs>(
    args?: Prisma.Subset<T, CharacterTalentsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CharacterTalentsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CharacterTalents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CharacterTalentsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CharacterTalentsAggregateArgs>(args: Prisma.Subset<T, CharacterTalentsAggregateArgs>): Prisma.PrismaPromise<GetCharacterTalentsAggregateType<T>>

  /**
   * Group by CharacterTalents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CharacterTalentsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CharacterTalentsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CharacterTalentsGroupByArgs['orderBy'] }
      : { orderBy?: CharacterTalentsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CharacterTalentsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCharacterTalentsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CharacterTalents model
 */
readonly fields: CharacterTalentsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CharacterTalents.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CharacterTalentsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  character<T extends Prisma.CharacterDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CharacterDefaultArgs<ExtArgs>>): Prisma.Prisma__CharacterClient<runtime.Types.Result.GetResult<Prisma.$CharacterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CharacterTalents model
 */
export interface CharacterTalentsFieldRefs {
  readonly id: Prisma.FieldRef<"CharacterTalents", 'String'>
  readonly characterId: Prisma.FieldRef<"CharacterTalents", 'String'>
  readonly totalPoints: Prisma.FieldRef<"CharacterTalents", 'Int'>
  readonly pointsSpent: Prisma.FieldRef<"CharacterTalents", 'Int'>
  readonly pointsRemaining: Prisma.FieldRef<"CharacterTalents", 'Int'>
  readonly finalized: Prisma.FieldRef<"CharacterTalents", 'Boolean'>
  readonly totalTalents: Prisma.FieldRef<"CharacterTalents", 'String'>
  readonly pendingTalents: Prisma.FieldRef<"CharacterTalents", 'String'>
  readonly pendingTrees: Prisma.FieldRef<"CharacterTalents", 'String'>
}
    

// Custom InputTypes
/**
 * CharacterTalents findUnique
 */
export type CharacterTalentsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterTalents
   */
  select?: Prisma.CharacterTalentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterTalents
   */
  omit?: Prisma.CharacterTalentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterTalentsInclude<ExtArgs> | null
  /**
   * Filter, which CharacterTalents to fetch.
   */
  where: Prisma.CharacterTalentsWhereUniqueInput
}

/**
 * CharacterTalents findUniqueOrThrow
 */
export type CharacterTalentsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterTalents
   */
  select?: Prisma.CharacterTalentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterTalents
   */
  omit?: Prisma.CharacterTalentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterTalentsInclude<ExtArgs> | null
  /**
   * Filter, which CharacterTalents to fetch.
   */
  where: Prisma.CharacterTalentsWhereUniqueInput
}

/**
 * CharacterTalents findFirst
 */
export type CharacterTalentsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterTalents
   */
  select?: Prisma.CharacterTalentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterTalents
   */
  omit?: Prisma.CharacterTalentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterTalentsInclude<ExtArgs> | null
  /**
   * Filter, which CharacterTalents to fetch.
   */
  where?: Prisma.CharacterTalentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CharacterTalents to fetch.
   */
  orderBy?: Prisma.CharacterTalentsOrderByWithRelationInput | Prisma.CharacterTalentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CharacterTalents.
   */
  cursor?: Prisma.CharacterTalentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CharacterTalents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CharacterTalents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CharacterTalents.
   */
  distinct?: Prisma.CharacterTalentsScalarFieldEnum | Prisma.CharacterTalentsScalarFieldEnum[]
}

/**
 * CharacterTalents findFirstOrThrow
 */
export type CharacterTalentsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterTalents
   */
  select?: Prisma.CharacterTalentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterTalents
   */
  omit?: Prisma.CharacterTalentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterTalentsInclude<ExtArgs> | null
  /**
   * Filter, which CharacterTalents to fetch.
   */
  where?: Prisma.CharacterTalentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CharacterTalents to fetch.
   */
  orderBy?: Prisma.CharacterTalentsOrderByWithRelationInput | Prisma.CharacterTalentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CharacterTalents.
   */
  cursor?: Prisma.CharacterTalentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CharacterTalents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CharacterTalents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CharacterTalents.
   */
  distinct?: Prisma.CharacterTalentsScalarFieldEnum | Prisma.CharacterTalentsScalarFieldEnum[]
}

/**
 * CharacterTalents findMany
 */
export type CharacterTalentsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterTalents
   */
  select?: Prisma.CharacterTalentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterTalents
   */
  omit?: Prisma.CharacterTalentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterTalentsInclude<ExtArgs> | null
  /**
   * Filter, which CharacterTalents to fetch.
   */
  where?: Prisma.CharacterTalentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CharacterTalents to fetch.
   */
  orderBy?: Prisma.CharacterTalentsOrderByWithRelationInput | Prisma.CharacterTalentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CharacterTalents.
   */
  cursor?: Prisma.CharacterTalentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CharacterTalents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CharacterTalents.
   */
  skip?: number
  distinct?: Prisma.CharacterTalentsScalarFieldEnum | Prisma.CharacterTalentsScalarFieldEnum[]
}

/**
 * CharacterTalents create
 */
export type CharacterTalentsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterTalents
   */
  select?: Prisma.CharacterTalentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterTalents
   */
  omit?: Prisma.CharacterTalentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterTalentsInclude<ExtArgs> | null
  /**
   * The data needed to create a CharacterTalents.
   */
  data: Prisma.XOR<Prisma.CharacterTalentsCreateInput, Prisma.CharacterTalentsUncheckedCreateInput>
}

/**
 * CharacterTalents createMany
 */
export type CharacterTalentsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CharacterTalents.
   */
  data: Prisma.CharacterTalentsCreateManyInput | Prisma.CharacterTalentsCreateManyInput[]
}

/**
 * CharacterTalents createManyAndReturn
 */
export type CharacterTalentsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterTalents
   */
  select?: Prisma.CharacterTalentsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterTalents
   */
  omit?: Prisma.CharacterTalentsOmit<ExtArgs> | null
  /**
   * The data used to create many CharacterTalents.
   */
  data: Prisma.CharacterTalentsCreateManyInput | Prisma.CharacterTalentsCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterTalentsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CharacterTalents update
 */
export type CharacterTalentsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterTalents
   */
  select?: Prisma.CharacterTalentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterTalents
   */
  omit?: Prisma.CharacterTalentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterTalentsInclude<ExtArgs> | null
  /**
   * The data needed to update a CharacterTalents.
   */
  data: Prisma.XOR<Prisma.CharacterTalentsUpdateInput, Prisma.CharacterTalentsUncheckedUpdateInput>
  /**
   * Choose, which CharacterTalents to update.
   */
  where: Prisma.CharacterTalentsWhereUniqueInput
}

/**
 * CharacterTalents updateMany
 */
export type CharacterTalentsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CharacterTalents.
   */
  data: Prisma.XOR<Prisma.CharacterTalentsUpdateManyMutationInput, Prisma.CharacterTalentsUncheckedUpdateManyInput>
  /**
   * Filter which CharacterTalents to update
   */
  where?: Prisma.CharacterTalentsWhereInput
  /**
   * Limit how many CharacterTalents to update.
   */
  limit?: number
}

/**
 * CharacterTalents updateManyAndReturn
 */
export type CharacterTalentsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterTalents
   */
  select?: Prisma.CharacterTalentsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterTalents
   */
  omit?: Prisma.CharacterTalentsOmit<ExtArgs> | null
  /**
   * The data used to update CharacterTalents.
   */
  data: Prisma.XOR<Prisma.CharacterTalentsUpdateManyMutationInput, Prisma.CharacterTalentsUncheckedUpdateManyInput>
  /**
   * Filter which CharacterTalents to update
   */
  where?: Prisma.CharacterTalentsWhereInput
  /**
   * Limit how many CharacterTalents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterTalentsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CharacterTalents upsert
 */
export type CharacterTalentsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterTalents
   */
  select?: Prisma.CharacterTalentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterTalents
   */
  omit?: Prisma.CharacterTalentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterTalentsInclude<ExtArgs> | null
  /**
   * The filter to search for the CharacterTalents to update in case it exists.
   */
  where: Prisma.CharacterTalentsWhereUniqueInput
  /**
   * In case the CharacterTalents found by the `where` argument doesn't exist, create a new CharacterTalents with this data.
   */
  create: Prisma.XOR<Prisma.CharacterTalentsCreateInput, Prisma.CharacterTalentsUncheckedCreateInput>
  /**
   * In case the CharacterTalents was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CharacterTalentsUpdateInput, Prisma.CharacterTalentsUncheckedUpdateInput>
}

/**
 * CharacterTalents delete
 */
export type CharacterTalentsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterTalents
   */
  select?: Prisma.CharacterTalentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterTalents
   */
  omit?: Prisma.CharacterTalentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterTalentsInclude<ExtArgs> | null
  /**
   * Filter which CharacterTalents to delete.
   */
  where: Prisma.CharacterTalentsWhereUniqueInput
}

/**
 * CharacterTalents deleteMany
 */
export type CharacterTalentsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CharacterTalents to delete
   */
  where?: Prisma.CharacterTalentsWhereInput
  /**
   * Limit how many CharacterTalents to delete.
   */
  limit?: number
}

/**
 * CharacterTalents without action
 */
export type CharacterTalentsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CharacterTalents
   */
  select?: Prisma.CharacterTalentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CharacterTalents
   */
  omit?: Prisma.CharacterTalentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CharacterTalentsInclude<ExtArgs> | null
}
