
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CultureSelection` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model CultureSelection
 * 
 */
export type CultureSelectionModel = runtime.Types.Result.DefaultSelection<Prisma.$CultureSelectionPayload>

export type AggregateCultureSelection = {
  _count: CultureSelectionCountAggregateOutputType | null
  _min: CultureSelectionMinAggregateOutputType | null
  _max: CultureSelectionMaxAggregateOutputType | null
}

export type CultureSelectionMinAggregateOutputType = {
  id: string | null
  characterId: string | null
  name: string | null
  description: string | null
  expertise: string | null
  suggestedNames: string | null
}

export type CultureSelectionMaxAggregateOutputType = {
  id: string | null
  characterId: string | null
  name: string | null
  description: string | null
  expertise: string | null
  suggestedNames: string | null
}

export type CultureSelectionCountAggregateOutputType = {
  id: number
  characterId: number
  name: number
  description: number
  expertise: number
  suggestedNames: number
  _all: number
}


export type CultureSelectionMinAggregateInputType = {
  id?: true
  characterId?: true
  name?: true
  description?: true
  expertise?: true
  suggestedNames?: true
}

export type CultureSelectionMaxAggregateInputType = {
  id?: true
  characterId?: true
  name?: true
  description?: true
  expertise?: true
  suggestedNames?: true
}

export type CultureSelectionCountAggregateInputType = {
  id?: true
  characterId?: true
  name?: true
  description?: true
  expertise?: true
  suggestedNames?: true
  _all?: true
}

export type CultureSelectionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CultureSelection to aggregate.
   */
  where?: Prisma.CultureSelectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CultureSelections to fetch.
   */
  orderBy?: Prisma.CultureSelectionOrderByWithRelationInput | Prisma.CultureSelectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CultureSelectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CultureSelections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CultureSelections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CultureSelections
  **/
  _count?: true | CultureSelectionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CultureSelectionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CultureSelectionMaxAggregateInputType
}

export type GetCultureSelectionAggregateType<T extends CultureSelectionAggregateArgs> = {
      [P in keyof T & keyof AggregateCultureSelection]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCultureSelection[P]>
    : Prisma.GetScalarType<T[P], AggregateCultureSelection[P]>
}




export type CultureSelectionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CultureSelectionWhereInput
  orderBy?: Prisma.CultureSelectionOrderByWithAggregationInput | Prisma.CultureSelectionOrderByWithAggregationInput[]
  by: Prisma.CultureSelectionScalarFieldEnum[] | Prisma.CultureSelectionScalarFieldEnum
  having?: Prisma.CultureSelectionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CultureSelectionCountAggregateInputType | true
  _min?: CultureSelectionMinAggregateInputType
  _max?: CultureSelectionMaxAggregateInputType
}

export type CultureSelectionGroupByOutputType = {
  id: string
  characterId: string
  name: string
  description: string
  expertise: string
  suggestedNames: string
  _count: CultureSelectionCountAggregateOutputType | null
  _min: CultureSelectionMinAggregateOutputType | null
  _max: CultureSelectionMaxAggregateOutputType | null
}

type GetCultureSelectionGroupByPayload<T extends CultureSelectionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CultureSelectionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CultureSelectionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CultureSelectionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CultureSelectionGroupByOutputType[P]>
      }
    >
  >



export type CultureSelectionWhereInput = {
  AND?: Prisma.CultureSelectionWhereInput | Prisma.CultureSelectionWhereInput[]
  OR?: Prisma.CultureSelectionWhereInput[]
  NOT?: Prisma.CultureSelectionWhereInput | Prisma.CultureSelectionWhereInput[]
  id?: Prisma.StringFilter<"CultureSelection"> | string
  characterId?: Prisma.StringFilter<"CultureSelection"> | string
  name?: Prisma.StringFilter<"CultureSelection"> | string
  description?: Prisma.StringFilter<"CultureSelection"> | string
  expertise?: Prisma.StringFilter<"CultureSelection"> | string
  suggestedNames?: Prisma.StringFilter<"CultureSelection"> | string
  character?: Prisma.XOR<Prisma.CharacterScalarRelationFilter, Prisma.CharacterWhereInput>
}

export type CultureSelectionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  expertise?: Prisma.SortOrder
  suggestedNames?: Prisma.SortOrder
  character?: Prisma.CharacterOrderByWithRelationInput
}

export type CultureSelectionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  characterId_name?: Prisma.CultureSelectionCharacterIdNameCompoundUniqueInput
  AND?: Prisma.CultureSelectionWhereInput | Prisma.CultureSelectionWhereInput[]
  OR?: Prisma.CultureSelectionWhereInput[]
  NOT?: Prisma.CultureSelectionWhereInput | Prisma.CultureSelectionWhereInput[]
  characterId?: Prisma.StringFilter<"CultureSelection"> | string
  name?: Prisma.StringFilter<"CultureSelection"> | string
  description?: Prisma.StringFilter<"CultureSelection"> | string
  expertise?: Prisma.StringFilter<"CultureSelection"> | string
  suggestedNames?: Prisma.StringFilter<"CultureSelection"> | string
  character?: Prisma.XOR<Prisma.CharacterScalarRelationFilter, Prisma.CharacterWhereInput>
}, "id" | "characterId_name">

export type CultureSelectionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  expertise?: Prisma.SortOrder
  suggestedNames?: Prisma.SortOrder
  _count?: Prisma.CultureSelectionCountOrderByAggregateInput
  _max?: Prisma.CultureSelectionMaxOrderByAggregateInput
  _min?: Prisma.CultureSelectionMinOrderByAggregateInput
}

export type CultureSelectionScalarWhereWithAggregatesInput = {
  AND?: Prisma.CultureSelectionScalarWhereWithAggregatesInput | Prisma.CultureSelectionScalarWhereWithAggregatesInput[]
  OR?: Prisma.CultureSelectionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CultureSelectionScalarWhereWithAggregatesInput | Prisma.CultureSelectionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CultureSelection"> | string
  characterId?: Prisma.StringWithAggregatesFilter<"CultureSelection"> | string
  name?: Prisma.StringWithAggregatesFilter<"CultureSelection"> | string
  description?: Prisma.StringWithAggregatesFilter<"CultureSelection"> | string
  expertise?: Prisma.StringWithAggregatesFilter<"CultureSelection"> | string
  suggestedNames?: Prisma.StringWithAggregatesFilter<"CultureSelection"> | string
}

export type CultureSelectionCreateInput = {
  id?: string
  name: string
  description: string
  expertise: string
  suggestedNames: string
  character: Prisma.CharacterCreateNestedOneWithoutCulturesInput
}

export type CultureSelectionUncheckedCreateInput = {
  id?: string
  characterId: string
  name: string
  description: string
  expertise: string
  suggestedNames: string
}

export type CultureSelectionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  expertise?: Prisma.StringFieldUpdateOperationsInput | string
  suggestedNames?: Prisma.StringFieldUpdateOperationsInput | string
  character?: Prisma.CharacterUpdateOneRequiredWithoutCulturesNestedInput
}

export type CultureSelectionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  characterId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  expertise?: Prisma.StringFieldUpdateOperationsInput | string
  suggestedNames?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CultureSelectionCreateManyInput = {
  id?: string
  characterId: string
  name: string
  description: string
  expertise: string
  suggestedNames: string
}

export type CultureSelectionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  expertise?: Prisma.StringFieldUpdateOperationsInput | string
  suggestedNames?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CultureSelectionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  characterId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  expertise?: Prisma.StringFieldUpdateOperationsInput | string
  suggestedNames?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CultureSelectionListRelationFilter = {
  every?: Prisma.CultureSelectionWhereInput
  some?: Prisma.CultureSelectionWhereInput
  none?: Prisma.CultureSelectionWhereInput
}

export type CultureSelectionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CultureSelectionCharacterIdNameCompoundUniqueInput = {
  characterId: string
  name: string
}

export type CultureSelectionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  expertise?: Prisma.SortOrder
  suggestedNames?: Prisma.SortOrder
}

export type CultureSelectionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  expertise?: Prisma.SortOrder
  suggestedNames?: Prisma.SortOrder
}

export type CultureSelectionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  expertise?: Prisma.SortOrder
  suggestedNames?: Prisma.SortOrder
}

export type CultureSelectionCreateNestedManyWithoutCharacterInput = {
  create?: Prisma.XOR<Prisma.CultureSelectionCreateWithoutCharacterInput, Prisma.CultureSelectionUncheckedCreateWithoutCharacterInput> | Prisma.CultureSelectionCreateWithoutCharacterInput[] | Prisma.CultureSelectionUncheckedCreateWithoutCharacterInput[]
  connectOrCreate?: Prisma.CultureSelectionCreateOrConnectWithoutCharacterInput | Prisma.CultureSelectionCreateOrConnectWithoutCharacterInput[]
  createMany?: Prisma.CultureSelectionCreateManyCharacterInputEnvelope
  connect?: Prisma.CultureSelectionWhereUniqueInput | Prisma.CultureSelectionWhereUniqueInput[]
}

export type CultureSelectionUncheckedCreateNestedManyWithoutCharacterInput = {
  create?: Prisma.XOR<Prisma.CultureSelectionCreateWithoutCharacterInput, Prisma.CultureSelectionUncheckedCreateWithoutCharacterInput> | Prisma.CultureSelectionCreateWithoutCharacterInput[] | Prisma.CultureSelectionUncheckedCreateWithoutCharacterInput[]
  connectOrCreate?: Prisma.CultureSelectionCreateOrConnectWithoutCharacterInput | Prisma.CultureSelectionCreateOrConnectWithoutCharacterInput[]
  createMany?: Prisma.CultureSelectionCreateManyCharacterInputEnvelope
  connect?: Prisma.CultureSelectionWhereUniqueInput | Prisma.CultureSelectionWhereUniqueInput[]
}

export type CultureSelectionUpdateManyWithoutCharacterNestedInput = {
  create?: Prisma.XOR<Prisma.CultureSelectionCreateWithoutCharacterInput, Prisma.CultureSelectionUncheckedCreateWithoutCharacterInput> | Prisma.CultureSelectionCreateWithoutCharacterInput[] | Prisma.CultureSelectionUncheckedCreateWithoutCharacterInput[]
  connectOrCreate?: Prisma.CultureSelectionCreateOrConnectWithoutCharacterInput | Prisma.CultureSelectionCreateOrConnectWithoutCharacterInput[]
  upsert?: Prisma.CultureSelectionUpsertWithWhereUniqueWithoutCharacterInput | Prisma.CultureSelectionUpsertWithWhereUniqueWithoutCharacterInput[]
  createMany?: Prisma.CultureSelectionCreateManyCharacterInputEnvelope
  set?: Prisma.CultureSelectionWhereUniqueInput | Prisma.CultureSelectionWhereUniqueInput[]
  disconnect?: Prisma.CultureSelectionWhereUniqueInput | Prisma.CultureSelectionWhereUniqueInput[]
  delete?: Prisma.CultureSelectionWhereUniqueInput | Prisma.CultureSelectionWhereUniqueInput[]
  connect?: Prisma.CultureSelectionWhereUniqueInput | Prisma.CultureSelectionWhereUniqueInput[]
  update?: Prisma.CultureSelectionUpdateWithWhereUniqueWithoutCharacterInput | Prisma.CultureSelectionUpdateWithWhereUniqueWithoutCharacterInput[]
  updateMany?: Prisma.CultureSelectionUpdateManyWithWhereWithoutCharacterInput | Prisma.CultureSelectionUpdateManyWithWhereWithoutCharacterInput[]
  deleteMany?: Prisma.CultureSelectionScalarWhereInput | Prisma.CultureSelectionScalarWhereInput[]
}

export type CultureSelectionUncheckedUpdateManyWithoutCharacterNestedInput = {
  create?: Prisma.XOR<Prisma.CultureSelectionCreateWithoutCharacterInput, Prisma.CultureSelectionUncheckedCreateWithoutCharacterInput> | Prisma.CultureSelectionCreateWithoutCharacterInput[] | Prisma.CultureSelectionUncheckedCreateWithoutCharacterInput[]
  connectOrCreate?: Prisma.CultureSelectionCreateOrConnectWithoutCharacterInput | Prisma.CultureSelectionCreateOrConnectWithoutCharacterInput[]
  upsert?: Prisma.CultureSelectionUpsertWithWhereUniqueWithoutCharacterInput | Prisma.CultureSelectionUpsertWithWhereUniqueWithoutCharacterInput[]
  createMany?: Prisma.CultureSelectionCreateManyCharacterInputEnvelope
  set?: Prisma.CultureSelectionWhereUniqueInput | Prisma.CultureSelectionWhereUniqueInput[]
  disconnect?: Prisma.CultureSelectionWhereUniqueInput | Prisma.CultureSelectionWhereUniqueInput[]
  delete?: Prisma.CultureSelectionWhereUniqueInput | Prisma.CultureSelectionWhereUniqueInput[]
  connect?: Prisma.CultureSelectionWhereUniqueInput | Prisma.CultureSelectionWhereUniqueInput[]
  update?: Prisma.CultureSelectionUpdateWithWhereUniqueWithoutCharacterInput | Prisma.CultureSelectionUpdateWithWhereUniqueWithoutCharacterInput[]
  updateMany?: Prisma.CultureSelectionUpdateManyWithWhereWithoutCharacterInput | Prisma.CultureSelectionUpdateManyWithWhereWithoutCharacterInput[]
  deleteMany?: Prisma.CultureSelectionScalarWhereInput | Prisma.CultureSelectionScalarWhereInput[]
}

export type CultureSelectionCreateWithoutCharacterInput = {
  id?: string
  name: string
  description: string
  expertise: string
  suggestedNames: string
}

export type CultureSelectionUncheckedCreateWithoutCharacterInput = {
  id?: string
  name: string
  description: string
  expertise: string
  suggestedNames: string
}

export type CultureSelectionCreateOrConnectWithoutCharacterInput = {
  where: Prisma.CultureSelectionWhereUniqueInput
  create: Prisma.XOR<Prisma.CultureSelectionCreateWithoutCharacterInput, Prisma.CultureSelectionUncheckedCreateWithoutCharacterInput>
}

export type CultureSelectionCreateManyCharacterInputEnvelope = {
  data: Prisma.CultureSelectionCreateManyCharacterInput | Prisma.CultureSelectionCreateManyCharacterInput[]
}

export type CultureSelectionUpsertWithWhereUniqueWithoutCharacterInput = {
  where: Prisma.CultureSelectionWhereUniqueInput
  update: Prisma.XOR<Prisma.CultureSelectionUpdateWithoutCharacterInput, Prisma.CultureSelectionUncheckedUpdateWithoutCharacterInput>
  create: Prisma.XOR<Prisma.CultureSelectionCreateWithoutCharacterInput, Prisma.CultureSelectionUncheckedCreateWithoutCharacterInput>
}

export type CultureSelectionUpdateWithWhereUniqueWithoutCharacterInput = {
  where: Prisma.CultureSelectionWhereUniqueInput
  data: Prisma.XOR<Prisma.CultureSelectionUpdateWithoutCharacterInput, Prisma.CultureSelectionUncheckedUpdateWithoutCharacterInput>
}

export type CultureSelectionUpdateManyWithWhereWithoutCharacterInput = {
  where: Prisma.CultureSelectionScalarWhereInput
  data: Prisma.XOR<Prisma.CultureSelectionUpdateManyMutationInput, Prisma.CultureSelectionUncheckedUpdateManyWithoutCharacterInput>
}

export type CultureSelectionScalarWhereInput = {
  AND?: Prisma.CultureSelectionScalarWhereInput | Prisma.CultureSelectionScalarWhereInput[]
  OR?: Prisma.CultureSelectionScalarWhereInput[]
  NOT?: Prisma.CultureSelectionScalarWhereInput | Prisma.CultureSelectionScalarWhereInput[]
  id?: Prisma.StringFilter<"CultureSelection"> | string
  characterId?: Prisma.StringFilter<"CultureSelection"> | string
  name?: Prisma.StringFilter<"CultureSelection"> | string
  description?: Prisma.StringFilter<"CultureSelection"> | string
  expertise?: Prisma.StringFilter<"CultureSelection"> | string
  suggestedNames?: Prisma.StringFilter<"CultureSelection"> | string
}

export type CultureSelectionCreateManyCharacterInput = {
  id?: string
  name: string
  description: string
  expertise: string
  suggestedNames: string
}

export type CultureSelectionUpdateWithoutCharacterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  expertise?: Prisma.StringFieldUpdateOperationsInput | string
  suggestedNames?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CultureSelectionUncheckedUpdateWithoutCharacterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  expertise?: Prisma.StringFieldUpdateOperationsInput | string
  suggestedNames?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CultureSelectionUncheckedUpdateManyWithoutCharacterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  expertise?: Prisma.StringFieldUpdateOperationsInput | string
  suggestedNames?: Prisma.StringFieldUpdateOperationsInput | string
}



export type CultureSelectionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  characterId?: boolean
  name?: boolean
  description?: boolean
  expertise?: boolean
  suggestedNames?: boolean
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["cultureSelection"]>

export type CultureSelectionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  characterId?: boolean
  name?: boolean
  description?: boolean
  expertise?: boolean
  suggestedNames?: boolean
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["cultureSelection"]>

export type CultureSelectionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  characterId?: boolean
  name?: boolean
  description?: boolean
  expertise?: boolean
  suggestedNames?: boolean
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["cultureSelection"]>

export type CultureSelectionSelectScalar = {
  id?: boolean
  characterId?: boolean
  name?: boolean
  description?: boolean
  expertise?: boolean
  suggestedNames?: boolean
}

export type CultureSelectionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "characterId" | "name" | "description" | "expertise" | "suggestedNames", ExtArgs["result"]["cultureSelection"]>
export type CultureSelectionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}
export type CultureSelectionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}
export type CultureSelectionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}

export type $CultureSelectionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CultureSelection"
  objects: {
    character: Prisma.$CharacterPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    characterId: string
    name: string
    description: string
    expertise: string
    suggestedNames: string
  }, ExtArgs["result"]["cultureSelection"]>
  composites: {}
}

export type CultureSelectionGetPayload<S extends boolean | null | undefined | CultureSelectionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CultureSelectionPayload, S>

export type CultureSelectionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CultureSelectionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CultureSelectionCountAggregateInputType | true
  }

export interface CultureSelectionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CultureSelection'], meta: { name: 'CultureSelection' } }
  /**
   * Find zero or one CultureSelection that matches the filter.
   * @param {CultureSelectionFindUniqueArgs} args - Arguments to find a CultureSelection
   * @example
   * // Get one CultureSelection
   * const cultureSelection = await prisma.cultureSelection.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CultureSelectionFindUniqueArgs>(args: Prisma.SelectSubset<T, CultureSelectionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CultureSelectionClient<runtime.Types.Result.GetResult<Prisma.$CultureSelectionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CultureSelection that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CultureSelectionFindUniqueOrThrowArgs} args - Arguments to find a CultureSelection
   * @example
   * // Get one CultureSelection
   * const cultureSelection = await prisma.cultureSelection.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CultureSelectionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CultureSelectionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CultureSelectionClient<runtime.Types.Result.GetResult<Prisma.$CultureSelectionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CultureSelection that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CultureSelectionFindFirstArgs} args - Arguments to find a CultureSelection
   * @example
   * // Get one CultureSelection
   * const cultureSelection = await prisma.cultureSelection.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CultureSelectionFindFirstArgs>(args?: Prisma.SelectSubset<T, CultureSelectionFindFirstArgs<ExtArgs>>): Prisma.Prisma__CultureSelectionClient<runtime.Types.Result.GetResult<Prisma.$CultureSelectionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CultureSelection that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CultureSelectionFindFirstOrThrowArgs} args - Arguments to find a CultureSelection
   * @example
   * // Get one CultureSelection
   * const cultureSelection = await prisma.cultureSelection.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CultureSelectionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CultureSelectionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CultureSelectionClient<runtime.Types.Result.GetResult<Prisma.$CultureSelectionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CultureSelections that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CultureSelectionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CultureSelections
   * const cultureSelections = await prisma.cultureSelection.findMany()
   * 
   * // Get first 10 CultureSelections
   * const cultureSelections = await prisma.cultureSelection.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const cultureSelectionWithIdOnly = await prisma.cultureSelection.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CultureSelectionFindManyArgs>(args?: Prisma.SelectSubset<T, CultureSelectionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CultureSelectionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CultureSelection.
   * @param {CultureSelectionCreateArgs} args - Arguments to create a CultureSelection.
   * @example
   * // Create one CultureSelection
   * const CultureSelection = await prisma.cultureSelection.create({
   *   data: {
   *     // ... data to create a CultureSelection
   *   }
   * })
   * 
   */
  create<T extends CultureSelectionCreateArgs>(args: Prisma.SelectSubset<T, CultureSelectionCreateArgs<ExtArgs>>): Prisma.Prisma__CultureSelectionClient<runtime.Types.Result.GetResult<Prisma.$CultureSelectionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CultureSelections.
   * @param {CultureSelectionCreateManyArgs} args - Arguments to create many CultureSelections.
   * @example
   * // Create many CultureSelections
   * const cultureSelection = await prisma.cultureSelection.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CultureSelectionCreateManyArgs>(args?: Prisma.SelectSubset<T, CultureSelectionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CultureSelections and returns the data saved in the database.
   * @param {CultureSelectionCreateManyAndReturnArgs} args - Arguments to create many CultureSelections.
   * @example
   * // Create many CultureSelections
   * const cultureSelection = await prisma.cultureSelection.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CultureSelections and only return the `id`
   * const cultureSelectionWithIdOnly = await prisma.cultureSelection.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CultureSelectionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CultureSelectionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CultureSelectionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CultureSelection.
   * @param {CultureSelectionDeleteArgs} args - Arguments to delete one CultureSelection.
   * @example
   * // Delete one CultureSelection
   * const CultureSelection = await prisma.cultureSelection.delete({
   *   where: {
   *     // ... filter to delete one CultureSelection
   *   }
   * })
   * 
   */
  delete<T extends CultureSelectionDeleteArgs>(args: Prisma.SelectSubset<T, CultureSelectionDeleteArgs<ExtArgs>>): Prisma.Prisma__CultureSelectionClient<runtime.Types.Result.GetResult<Prisma.$CultureSelectionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CultureSelection.
   * @param {CultureSelectionUpdateArgs} args - Arguments to update one CultureSelection.
   * @example
   * // Update one CultureSelection
   * const cultureSelection = await prisma.cultureSelection.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CultureSelectionUpdateArgs>(args: Prisma.SelectSubset<T, CultureSelectionUpdateArgs<ExtArgs>>): Prisma.Prisma__CultureSelectionClient<runtime.Types.Result.GetResult<Prisma.$CultureSelectionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CultureSelections.
   * @param {CultureSelectionDeleteManyArgs} args - Arguments to filter CultureSelections to delete.
   * @example
   * // Delete a few CultureSelections
   * const { count } = await prisma.cultureSelection.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CultureSelectionDeleteManyArgs>(args?: Prisma.SelectSubset<T, CultureSelectionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CultureSelections.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CultureSelectionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CultureSelections
   * const cultureSelection = await prisma.cultureSelection.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CultureSelectionUpdateManyArgs>(args: Prisma.SelectSubset<T, CultureSelectionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CultureSelections and returns the data updated in the database.
   * @param {CultureSelectionUpdateManyAndReturnArgs} args - Arguments to update many CultureSelections.
   * @example
   * // Update many CultureSelections
   * const cultureSelection = await prisma.cultureSelection.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CultureSelections and only return the `id`
   * const cultureSelectionWithIdOnly = await prisma.cultureSelection.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CultureSelectionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CultureSelectionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CultureSelectionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CultureSelection.
   * @param {CultureSelectionUpsertArgs} args - Arguments to update or create a CultureSelection.
   * @example
   * // Update or create a CultureSelection
   * const cultureSelection = await prisma.cultureSelection.upsert({
   *   create: {
   *     // ... data to create a CultureSelection
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CultureSelection we want to update
   *   }
   * })
   */
  upsert<T extends CultureSelectionUpsertArgs>(args: Prisma.SelectSubset<T, CultureSelectionUpsertArgs<ExtArgs>>): Prisma.Prisma__CultureSelectionClient<runtime.Types.Result.GetResult<Prisma.$CultureSelectionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CultureSelections.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CultureSelectionCountArgs} args - Arguments to filter CultureSelections to count.
   * @example
   * // Count the number of CultureSelections
   * const count = await prisma.cultureSelection.count({
   *   where: {
   *     // ... the filter for the CultureSelections we want to count
   *   }
   * })
  **/
  count<T extends CultureSelectionCountArgs>(
    args?: Prisma.Subset<T, CultureSelectionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CultureSelectionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CultureSelection.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CultureSelectionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CultureSelectionAggregateArgs>(args: Prisma.Subset<T, CultureSelectionAggregateArgs>): Prisma.PrismaPromise<GetCultureSelectionAggregateType<T>>

  /**
   * Group by CultureSelection.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CultureSelectionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CultureSelectionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CultureSelectionGroupByArgs['orderBy'] }
      : { orderBy?: CultureSelectionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CultureSelectionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCultureSelectionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CultureSelection model
 */
readonly fields: CultureSelectionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CultureSelection.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CultureSelectionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  character<T extends Prisma.CharacterDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CharacterDefaultArgs<ExtArgs>>): Prisma.Prisma__CharacterClient<runtime.Types.Result.GetResult<Prisma.$CharacterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CultureSelection model
 */
export interface CultureSelectionFieldRefs {
  readonly id: Prisma.FieldRef<"CultureSelection", 'String'>
  readonly characterId: Prisma.FieldRef<"CultureSelection", 'String'>
  readonly name: Prisma.FieldRef<"CultureSelection", 'String'>
  readonly description: Prisma.FieldRef<"CultureSelection", 'String'>
  readonly expertise: Prisma.FieldRef<"CultureSelection", 'String'>
  readonly suggestedNames: Prisma.FieldRef<"CultureSelection", 'String'>
}
    

// Custom InputTypes
/**
 * CultureSelection findUnique
 */
export type CultureSelectionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CultureSelection
   */
  select?: Prisma.CultureSelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CultureSelection
   */
  omit?: Prisma.CultureSelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CultureSelectionInclude<ExtArgs> | null
  /**
   * Filter, which CultureSelection to fetch.
   */
  where: Prisma.CultureSelectionWhereUniqueInput
}

/**
 * CultureSelection findUniqueOrThrow
 */
export type CultureSelectionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CultureSelection
   */
  select?: Prisma.CultureSelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CultureSelection
   */
  omit?: Prisma.CultureSelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CultureSelectionInclude<ExtArgs> | null
  /**
   * Filter, which CultureSelection to fetch.
   */
  where: Prisma.CultureSelectionWhereUniqueInput
}

/**
 * CultureSelection findFirst
 */
export type CultureSelectionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CultureSelection
   */
  select?: Prisma.CultureSelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CultureSelection
   */
  omit?: Prisma.CultureSelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CultureSelectionInclude<ExtArgs> | null
  /**
   * Filter, which CultureSelection to fetch.
   */
  where?: Prisma.CultureSelectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CultureSelections to fetch.
   */
  orderBy?: Prisma.CultureSelectionOrderByWithRelationInput | Prisma.CultureSelectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CultureSelections.
   */
  cursor?: Prisma.CultureSelectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CultureSelections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CultureSelections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CultureSelections.
   */
  distinct?: Prisma.CultureSelectionScalarFieldEnum | Prisma.CultureSelectionScalarFieldEnum[]
}

/**
 * CultureSelection findFirstOrThrow
 */
export type CultureSelectionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CultureSelection
   */
  select?: Prisma.CultureSelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CultureSelection
   */
  omit?: Prisma.CultureSelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CultureSelectionInclude<ExtArgs> | null
  /**
   * Filter, which CultureSelection to fetch.
   */
  where?: Prisma.CultureSelectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CultureSelections to fetch.
   */
  orderBy?: Prisma.CultureSelectionOrderByWithRelationInput | Prisma.CultureSelectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CultureSelections.
   */
  cursor?: Prisma.CultureSelectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CultureSelections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CultureSelections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CultureSelections.
   */
  distinct?: Prisma.CultureSelectionScalarFieldEnum | Prisma.CultureSelectionScalarFieldEnum[]
}

/**
 * CultureSelection findMany
 */
export type CultureSelectionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CultureSelection
   */
  select?: Prisma.CultureSelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CultureSelection
   */
  omit?: Prisma.CultureSelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CultureSelectionInclude<ExtArgs> | null
  /**
   * Filter, which CultureSelections to fetch.
   */
  where?: Prisma.CultureSelectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CultureSelections to fetch.
   */
  orderBy?: Prisma.CultureSelectionOrderByWithRelationInput | Prisma.CultureSelectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CultureSelections.
   */
  cursor?: Prisma.CultureSelectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CultureSelections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CultureSelections.
   */
  skip?: number
  distinct?: Prisma.CultureSelectionScalarFieldEnum | Prisma.CultureSelectionScalarFieldEnum[]
}

/**
 * CultureSelection create
 */
export type CultureSelectionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CultureSelection
   */
  select?: Prisma.CultureSelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CultureSelection
   */
  omit?: Prisma.CultureSelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CultureSelectionInclude<ExtArgs> | null
  /**
   * The data needed to create a CultureSelection.
   */
  data: Prisma.XOR<Prisma.CultureSelectionCreateInput, Prisma.CultureSelectionUncheckedCreateInput>
}

/**
 * CultureSelection createMany
 */
export type CultureSelectionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CultureSelections.
   */
  data: Prisma.CultureSelectionCreateManyInput | Prisma.CultureSelectionCreateManyInput[]
}

/**
 * CultureSelection createManyAndReturn
 */
export type CultureSelectionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CultureSelection
   */
  select?: Prisma.CultureSelectionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CultureSelection
   */
  omit?: Prisma.CultureSelectionOmit<ExtArgs> | null
  /**
   * The data used to create many CultureSelections.
   */
  data: Prisma.CultureSelectionCreateManyInput | Prisma.CultureSelectionCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CultureSelectionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CultureSelection update
 */
export type CultureSelectionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CultureSelection
   */
  select?: Prisma.CultureSelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CultureSelection
   */
  omit?: Prisma.CultureSelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CultureSelectionInclude<ExtArgs> | null
  /**
   * The data needed to update a CultureSelection.
   */
  data: Prisma.XOR<Prisma.CultureSelectionUpdateInput, Prisma.CultureSelectionUncheckedUpdateInput>
  /**
   * Choose, which CultureSelection to update.
   */
  where: Prisma.CultureSelectionWhereUniqueInput
}

/**
 * CultureSelection updateMany
 */
export type CultureSelectionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CultureSelections.
   */
  data: Prisma.XOR<Prisma.CultureSelectionUpdateManyMutationInput, Prisma.CultureSelectionUncheckedUpdateManyInput>
  /**
   * Filter which CultureSelections to update
   */
  where?: Prisma.CultureSelectionWhereInput
  /**
   * Limit how many CultureSelections to update.
   */
  limit?: number
}

/**
 * CultureSelection updateManyAndReturn
 */
export type CultureSelectionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CultureSelection
   */
  select?: Prisma.CultureSelectionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CultureSelection
   */
  omit?: Prisma.CultureSelectionOmit<ExtArgs> | null
  /**
   * The data used to update CultureSelections.
   */
  data: Prisma.XOR<Prisma.CultureSelectionUpdateManyMutationInput, Prisma.CultureSelectionUncheckedUpdateManyInput>
  /**
   * Filter which CultureSelections to update
   */
  where?: Prisma.CultureSelectionWhereInput
  /**
   * Limit how many CultureSelections to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CultureSelectionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CultureSelection upsert
 */
export type CultureSelectionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CultureSelection
   */
  select?: Prisma.CultureSelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CultureSelection
   */
  omit?: Prisma.CultureSelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CultureSelectionInclude<ExtArgs> | null
  /**
   * The filter to search for the CultureSelection to update in case it exists.
   */
  where: Prisma.CultureSelectionWhereUniqueInput
  /**
   * In case the CultureSelection found by the `where` argument doesn't exist, create a new CultureSelection with this data.
   */
  create: Prisma.XOR<Prisma.CultureSelectionCreateInput, Prisma.CultureSelectionUncheckedCreateInput>
  /**
   * In case the CultureSelection was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CultureSelectionUpdateInput, Prisma.CultureSelectionUncheckedUpdateInput>
}

/**
 * CultureSelection delete
 */
export type CultureSelectionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CultureSelection
   */
  select?: Prisma.CultureSelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CultureSelection
   */
  omit?: Prisma.CultureSelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CultureSelectionInclude<ExtArgs> | null
  /**
   * Filter which CultureSelection to delete.
   */
  where: Prisma.CultureSelectionWhereUniqueInput
}

/**
 * CultureSelection deleteMany
 */
export type CultureSelectionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CultureSelections to delete
   */
  where?: Prisma.CultureSelectionWhereInput
  /**
   * Limit how many CultureSelections to delete.
   */
  limit?: number
}

/**
 * CultureSelection without action
 */
export type CultureSelectionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CultureSelection
   */
  select?: Prisma.CultureSelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CultureSelection
   */
  omit?: Prisma.CultureSelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CultureSelectionInclude<ExtArgs> | null
}
