
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PathSelection` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model PathSelection
 * 
 */
export type PathSelectionModel = runtime.Types.Result.DefaultSelection<Prisma.$PathSelectionPayload>

export type AggregatePathSelection = {
  _count: PathSelectionCountAggregateOutputType | null
  _min: PathSelectionMinAggregateOutputType | null
  _max: PathSelectionMaxAggregateOutputType | null
}

export type PathSelectionMinAggregateOutputType = {
  id: string | null
  characterId: string | null
  pathName: string | null
}

export type PathSelectionMaxAggregateOutputType = {
  id: string | null
  characterId: string | null
  pathName: string | null
}

export type PathSelectionCountAggregateOutputType = {
  id: number
  characterId: number
  pathName: number
  _all: number
}


export type PathSelectionMinAggregateInputType = {
  id?: true
  characterId?: true
  pathName?: true
}

export type PathSelectionMaxAggregateInputType = {
  id?: true
  characterId?: true
  pathName?: true
}

export type PathSelectionCountAggregateInputType = {
  id?: true
  characterId?: true
  pathName?: true
  _all?: true
}

export type PathSelectionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PathSelection to aggregate.
   */
  where?: Prisma.PathSelectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PathSelections to fetch.
   */
  orderBy?: Prisma.PathSelectionOrderByWithRelationInput | Prisma.PathSelectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PathSelectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PathSelections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PathSelections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PathSelections
  **/
  _count?: true | PathSelectionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PathSelectionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PathSelectionMaxAggregateInputType
}

export type GetPathSelectionAggregateType<T extends PathSelectionAggregateArgs> = {
      [P in keyof T & keyof AggregatePathSelection]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePathSelection[P]>
    : Prisma.GetScalarType<T[P], AggregatePathSelection[P]>
}




export type PathSelectionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PathSelectionWhereInput
  orderBy?: Prisma.PathSelectionOrderByWithAggregationInput | Prisma.PathSelectionOrderByWithAggregationInput[]
  by: Prisma.PathSelectionScalarFieldEnum[] | Prisma.PathSelectionScalarFieldEnum
  having?: Prisma.PathSelectionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PathSelectionCountAggregateInputType | true
  _min?: PathSelectionMinAggregateInputType
  _max?: PathSelectionMaxAggregateInputType
}

export type PathSelectionGroupByOutputType = {
  id: string
  characterId: string
  pathName: string
  _count: PathSelectionCountAggregateOutputType | null
  _min: PathSelectionMinAggregateOutputType | null
  _max: PathSelectionMaxAggregateOutputType | null
}

type GetPathSelectionGroupByPayload<T extends PathSelectionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PathSelectionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PathSelectionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PathSelectionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PathSelectionGroupByOutputType[P]>
      }
    >
  >



export type PathSelectionWhereInput = {
  AND?: Prisma.PathSelectionWhereInput | Prisma.PathSelectionWhereInput[]
  OR?: Prisma.PathSelectionWhereInput[]
  NOT?: Prisma.PathSelectionWhereInput | Prisma.PathSelectionWhereInput[]
  id?: Prisma.StringFilter<"PathSelection"> | string
  characterId?: Prisma.StringFilter<"PathSelection"> | string
  pathName?: Prisma.StringFilter<"PathSelection"> | string
  character?: Prisma.XOR<Prisma.CharacterScalarRelationFilter, Prisma.CharacterWhereInput>
}

export type PathSelectionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  pathName?: Prisma.SortOrder
  character?: Prisma.CharacterOrderByWithRelationInput
}

export type PathSelectionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  characterId_pathName?: Prisma.PathSelectionCharacterIdPathNameCompoundUniqueInput
  AND?: Prisma.PathSelectionWhereInput | Prisma.PathSelectionWhereInput[]
  OR?: Prisma.PathSelectionWhereInput[]
  NOT?: Prisma.PathSelectionWhereInput | Prisma.PathSelectionWhereInput[]
  characterId?: Prisma.StringFilter<"PathSelection"> | string
  pathName?: Prisma.StringFilter<"PathSelection"> | string
  character?: Prisma.XOR<Prisma.CharacterScalarRelationFilter, Prisma.CharacterWhereInput>
}, "id" | "characterId_pathName">

export type PathSelectionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  pathName?: Prisma.SortOrder
  _count?: Prisma.PathSelectionCountOrderByAggregateInput
  _max?: Prisma.PathSelectionMaxOrderByAggregateInput
  _min?: Prisma.PathSelectionMinOrderByAggregateInput
}

export type PathSelectionScalarWhereWithAggregatesInput = {
  AND?: Prisma.PathSelectionScalarWhereWithAggregatesInput | Prisma.PathSelectionScalarWhereWithAggregatesInput[]
  OR?: Prisma.PathSelectionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PathSelectionScalarWhereWithAggregatesInput | Prisma.PathSelectionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PathSelection"> | string
  characterId?: Prisma.StringWithAggregatesFilter<"PathSelection"> | string
  pathName?: Prisma.StringWithAggregatesFilter<"PathSelection"> | string
}

export type PathSelectionCreateInput = {
  id?: string
  pathName: string
  character: Prisma.CharacterCreateNestedOneWithoutPathsInput
}

export type PathSelectionUncheckedCreateInput = {
  id?: string
  characterId: string
  pathName: string
}

export type PathSelectionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pathName?: Prisma.StringFieldUpdateOperationsInput | string
  character?: Prisma.CharacterUpdateOneRequiredWithoutPathsNestedInput
}

export type PathSelectionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  characterId?: Prisma.StringFieldUpdateOperationsInput | string
  pathName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PathSelectionCreateManyInput = {
  id?: string
  characterId: string
  pathName: string
}

export type PathSelectionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pathName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PathSelectionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  characterId?: Prisma.StringFieldUpdateOperationsInput | string
  pathName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PathSelectionListRelationFilter = {
  every?: Prisma.PathSelectionWhereInput
  some?: Prisma.PathSelectionWhereInput
  none?: Prisma.PathSelectionWhereInput
}

export type PathSelectionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PathSelectionCharacterIdPathNameCompoundUniqueInput = {
  characterId: string
  pathName: string
}

export type PathSelectionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  pathName?: Prisma.SortOrder
}

export type PathSelectionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  pathName?: Prisma.SortOrder
}

export type PathSelectionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  pathName?: Prisma.SortOrder
}

export type PathSelectionCreateNestedManyWithoutCharacterInput = {
  create?: Prisma.XOR<Prisma.PathSelectionCreateWithoutCharacterInput, Prisma.PathSelectionUncheckedCreateWithoutCharacterInput> | Prisma.PathSelectionCreateWithoutCharacterInput[] | Prisma.PathSelectionUncheckedCreateWithoutCharacterInput[]
  connectOrCreate?: Prisma.PathSelectionCreateOrConnectWithoutCharacterInput | Prisma.PathSelectionCreateOrConnectWithoutCharacterInput[]
  createMany?: Prisma.PathSelectionCreateManyCharacterInputEnvelope
  connect?: Prisma.PathSelectionWhereUniqueInput | Prisma.PathSelectionWhereUniqueInput[]
}

export type PathSelectionUncheckedCreateNestedManyWithoutCharacterInput = {
  create?: Prisma.XOR<Prisma.PathSelectionCreateWithoutCharacterInput, Prisma.PathSelectionUncheckedCreateWithoutCharacterInput> | Prisma.PathSelectionCreateWithoutCharacterInput[] | Prisma.PathSelectionUncheckedCreateWithoutCharacterInput[]
  connectOrCreate?: Prisma.PathSelectionCreateOrConnectWithoutCharacterInput | Prisma.PathSelectionCreateOrConnectWithoutCharacterInput[]
  createMany?: Prisma.PathSelectionCreateManyCharacterInputEnvelope
  connect?: Prisma.PathSelectionWhereUniqueInput | Prisma.PathSelectionWhereUniqueInput[]
}

export type PathSelectionUpdateManyWithoutCharacterNestedInput = {
  create?: Prisma.XOR<Prisma.PathSelectionCreateWithoutCharacterInput, Prisma.PathSelectionUncheckedCreateWithoutCharacterInput> | Prisma.PathSelectionCreateWithoutCharacterInput[] | Prisma.PathSelectionUncheckedCreateWithoutCharacterInput[]
  connectOrCreate?: Prisma.PathSelectionCreateOrConnectWithoutCharacterInput | Prisma.PathSelectionCreateOrConnectWithoutCharacterInput[]
  upsert?: Prisma.PathSelectionUpsertWithWhereUniqueWithoutCharacterInput | Prisma.PathSelectionUpsertWithWhereUniqueWithoutCharacterInput[]
  createMany?: Prisma.PathSelectionCreateManyCharacterInputEnvelope
  set?: Prisma.PathSelectionWhereUniqueInput | Prisma.PathSelectionWhereUniqueInput[]
  disconnect?: Prisma.PathSelectionWhereUniqueInput | Prisma.PathSelectionWhereUniqueInput[]
  delete?: Prisma.PathSelectionWhereUniqueInput | Prisma.PathSelectionWhereUniqueInput[]
  connect?: Prisma.PathSelectionWhereUniqueInput | Prisma.PathSelectionWhereUniqueInput[]
  update?: Prisma.PathSelectionUpdateWithWhereUniqueWithoutCharacterInput | Prisma.PathSelectionUpdateWithWhereUniqueWithoutCharacterInput[]
  updateMany?: Prisma.PathSelectionUpdateManyWithWhereWithoutCharacterInput | Prisma.PathSelectionUpdateManyWithWhereWithoutCharacterInput[]
  deleteMany?: Prisma.PathSelectionScalarWhereInput | Prisma.PathSelectionScalarWhereInput[]
}

export type PathSelectionUncheckedUpdateManyWithoutCharacterNestedInput = {
  create?: Prisma.XOR<Prisma.PathSelectionCreateWithoutCharacterInput, Prisma.PathSelectionUncheckedCreateWithoutCharacterInput> | Prisma.PathSelectionCreateWithoutCharacterInput[] | Prisma.PathSelectionUncheckedCreateWithoutCharacterInput[]
  connectOrCreate?: Prisma.PathSelectionCreateOrConnectWithoutCharacterInput | Prisma.PathSelectionCreateOrConnectWithoutCharacterInput[]
  upsert?: Prisma.PathSelectionUpsertWithWhereUniqueWithoutCharacterInput | Prisma.PathSelectionUpsertWithWhereUniqueWithoutCharacterInput[]
  createMany?: Prisma.PathSelectionCreateManyCharacterInputEnvelope
  set?: Prisma.PathSelectionWhereUniqueInput | Prisma.PathSelectionWhereUniqueInput[]
  disconnect?: Prisma.PathSelectionWhereUniqueInput | Prisma.PathSelectionWhereUniqueInput[]
  delete?: Prisma.PathSelectionWhereUniqueInput | Prisma.PathSelectionWhereUniqueInput[]
  connect?: Prisma.PathSelectionWhereUniqueInput | Prisma.PathSelectionWhereUniqueInput[]
  update?: Prisma.PathSelectionUpdateWithWhereUniqueWithoutCharacterInput | Prisma.PathSelectionUpdateWithWhereUniqueWithoutCharacterInput[]
  updateMany?: Prisma.PathSelectionUpdateManyWithWhereWithoutCharacterInput | Prisma.PathSelectionUpdateManyWithWhereWithoutCharacterInput[]
  deleteMany?: Prisma.PathSelectionScalarWhereInput | Prisma.PathSelectionScalarWhereInput[]
}

export type PathSelectionCreateWithoutCharacterInput = {
  id?: string
  pathName: string
}

export type PathSelectionUncheckedCreateWithoutCharacterInput = {
  id?: string
  pathName: string
}

export type PathSelectionCreateOrConnectWithoutCharacterInput = {
  where: Prisma.PathSelectionWhereUniqueInput
  create: Prisma.XOR<Prisma.PathSelectionCreateWithoutCharacterInput, Prisma.PathSelectionUncheckedCreateWithoutCharacterInput>
}

export type PathSelectionCreateManyCharacterInputEnvelope = {
  data: Prisma.PathSelectionCreateManyCharacterInput | Prisma.PathSelectionCreateManyCharacterInput[]
}

export type PathSelectionUpsertWithWhereUniqueWithoutCharacterInput = {
  where: Prisma.PathSelectionWhereUniqueInput
  update: Prisma.XOR<Prisma.PathSelectionUpdateWithoutCharacterInput, Prisma.PathSelectionUncheckedUpdateWithoutCharacterInput>
  create: Prisma.XOR<Prisma.PathSelectionCreateWithoutCharacterInput, Prisma.PathSelectionUncheckedCreateWithoutCharacterInput>
}

export type PathSelectionUpdateWithWhereUniqueWithoutCharacterInput = {
  where: Prisma.PathSelectionWhereUniqueInput
  data: Prisma.XOR<Prisma.PathSelectionUpdateWithoutCharacterInput, Prisma.PathSelectionUncheckedUpdateWithoutCharacterInput>
}

export type PathSelectionUpdateManyWithWhereWithoutCharacterInput = {
  where: Prisma.PathSelectionScalarWhereInput
  data: Prisma.XOR<Prisma.PathSelectionUpdateManyMutationInput, Prisma.PathSelectionUncheckedUpdateManyWithoutCharacterInput>
}

export type PathSelectionScalarWhereInput = {
  AND?: Prisma.PathSelectionScalarWhereInput | Prisma.PathSelectionScalarWhereInput[]
  OR?: Prisma.PathSelectionScalarWhereInput[]
  NOT?: Prisma.PathSelectionScalarWhereInput | Prisma.PathSelectionScalarWhereInput[]
  id?: Prisma.StringFilter<"PathSelection"> | string
  characterId?: Prisma.StringFilter<"PathSelection"> | string
  pathName?: Prisma.StringFilter<"PathSelection"> | string
}

export type PathSelectionCreateManyCharacterInput = {
  id?: string
  pathName: string
}

export type PathSelectionUpdateWithoutCharacterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pathName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PathSelectionUncheckedUpdateWithoutCharacterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pathName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PathSelectionUncheckedUpdateManyWithoutCharacterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pathName?: Prisma.StringFieldUpdateOperationsInput | string
}



export type PathSelectionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  characterId?: boolean
  pathName?: boolean
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pathSelection"]>

export type PathSelectionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  characterId?: boolean
  pathName?: boolean
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pathSelection"]>

export type PathSelectionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  characterId?: boolean
  pathName?: boolean
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pathSelection"]>

export type PathSelectionSelectScalar = {
  id?: boolean
  characterId?: boolean
  pathName?: boolean
}

export type PathSelectionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "characterId" | "pathName", ExtArgs["result"]["pathSelection"]>
export type PathSelectionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}
export type PathSelectionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}
export type PathSelectionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}

export type $PathSelectionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PathSelection"
  objects: {
    character: Prisma.$CharacterPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    characterId: string
    pathName: string
  }, ExtArgs["result"]["pathSelection"]>
  composites: {}
}

export type PathSelectionGetPayload<S extends boolean | null | undefined | PathSelectionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PathSelectionPayload, S>

export type PathSelectionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PathSelectionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PathSelectionCountAggregateInputType | true
  }

export interface PathSelectionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PathSelection'], meta: { name: 'PathSelection' } }
  /**
   * Find zero or one PathSelection that matches the filter.
   * @param {PathSelectionFindUniqueArgs} args - Arguments to find a PathSelection
   * @example
   * // Get one PathSelection
   * const pathSelection = await prisma.pathSelection.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PathSelectionFindUniqueArgs>(args: Prisma.SelectSubset<T, PathSelectionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PathSelectionClient<runtime.Types.Result.GetResult<Prisma.$PathSelectionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PathSelection that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PathSelectionFindUniqueOrThrowArgs} args - Arguments to find a PathSelection
   * @example
   * // Get one PathSelection
   * const pathSelection = await prisma.pathSelection.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PathSelectionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PathSelectionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PathSelectionClient<runtime.Types.Result.GetResult<Prisma.$PathSelectionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PathSelection that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PathSelectionFindFirstArgs} args - Arguments to find a PathSelection
   * @example
   * // Get one PathSelection
   * const pathSelection = await prisma.pathSelection.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PathSelectionFindFirstArgs>(args?: Prisma.SelectSubset<T, PathSelectionFindFirstArgs<ExtArgs>>): Prisma.Prisma__PathSelectionClient<runtime.Types.Result.GetResult<Prisma.$PathSelectionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PathSelection that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PathSelectionFindFirstOrThrowArgs} args - Arguments to find a PathSelection
   * @example
   * // Get one PathSelection
   * const pathSelection = await prisma.pathSelection.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PathSelectionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PathSelectionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PathSelectionClient<runtime.Types.Result.GetResult<Prisma.$PathSelectionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PathSelections that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PathSelectionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PathSelections
   * const pathSelections = await prisma.pathSelection.findMany()
   * 
   * // Get first 10 PathSelections
   * const pathSelections = await prisma.pathSelection.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pathSelectionWithIdOnly = await prisma.pathSelection.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PathSelectionFindManyArgs>(args?: Prisma.SelectSubset<T, PathSelectionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PathSelectionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PathSelection.
   * @param {PathSelectionCreateArgs} args - Arguments to create a PathSelection.
   * @example
   * // Create one PathSelection
   * const PathSelection = await prisma.pathSelection.create({
   *   data: {
   *     // ... data to create a PathSelection
   *   }
   * })
   * 
   */
  create<T extends PathSelectionCreateArgs>(args: Prisma.SelectSubset<T, PathSelectionCreateArgs<ExtArgs>>): Prisma.Prisma__PathSelectionClient<runtime.Types.Result.GetResult<Prisma.$PathSelectionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PathSelections.
   * @param {PathSelectionCreateManyArgs} args - Arguments to create many PathSelections.
   * @example
   * // Create many PathSelections
   * const pathSelection = await prisma.pathSelection.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PathSelectionCreateManyArgs>(args?: Prisma.SelectSubset<T, PathSelectionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PathSelections and returns the data saved in the database.
   * @param {PathSelectionCreateManyAndReturnArgs} args - Arguments to create many PathSelections.
   * @example
   * // Create many PathSelections
   * const pathSelection = await prisma.pathSelection.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PathSelections and only return the `id`
   * const pathSelectionWithIdOnly = await prisma.pathSelection.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PathSelectionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PathSelectionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PathSelectionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PathSelection.
   * @param {PathSelectionDeleteArgs} args - Arguments to delete one PathSelection.
   * @example
   * // Delete one PathSelection
   * const PathSelection = await prisma.pathSelection.delete({
   *   where: {
   *     // ... filter to delete one PathSelection
   *   }
   * })
   * 
   */
  delete<T extends PathSelectionDeleteArgs>(args: Prisma.SelectSubset<T, PathSelectionDeleteArgs<ExtArgs>>): Prisma.Prisma__PathSelectionClient<runtime.Types.Result.GetResult<Prisma.$PathSelectionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PathSelection.
   * @param {PathSelectionUpdateArgs} args - Arguments to update one PathSelection.
   * @example
   * // Update one PathSelection
   * const pathSelection = await prisma.pathSelection.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PathSelectionUpdateArgs>(args: Prisma.SelectSubset<T, PathSelectionUpdateArgs<ExtArgs>>): Prisma.Prisma__PathSelectionClient<runtime.Types.Result.GetResult<Prisma.$PathSelectionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PathSelections.
   * @param {PathSelectionDeleteManyArgs} args - Arguments to filter PathSelections to delete.
   * @example
   * // Delete a few PathSelections
   * const { count } = await prisma.pathSelection.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PathSelectionDeleteManyArgs>(args?: Prisma.SelectSubset<T, PathSelectionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PathSelections.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PathSelectionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PathSelections
   * const pathSelection = await prisma.pathSelection.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PathSelectionUpdateManyArgs>(args: Prisma.SelectSubset<T, PathSelectionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PathSelections and returns the data updated in the database.
   * @param {PathSelectionUpdateManyAndReturnArgs} args - Arguments to update many PathSelections.
   * @example
   * // Update many PathSelections
   * const pathSelection = await prisma.pathSelection.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PathSelections and only return the `id`
   * const pathSelectionWithIdOnly = await prisma.pathSelection.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PathSelectionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PathSelectionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PathSelectionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PathSelection.
   * @param {PathSelectionUpsertArgs} args - Arguments to update or create a PathSelection.
   * @example
   * // Update or create a PathSelection
   * const pathSelection = await prisma.pathSelection.upsert({
   *   create: {
   *     // ... data to create a PathSelection
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PathSelection we want to update
   *   }
   * })
   */
  upsert<T extends PathSelectionUpsertArgs>(args: Prisma.SelectSubset<T, PathSelectionUpsertArgs<ExtArgs>>): Prisma.Prisma__PathSelectionClient<runtime.Types.Result.GetResult<Prisma.$PathSelectionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PathSelections.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PathSelectionCountArgs} args - Arguments to filter PathSelections to count.
   * @example
   * // Count the number of PathSelections
   * const count = await prisma.pathSelection.count({
   *   where: {
   *     // ... the filter for the PathSelections we want to count
   *   }
   * })
  **/
  count<T extends PathSelectionCountArgs>(
    args?: Prisma.Subset<T, PathSelectionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PathSelectionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PathSelection.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PathSelectionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PathSelectionAggregateArgs>(args: Prisma.Subset<T, PathSelectionAggregateArgs>): Prisma.PrismaPromise<GetPathSelectionAggregateType<T>>

  /**
   * Group by PathSelection.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PathSelectionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PathSelectionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PathSelectionGroupByArgs['orderBy'] }
      : { orderBy?: PathSelectionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PathSelectionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPathSelectionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PathSelection model
 */
readonly fields: PathSelectionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PathSelection.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PathSelectionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  character<T extends Prisma.CharacterDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CharacterDefaultArgs<ExtArgs>>): Prisma.Prisma__CharacterClient<runtime.Types.Result.GetResult<Prisma.$CharacterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PathSelection model
 */
export interface PathSelectionFieldRefs {
  readonly id: Prisma.FieldRef<"PathSelection", 'String'>
  readonly characterId: Prisma.FieldRef<"PathSelection", 'String'>
  readonly pathName: Prisma.FieldRef<"PathSelection", 'String'>
}
    

// Custom InputTypes
/**
 * PathSelection findUnique
 */
export type PathSelectionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathSelection
   */
  select?: Prisma.PathSelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PathSelection
   */
  omit?: Prisma.PathSelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathSelectionInclude<ExtArgs> | null
  /**
   * Filter, which PathSelection to fetch.
   */
  where: Prisma.PathSelectionWhereUniqueInput
}

/**
 * PathSelection findUniqueOrThrow
 */
export type PathSelectionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathSelection
   */
  select?: Prisma.PathSelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PathSelection
   */
  omit?: Prisma.PathSelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathSelectionInclude<ExtArgs> | null
  /**
   * Filter, which PathSelection to fetch.
   */
  where: Prisma.PathSelectionWhereUniqueInput
}

/**
 * PathSelection findFirst
 */
export type PathSelectionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathSelection
   */
  select?: Prisma.PathSelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PathSelection
   */
  omit?: Prisma.PathSelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathSelectionInclude<ExtArgs> | null
  /**
   * Filter, which PathSelection to fetch.
   */
  where?: Prisma.PathSelectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PathSelections to fetch.
   */
  orderBy?: Prisma.PathSelectionOrderByWithRelationInput | Prisma.PathSelectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PathSelections.
   */
  cursor?: Prisma.PathSelectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PathSelections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PathSelections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PathSelections.
   */
  distinct?: Prisma.PathSelectionScalarFieldEnum | Prisma.PathSelectionScalarFieldEnum[]
}

/**
 * PathSelection findFirstOrThrow
 */
export type PathSelectionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathSelection
   */
  select?: Prisma.PathSelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PathSelection
   */
  omit?: Prisma.PathSelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathSelectionInclude<ExtArgs> | null
  /**
   * Filter, which PathSelection to fetch.
   */
  where?: Prisma.PathSelectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PathSelections to fetch.
   */
  orderBy?: Prisma.PathSelectionOrderByWithRelationInput | Prisma.PathSelectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PathSelections.
   */
  cursor?: Prisma.PathSelectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PathSelections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PathSelections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PathSelections.
   */
  distinct?: Prisma.PathSelectionScalarFieldEnum | Prisma.PathSelectionScalarFieldEnum[]
}

/**
 * PathSelection findMany
 */
export type PathSelectionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathSelection
   */
  select?: Prisma.PathSelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PathSelection
   */
  omit?: Prisma.PathSelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathSelectionInclude<ExtArgs> | null
  /**
   * Filter, which PathSelections to fetch.
   */
  where?: Prisma.PathSelectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PathSelections to fetch.
   */
  orderBy?: Prisma.PathSelectionOrderByWithRelationInput | Prisma.PathSelectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PathSelections.
   */
  cursor?: Prisma.PathSelectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PathSelections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PathSelections.
   */
  skip?: number
  distinct?: Prisma.PathSelectionScalarFieldEnum | Prisma.PathSelectionScalarFieldEnum[]
}

/**
 * PathSelection create
 */
export type PathSelectionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathSelection
   */
  select?: Prisma.PathSelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PathSelection
   */
  omit?: Prisma.PathSelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathSelectionInclude<ExtArgs> | null
  /**
   * The data needed to create a PathSelection.
   */
  data: Prisma.XOR<Prisma.PathSelectionCreateInput, Prisma.PathSelectionUncheckedCreateInput>
}

/**
 * PathSelection createMany
 */
export type PathSelectionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PathSelections.
   */
  data: Prisma.PathSelectionCreateManyInput | Prisma.PathSelectionCreateManyInput[]
}

/**
 * PathSelection createManyAndReturn
 */
export type PathSelectionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathSelection
   */
  select?: Prisma.PathSelectionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PathSelection
   */
  omit?: Prisma.PathSelectionOmit<ExtArgs> | null
  /**
   * The data used to create many PathSelections.
   */
  data: Prisma.PathSelectionCreateManyInput | Prisma.PathSelectionCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathSelectionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PathSelection update
 */
export type PathSelectionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathSelection
   */
  select?: Prisma.PathSelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PathSelection
   */
  omit?: Prisma.PathSelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathSelectionInclude<ExtArgs> | null
  /**
   * The data needed to update a PathSelection.
   */
  data: Prisma.XOR<Prisma.PathSelectionUpdateInput, Prisma.PathSelectionUncheckedUpdateInput>
  /**
   * Choose, which PathSelection to update.
   */
  where: Prisma.PathSelectionWhereUniqueInput
}

/**
 * PathSelection updateMany
 */
export type PathSelectionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PathSelections.
   */
  data: Prisma.XOR<Prisma.PathSelectionUpdateManyMutationInput, Prisma.PathSelectionUncheckedUpdateManyInput>
  /**
   * Filter which PathSelections to update
   */
  where?: Prisma.PathSelectionWhereInput
  /**
   * Limit how many PathSelections to update.
   */
  limit?: number
}

/**
 * PathSelection updateManyAndReturn
 */
export type PathSelectionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathSelection
   */
  select?: Prisma.PathSelectionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PathSelection
   */
  omit?: Prisma.PathSelectionOmit<ExtArgs> | null
  /**
   * The data used to update PathSelections.
   */
  data: Prisma.XOR<Prisma.PathSelectionUpdateManyMutationInput, Prisma.PathSelectionUncheckedUpdateManyInput>
  /**
   * Filter which PathSelections to update
   */
  where?: Prisma.PathSelectionWhereInput
  /**
   * Limit how many PathSelections to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathSelectionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PathSelection upsert
 */
export type PathSelectionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathSelection
   */
  select?: Prisma.PathSelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PathSelection
   */
  omit?: Prisma.PathSelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathSelectionInclude<ExtArgs> | null
  /**
   * The filter to search for the PathSelection to update in case it exists.
   */
  where: Prisma.PathSelectionWhereUniqueInput
  /**
   * In case the PathSelection found by the `where` argument doesn't exist, create a new PathSelection with this data.
   */
  create: Prisma.XOR<Prisma.PathSelectionCreateInput, Prisma.PathSelectionUncheckedCreateInput>
  /**
   * In case the PathSelection was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PathSelectionUpdateInput, Prisma.PathSelectionUncheckedUpdateInput>
}

/**
 * PathSelection delete
 */
export type PathSelectionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathSelection
   */
  select?: Prisma.PathSelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PathSelection
   */
  omit?: Prisma.PathSelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathSelectionInclude<ExtArgs> | null
  /**
   * Filter which PathSelection to delete.
   */
  where: Prisma.PathSelectionWhereUniqueInput
}

/**
 * PathSelection deleteMany
 */
export type PathSelectionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PathSelections to delete
   */
  where?: Prisma.PathSelectionWhereInput
  /**
   * Limit how many PathSelections to delete.
   */
  limit?: number
}

/**
 * PathSelection without action
 */
export type PathSelectionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathSelection
   */
  select?: Prisma.PathSelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PathSelection
   */
  omit?: Prisma.PathSelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathSelectionInclude<ExtArgs> | null
}
