
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SelectedExpertise` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SelectedExpertise
 * 
 */
export type SelectedExpertiseModel = runtime.Types.Result.DefaultSelection<Prisma.$SelectedExpertisePayload>

export type AggregateSelectedExpertise = {
  _count: SelectedExpertiseCountAggregateOutputType | null
  _min: SelectedExpertiseMinAggregateOutputType | null
  _max: SelectedExpertiseMaxAggregateOutputType | null
}

export type SelectedExpertiseMinAggregateOutputType = {
  id: string | null
  characterId: string | null
  name: string | null
  source: string | null
  sourceId: string | null
}

export type SelectedExpertiseMaxAggregateOutputType = {
  id: string | null
  characterId: string | null
  name: string | null
  source: string | null
  sourceId: string | null
}

export type SelectedExpertiseCountAggregateOutputType = {
  id: number
  characterId: number
  name: number
  source: number
  sourceId: number
  _all: number
}


export type SelectedExpertiseMinAggregateInputType = {
  id?: true
  characterId?: true
  name?: true
  source?: true
  sourceId?: true
}

export type SelectedExpertiseMaxAggregateInputType = {
  id?: true
  characterId?: true
  name?: true
  source?: true
  sourceId?: true
}

export type SelectedExpertiseCountAggregateInputType = {
  id?: true
  characterId?: true
  name?: true
  source?: true
  sourceId?: true
  _all?: true
}

export type SelectedExpertiseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SelectedExpertise to aggregate.
   */
  where?: Prisma.SelectedExpertiseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SelectedExpertises to fetch.
   */
  orderBy?: Prisma.SelectedExpertiseOrderByWithRelationInput | Prisma.SelectedExpertiseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SelectedExpertiseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SelectedExpertises from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SelectedExpertises.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SelectedExpertises
  **/
  _count?: true | SelectedExpertiseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SelectedExpertiseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SelectedExpertiseMaxAggregateInputType
}

export type GetSelectedExpertiseAggregateType<T extends SelectedExpertiseAggregateArgs> = {
      [P in keyof T & keyof AggregateSelectedExpertise]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSelectedExpertise[P]>
    : Prisma.GetScalarType<T[P], AggregateSelectedExpertise[P]>
}




export type SelectedExpertiseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SelectedExpertiseWhereInput
  orderBy?: Prisma.SelectedExpertiseOrderByWithAggregationInput | Prisma.SelectedExpertiseOrderByWithAggregationInput[]
  by: Prisma.SelectedExpertiseScalarFieldEnum[] | Prisma.SelectedExpertiseScalarFieldEnum
  having?: Prisma.SelectedExpertiseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SelectedExpertiseCountAggregateInputType | true
  _min?: SelectedExpertiseMinAggregateInputType
  _max?: SelectedExpertiseMaxAggregateInputType
}

export type SelectedExpertiseGroupByOutputType = {
  id: string
  characterId: string
  name: string
  source: string
  sourceId: string
  _count: SelectedExpertiseCountAggregateOutputType | null
  _min: SelectedExpertiseMinAggregateOutputType | null
  _max: SelectedExpertiseMaxAggregateOutputType | null
}

type GetSelectedExpertiseGroupByPayload<T extends SelectedExpertiseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SelectedExpertiseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SelectedExpertiseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SelectedExpertiseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SelectedExpertiseGroupByOutputType[P]>
      }
    >
  >



export type SelectedExpertiseWhereInput = {
  AND?: Prisma.SelectedExpertiseWhereInput | Prisma.SelectedExpertiseWhereInput[]
  OR?: Prisma.SelectedExpertiseWhereInput[]
  NOT?: Prisma.SelectedExpertiseWhereInput | Prisma.SelectedExpertiseWhereInput[]
  id?: Prisma.StringFilter<"SelectedExpertise"> | string
  characterId?: Prisma.StringFilter<"SelectedExpertise"> | string
  name?: Prisma.StringFilter<"SelectedExpertise"> | string
  source?: Prisma.StringFilter<"SelectedExpertise"> | string
  sourceId?: Prisma.StringFilter<"SelectedExpertise"> | string
  character?: Prisma.XOR<Prisma.CharacterScalarRelationFilter, Prisma.CharacterWhereInput>
}

export type SelectedExpertiseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  source?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
  character?: Prisma.CharacterOrderByWithRelationInput
}

export type SelectedExpertiseWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  characterId_name?: Prisma.SelectedExpertiseCharacterIdNameCompoundUniqueInput
  AND?: Prisma.SelectedExpertiseWhereInput | Prisma.SelectedExpertiseWhereInput[]
  OR?: Prisma.SelectedExpertiseWhereInput[]
  NOT?: Prisma.SelectedExpertiseWhereInput | Prisma.SelectedExpertiseWhereInput[]
  characterId?: Prisma.StringFilter<"SelectedExpertise"> | string
  name?: Prisma.StringFilter<"SelectedExpertise"> | string
  source?: Prisma.StringFilter<"SelectedExpertise"> | string
  sourceId?: Prisma.StringFilter<"SelectedExpertise"> | string
  character?: Prisma.XOR<Prisma.CharacterScalarRelationFilter, Prisma.CharacterWhereInput>
}, "id" | "characterId_name">

export type SelectedExpertiseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  source?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
  _count?: Prisma.SelectedExpertiseCountOrderByAggregateInput
  _max?: Prisma.SelectedExpertiseMaxOrderByAggregateInput
  _min?: Prisma.SelectedExpertiseMinOrderByAggregateInput
}

export type SelectedExpertiseScalarWhereWithAggregatesInput = {
  AND?: Prisma.SelectedExpertiseScalarWhereWithAggregatesInput | Prisma.SelectedExpertiseScalarWhereWithAggregatesInput[]
  OR?: Prisma.SelectedExpertiseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SelectedExpertiseScalarWhereWithAggregatesInput | Prisma.SelectedExpertiseScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SelectedExpertise"> | string
  characterId?: Prisma.StringWithAggregatesFilter<"SelectedExpertise"> | string
  name?: Prisma.StringWithAggregatesFilter<"SelectedExpertise"> | string
  source?: Prisma.StringWithAggregatesFilter<"SelectedExpertise"> | string
  sourceId?: Prisma.StringWithAggregatesFilter<"SelectedExpertise"> | string
}

export type SelectedExpertiseCreateInput = {
  id?: string
  name: string
  source: string
  sourceId: string
  character: Prisma.CharacterCreateNestedOneWithoutExpertisesInput
}

export type SelectedExpertiseUncheckedCreateInput = {
  id?: string
  characterId: string
  name: string
  source: string
  sourceId: string
}

export type SelectedExpertiseUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  sourceId?: Prisma.StringFieldUpdateOperationsInput | string
  character?: Prisma.CharacterUpdateOneRequiredWithoutExpertisesNestedInput
}

export type SelectedExpertiseUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  characterId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  sourceId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SelectedExpertiseCreateManyInput = {
  id?: string
  characterId: string
  name: string
  source: string
  sourceId: string
}

export type SelectedExpertiseUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  sourceId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SelectedExpertiseUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  characterId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  sourceId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SelectedExpertiseListRelationFilter = {
  every?: Prisma.SelectedExpertiseWhereInput
  some?: Prisma.SelectedExpertiseWhereInput
  none?: Prisma.SelectedExpertiseWhereInput
}

export type SelectedExpertiseOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SelectedExpertiseCharacterIdNameCompoundUniqueInput = {
  characterId: string
  name: string
}

export type SelectedExpertiseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  source?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
}

export type SelectedExpertiseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  source?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
}

export type SelectedExpertiseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  source?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
}

export type SelectedExpertiseCreateNestedManyWithoutCharacterInput = {
  create?: Prisma.XOR<Prisma.SelectedExpertiseCreateWithoutCharacterInput, Prisma.SelectedExpertiseUncheckedCreateWithoutCharacterInput> | Prisma.SelectedExpertiseCreateWithoutCharacterInput[] | Prisma.SelectedExpertiseUncheckedCreateWithoutCharacterInput[]
  connectOrCreate?: Prisma.SelectedExpertiseCreateOrConnectWithoutCharacterInput | Prisma.SelectedExpertiseCreateOrConnectWithoutCharacterInput[]
  createMany?: Prisma.SelectedExpertiseCreateManyCharacterInputEnvelope
  connect?: Prisma.SelectedExpertiseWhereUniqueInput | Prisma.SelectedExpertiseWhereUniqueInput[]
}

export type SelectedExpertiseUncheckedCreateNestedManyWithoutCharacterInput = {
  create?: Prisma.XOR<Prisma.SelectedExpertiseCreateWithoutCharacterInput, Prisma.SelectedExpertiseUncheckedCreateWithoutCharacterInput> | Prisma.SelectedExpertiseCreateWithoutCharacterInput[] | Prisma.SelectedExpertiseUncheckedCreateWithoutCharacterInput[]
  connectOrCreate?: Prisma.SelectedExpertiseCreateOrConnectWithoutCharacterInput | Prisma.SelectedExpertiseCreateOrConnectWithoutCharacterInput[]
  createMany?: Prisma.SelectedExpertiseCreateManyCharacterInputEnvelope
  connect?: Prisma.SelectedExpertiseWhereUniqueInput | Prisma.SelectedExpertiseWhereUniqueInput[]
}

export type SelectedExpertiseUpdateManyWithoutCharacterNestedInput = {
  create?: Prisma.XOR<Prisma.SelectedExpertiseCreateWithoutCharacterInput, Prisma.SelectedExpertiseUncheckedCreateWithoutCharacterInput> | Prisma.SelectedExpertiseCreateWithoutCharacterInput[] | Prisma.SelectedExpertiseUncheckedCreateWithoutCharacterInput[]
  connectOrCreate?: Prisma.SelectedExpertiseCreateOrConnectWithoutCharacterInput | Prisma.SelectedExpertiseCreateOrConnectWithoutCharacterInput[]
  upsert?: Prisma.SelectedExpertiseUpsertWithWhereUniqueWithoutCharacterInput | Prisma.SelectedExpertiseUpsertWithWhereUniqueWithoutCharacterInput[]
  createMany?: Prisma.SelectedExpertiseCreateManyCharacterInputEnvelope
  set?: Prisma.SelectedExpertiseWhereUniqueInput | Prisma.SelectedExpertiseWhereUniqueInput[]
  disconnect?: Prisma.SelectedExpertiseWhereUniqueInput | Prisma.SelectedExpertiseWhereUniqueInput[]
  delete?: Prisma.SelectedExpertiseWhereUniqueInput | Prisma.SelectedExpertiseWhereUniqueInput[]
  connect?: Prisma.SelectedExpertiseWhereUniqueInput | Prisma.SelectedExpertiseWhereUniqueInput[]
  update?: Prisma.SelectedExpertiseUpdateWithWhereUniqueWithoutCharacterInput | Prisma.SelectedExpertiseUpdateWithWhereUniqueWithoutCharacterInput[]
  updateMany?: Prisma.SelectedExpertiseUpdateManyWithWhereWithoutCharacterInput | Prisma.SelectedExpertiseUpdateManyWithWhereWithoutCharacterInput[]
  deleteMany?: Prisma.SelectedExpertiseScalarWhereInput | Prisma.SelectedExpertiseScalarWhereInput[]
}

export type SelectedExpertiseUncheckedUpdateManyWithoutCharacterNestedInput = {
  create?: Prisma.XOR<Prisma.SelectedExpertiseCreateWithoutCharacterInput, Prisma.SelectedExpertiseUncheckedCreateWithoutCharacterInput> | Prisma.SelectedExpertiseCreateWithoutCharacterInput[] | Prisma.SelectedExpertiseUncheckedCreateWithoutCharacterInput[]
  connectOrCreate?: Prisma.SelectedExpertiseCreateOrConnectWithoutCharacterInput | Prisma.SelectedExpertiseCreateOrConnectWithoutCharacterInput[]
  upsert?: Prisma.SelectedExpertiseUpsertWithWhereUniqueWithoutCharacterInput | Prisma.SelectedExpertiseUpsertWithWhereUniqueWithoutCharacterInput[]
  createMany?: Prisma.SelectedExpertiseCreateManyCharacterInputEnvelope
  set?: Prisma.SelectedExpertiseWhereUniqueInput | Prisma.SelectedExpertiseWhereUniqueInput[]
  disconnect?: Prisma.SelectedExpertiseWhereUniqueInput | Prisma.SelectedExpertiseWhereUniqueInput[]
  delete?: Prisma.SelectedExpertiseWhereUniqueInput | Prisma.SelectedExpertiseWhereUniqueInput[]
  connect?: Prisma.SelectedExpertiseWhereUniqueInput | Prisma.SelectedExpertiseWhereUniqueInput[]
  update?: Prisma.SelectedExpertiseUpdateWithWhereUniqueWithoutCharacterInput | Prisma.SelectedExpertiseUpdateWithWhereUniqueWithoutCharacterInput[]
  updateMany?: Prisma.SelectedExpertiseUpdateManyWithWhereWithoutCharacterInput | Prisma.SelectedExpertiseUpdateManyWithWhereWithoutCharacterInput[]
  deleteMany?: Prisma.SelectedExpertiseScalarWhereInput | Prisma.SelectedExpertiseScalarWhereInput[]
}

export type SelectedExpertiseCreateWithoutCharacterInput = {
  id?: string
  name: string
  source: string
  sourceId: string
}

export type SelectedExpertiseUncheckedCreateWithoutCharacterInput = {
  id?: string
  name: string
  source: string
  sourceId: string
}

export type SelectedExpertiseCreateOrConnectWithoutCharacterInput = {
  where: Prisma.SelectedExpertiseWhereUniqueInput
  create: Prisma.XOR<Prisma.SelectedExpertiseCreateWithoutCharacterInput, Prisma.SelectedExpertiseUncheckedCreateWithoutCharacterInput>
}

export type SelectedExpertiseCreateManyCharacterInputEnvelope = {
  data: Prisma.SelectedExpertiseCreateManyCharacterInput | Prisma.SelectedExpertiseCreateManyCharacterInput[]
}

export type SelectedExpertiseUpsertWithWhereUniqueWithoutCharacterInput = {
  where: Prisma.SelectedExpertiseWhereUniqueInput
  update: Prisma.XOR<Prisma.SelectedExpertiseUpdateWithoutCharacterInput, Prisma.SelectedExpertiseUncheckedUpdateWithoutCharacterInput>
  create: Prisma.XOR<Prisma.SelectedExpertiseCreateWithoutCharacterInput, Prisma.SelectedExpertiseUncheckedCreateWithoutCharacterInput>
}

export type SelectedExpertiseUpdateWithWhereUniqueWithoutCharacterInput = {
  where: Prisma.SelectedExpertiseWhereUniqueInput
  data: Prisma.XOR<Prisma.SelectedExpertiseUpdateWithoutCharacterInput, Prisma.SelectedExpertiseUncheckedUpdateWithoutCharacterInput>
}

export type SelectedExpertiseUpdateManyWithWhereWithoutCharacterInput = {
  where: Prisma.SelectedExpertiseScalarWhereInput
  data: Prisma.XOR<Prisma.SelectedExpertiseUpdateManyMutationInput, Prisma.SelectedExpertiseUncheckedUpdateManyWithoutCharacterInput>
}

export type SelectedExpertiseScalarWhereInput = {
  AND?: Prisma.SelectedExpertiseScalarWhereInput | Prisma.SelectedExpertiseScalarWhereInput[]
  OR?: Prisma.SelectedExpertiseScalarWhereInput[]
  NOT?: Prisma.SelectedExpertiseScalarWhereInput | Prisma.SelectedExpertiseScalarWhereInput[]
  id?: Prisma.StringFilter<"SelectedExpertise"> | string
  characterId?: Prisma.StringFilter<"SelectedExpertise"> | string
  name?: Prisma.StringFilter<"SelectedExpertise"> | string
  source?: Prisma.StringFilter<"SelectedExpertise"> | string
  sourceId?: Prisma.StringFilter<"SelectedExpertise"> | string
}

export type SelectedExpertiseCreateManyCharacterInput = {
  id?: string
  name: string
  source: string
  sourceId: string
}

export type SelectedExpertiseUpdateWithoutCharacterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  sourceId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SelectedExpertiseUncheckedUpdateWithoutCharacterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  sourceId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SelectedExpertiseUncheckedUpdateManyWithoutCharacterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  sourceId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type SelectedExpertiseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  characterId?: boolean
  name?: boolean
  source?: boolean
  sourceId?: boolean
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["selectedExpertise"]>

export type SelectedExpertiseSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  characterId?: boolean
  name?: boolean
  source?: boolean
  sourceId?: boolean
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["selectedExpertise"]>

export type SelectedExpertiseSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  characterId?: boolean
  name?: boolean
  source?: boolean
  sourceId?: boolean
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["selectedExpertise"]>

export type SelectedExpertiseSelectScalar = {
  id?: boolean
  characterId?: boolean
  name?: boolean
  source?: boolean
  sourceId?: boolean
}

export type SelectedExpertiseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "characterId" | "name" | "source" | "sourceId", ExtArgs["result"]["selectedExpertise"]>
export type SelectedExpertiseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}
export type SelectedExpertiseIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}
export type SelectedExpertiseIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}

export type $SelectedExpertisePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SelectedExpertise"
  objects: {
    character: Prisma.$CharacterPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    characterId: string
    name: string
    source: string
    sourceId: string
  }, ExtArgs["result"]["selectedExpertise"]>
  composites: {}
}

export type SelectedExpertiseGetPayload<S extends boolean | null | undefined | SelectedExpertiseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SelectedExpertisePayload, S>

export type SelectedExpertiseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SelectedExpertiseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SelectedExpertiseCountAggregateInputType | true
  }

export interface SelectedExpertiseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SelectedExpertise'], meta: { name: 'SelectedExpertise' } }
  /**
   * Find zero or one SelectedExpertise that matches the filter.
   * @param {SelectedExpertiseFindUniqueArgs} args - Arguments to find a SelectedExpertise
   * @example
   * // Get one SelectedExpertise
   * const selectedExpertise = await prisma.selectedExpertise.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SelectedExpertiseFindUniqueArgs>(args: Prisma.SelectSubset<T, SelectedExpertiseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SelectedExpertiseClient<runtime.Types.Result.GetResult<Prisma.$SelectedExpertisePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SelectedExpertise that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SelectedExpertiseFindUniqueOrThrowArgs} args - Arguments to find a SelectedExpertise
   * @example
   * // Get one SelectedExpertise
   * const selectedExpertise = await prisma.selectedExpertise.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SelectedExpertiseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SelectedExpertiseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SelectedExpertiseClient<runtime.Types.Result.GetResult<Prisma.$SelectedExpertisePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SelectedExpertise that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SelectedExpertiseFindFirstArgs} args - Arguments to find a SelectedExpertise
   * @example
   * // Get one SelectedExpertise
   * const selectedExpertise = await prisma.selectedExpertise.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SelectedExpertiseFindFirstArgs>(args?: Prisma.SelectSubset<T, SelectedExpertiseFindFirstArgs<ExtArgs>>): Prisma.Prisma__SelectedExpertiseClient<runtime.Types.Result.GetResult<Prisma.$SelectedExpertisePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SelectedExpertise that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SelectedExpertiseFindFirstOrThrowArgs} args - Arguments to find a SelectedExpertise
   * @example
   * // Get one SelectedExpertise
   * const selectedExpertise = await prisma.selectedExpertise.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SelectedExpertiseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SelectedExpertiseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SelectedExpertiseClient<runtime.Types.Result.GetResult<Prisma.$SelectedExpertisePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SelectedExpertises that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SelectedExpertiseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SelectedExpertises
   * const selectedExpertises = await prisma.selectedExpertise.findMany()
   * 
   * // Get first 10 SelectedExpertises
   * const selectedExpertises = await prisma.selectedExpertise.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const selectedExpertiseWithIdOnly = await prisma.selectedExpertise.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SelectedExpertiseFindManyArgs>(args?: Prisma.SelectSubset<T, SelectedExpertiseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SelectedExpertisePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SelectedExpertise.
   * @param {SelectedExpertiseCreateArgs} args - Arguments to create a SelectedExpertise.
   * @example
   * // Create one SelectedExpertise
   * const SelectedExpertise = await prisma.selectedExpertise.create({
   *   data: {
   *     // ... data to create a SelectedExpertise
   *   }
   * })
   * 
   */
  create<T extends SelectedExpertiseCreateArgs>(args: Prisma.SelectSubset<T, SelectedExpertiseCreateArgs<ExtArgs>>): Prisma.Prisma__SelectedExpertiseClient<runtime.Types.Result.GetResult<Prisma.$SelectedExpertisePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SelectedExpertises.
   * @param {SelectedExpertiseCreateManyArgs} args - Arguments to create many SelectedExpertises.
   * @example
   * // Create many SelectedExpertises
   * const selectedExpertise = await prisma.selectedExpertise.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SelectedExpertiseCreateManyArgs>(args?: Prisma.SelectSubset<T, SelectedExpertiseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SelectedExpertises and returns the data saved in the database.
   * @param {SelectedExpertiseCreateManyAndReturnArgs} args - Arguments to create many SelectedExpertises.
   * @example
   * // Create many SelectedExpertises
   * const selectedExpertise = await prisma.selectedExpertise.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SelectedExpertises and only return the `id`
   * const selectedExpertiseWithIdOnly = await prisma.selectedExpertise.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SelectedExpertiseCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SelectedExpertiseCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SelectedExpertisePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SelectedExpertise.
   * @param {SelectedExpertiseDeleteArgs} args - Arguments to delete one SelectedExpertise.
   * @example
   * // Delete one SelectedExpertise
   * const SelectedExpertise = await prisma.selectedExpertise.delete({
   *   where: {
   *     // ... filter to delete one SelectedExpertise
   *   }
   * })
   * 
   */
  delete<T extends SelectedExpertiseDeleteArgs>(args: Prisma.SelectSubset<T, SelectedExpertiseDeleteArgs<ExtArgs>>): Prisma.Prisma__SelectedExpertiseClient<runtime.Types.Result.GetResult<Prisma.$SelectedExpertisePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SelectedExpertise.
   * @param {SelectedExpertiseUpdateArgs} args - Arguments to update one SelectedExpertise.
   * @example
   * // Update one SelectedExpertise
   * const selectedExpertise = await prisma.selectedExpertise.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SelectedExpertiseUpdateArgs>(args: Prisma.SelectSubset<T, SelectedExpertiseUpdateArgs<ExtArgs>>): Prisma.Prisma__SelectedExpertiseClient<runtime.Types.Result.GetResult<Prisma.$SelectedExpertisePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SelectedExpertises.
   * @param {SelectedExpertiseDeleteManyArgs} args - Arguments to filter SelectedExpertises to delete.
   * @example
   * // Delete a few SelectedExpertises
   * const { count } = await prisma.selectedExpertise.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SelectedExpertiseDeleteManyArgs>(args?: Prisma.SelectSubset<T, SelectedExpertiseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SelectedExpertises.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SelectedExpertiseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SelectedExpertises
   * const selectedExpertise = await prisma.selectedExpertise.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SelectedExpertiseUpdateManyArgs>(args: Prisma.SelectSubset<T, SelectedExpertiseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SelectedExpertises and returns the data updated in the database.
   * @param {SelectedExpertiseUpdateManyAndReturnArgs} args - Arguments to update many SelectedExpertises.
   * @example
   * // Update many SelectedExpertises
   * const selectedExpertise = await prisma.selectedExpertise.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SelectedExpertises and only return the `id`
   * const selectedExpertiseWithIdOnly = await prisma.selectedExpertise.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SelectedExpertiseUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SelectedExpertiseUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SelectedExpertisePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SelectedExpertise.
   * @param {SelectedExpertiseUpsertArgs} args - Arguments to update or create a SelectedExpertise.
   * @example
   * // Update or create a SelectedExpertise
   * const selectedExpertise = await prisma.selectedExpertise.upsert({
   *   create: {
   *     // ... data to create a SelectedExpertise
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SelectedExpertise we want to update
   *   }
   * })
   */
  upsert<T extends SelectedExpertiseUpsertArgs>(args: Prisma.SelectSubset<T, SelectedExpertiseUpsertArgs<ExtArgs>>): Prisma.Prisma__SelectedExpertiseClient<runtime.Types.Result.GetResult<Prisma.$SelectedExpertisePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SelectedExpertises.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SelectedExpertiseCountArgs} args - Arguments to filter SelectedExpertises to count.
   * @example
   * // Count the number of SelectedExpertises
   * const count = await prisma.selectedExpertise.count({
   *   where: {
   *     // ... the filter for the SelectedExpertises we want to count
   *   }
   * })
  **/
  count<T extends SelectedExpertiseCountArgs>(
    args?: Prisma.Subset<T, SelectedExpertiseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SelectedExpertiseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SelectedExpertise.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SelectedExpertiseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SelectedExpertiseAggregateArgs>(args: Prisma.Subset<T, SelectedExpertiseAggregateArgs>): Prisma.PrismaPromise<GetSelectedExpertiseAggregateType<T>>

  /**
   * Group by SelectedExpertise.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SelectedExpertiseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SelectedExpertiseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SelectedExpertiseGroupByArgs['orderBy'] }
      : { orderBy?: SelectedExpertiseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SelectedExpertiseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSelectedExpertiseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SelectedExpertise model
 */
readonly fields: SelectedExpertiseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SelectedExpertise.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SelectedExpertiseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  character<T extends Prisma.CharacterDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CharacterDefaultArgs<ExtArgs>>): Prisma.Prisma__CharacterClient<runtime.Types.Result.GetResult<Prisma.$CharacterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SelectedExpertise model
 */
export interface SelectedExpertiseFieldRefs {
  readonly id: Prisma.FieldRef<"SelectedExpertise", 'String'>
  readonly characterId: Prisma.FieldRef<"SelectedExpertise", 'String'>
  readonly name: Prisma.FieldRef<"SelectedExpertise", 'String'>
  readonly source: Prisma.FieldRef<"SelectedExpertise", 'String'>
  readonly sourceId: Prisma.FieldRef<"SelectedExpertise", 'String'>
}
    

// Custom InputTypes
/**
 * SelectedExpertise findUnique
 */
export type SelectedExpertiseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SelectedExpertise
   */
  select?: Prisma.SelectedExpertiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SelectedExpertise
   */
  omit?: Prisma.SelectedExpertiseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectedExpertiseInclude<ExtArgs> | null
  /**
   * Filter, which SelectedExpertise to fetch.
   */
  where: Prisma.SelectedExpertiseWhereUniqueInput
}

/**
 * SelectedExpertise findUniqueOrThrow
 */
export type SelectedExpertiseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SelectedExpertise
   */
  select?: Prisma.SelectedExpertiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SelectedExpertise
   */
  omit?: Prisma.SelectedExpertiseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectedExpertiseInclude<ExtArgs> | null
  /**
   * Filter, which SelectedExpertise to fetch.
   */
  where: Prisma.SelectedExpertiseWhereUniqueInput
}

/**
 * SelectedExpertise findFirst
 */
export type SelectedExpertiseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SelectedExpertise
   */
  select?: Prisma.SelectedExpertiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SelectedExpertise
   */
  omit?: Prisma.SelectedExpertiseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectedExpertiseInclude<ExtArgs> | null
  /**
   * Filter, which SelectedExpertise to fetch.
   */
  where?: Prisma.SelectedExpertiseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SelectedExpertises to fetch.
   */
  orderBy?: Prisma.SelectedExpertiseOrderByWithRelationInput | Prisma.SelectedExpertiseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SelectedExpertises.
   */
  cursor?: Prisma.SelectedExpertiseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SelectedExpertises from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SelectedExpertises.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SelectedExpertises.
   */
  distinct?: Prisma.SelectedExpertiseScalarFieldEnum | Prisma.SelectedExpertiseScalarFieldEnum[]
}

/**
 * SelectedExpertise findFirstOrThrow
 */
export type SelectedExpertiseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SelectedExpertise
   */
  select?: Prisma.SelectedExpertiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SelectedExpertise
   */
  omit?: Prisma.SelectedExpertiseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectedExpertiseInclude<ExtArgs> | null
  /**
   * Filter, which SelectedExpertise to fetch.
   */
  where?: Prisma.SelectedExpertiseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SelectedExpertises to fetch.
   */
  orderBy?: Prisma.SelectedExpertiseOrderByWithRelationInput | Prisma.SelectedExpertiseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SelectedExpertises.
   */
  cursor?: Prisma.SelectedExpertiseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SelectedExpertises from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SelectedExpertises.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SelectedExpertises.
   */
  distinct?: Prisma.SelectedExpertiseScalarFieldEnum | Prisma.SelectedExpertiseScalarFieldEnum[]
}

/**
 * SelectedExpertise findMany
 */
export type SelectedExpertiseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SelectedExpertise
   */
  select?: Prisma.SelectedExpertiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SelectedExpertise
   */
  omit?: Prisma.SelectedExpertiseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectedExpertiseInclude<ExtArgs> | null
  /**
   * Filter, which SelectedExpertises to fetch.
   */
  where?: Prisma.SelectedExpertiseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SelectedExpertises to fetch.
   */
  orderBy?: Prisma.SelectedExpertiseOrderByWithRelationInput | Prisma.SelectedExpertiseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SelectedExpertises.
   */
  cursor?: Prisma.SelectedExpertiseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SelectedExpertises from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SelectedExpertises.
   */
  skip?: number
  distinct?: Prisma.SelectedExpertiseScalarFieldEnum | Prisma.SelectedExpertiseScalarFieldEnum[]
}

/**
 * SelectedExpertise create
 */
export type SelectedExpertiseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SelectedExpertise
   */
  select?: Prisma.SelectedExpertiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SelectedExpertise
   */
  omit?: Prisma.SelectedExpertiseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectedExpertiseInclude<ExtArgs> | null
  /**
   * The data needed to create a SelectedExpertise.
   */
  data: Prisma.XOR<Prisma.SelectedExpertiseCreateInput, Prisma.SelectedExpertiseUncheckedCreateInput>
}

/**
 * SelectedExpertise createMany
 */
export type SelectedExpertiseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SelectedExpertises.
   */
  data: Prisma.SelectedExpertiseCreateManyInput | Prisma.SelectedExpertiseCreateManyInput[]
}

/**
 * SelectedExpertise createManyAndReturn
 */
export type SelectedExpertiseCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SelectedExpertise
   */
  select?: Prisma.SelectedExpertiseSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SelectedExpertise
   */
  omit?: Prisma.SelectedExpertiseOmit<ExtArgs> | null
  /**
   * The data used to create many SelectedExpertises.
   */
  data: Prisma.SelectedExpertiseCreateManyInput | Prisma.SelectedExpertiseCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectedExpertiseIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SelectedExpertise update
 */
export type SelectedExpertiseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SelectedExpertise
   */
  select?: Prisma.SelectedExpertiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SelectedExpertise
   */
  omit?: Prisma.SelectedExpertiseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectedExpertiseInclude<ExtArgs> | null
  /**
   * The data needed to update a SelectedExpertise.
   */
  data: Prisma.XOR<Prisma.SelectedExpertiseUpdateInput, Prisma.SelectedExpertiseUncheckedUpdateInput>
  /**
   * Choose, which SelectedExpertise to update.
   */
  where: Prisma.SelectedExpertiseWhereUniqueInput
}

/**
 * SelectedExpertise updateMany
 */
export type SelectedExpertiseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SelectedExpertises.
   */
  data: Prisma.XOR<Prisma.SelectedExpertiseUpdateManyMutationInput, Prisma.SelectedExpertiseUncheckedUpdateManyInput>
  /**
   * Filter which SelectedExpertises to update
   */
  where?: Prisma.SelectedExpertiseWhereInput
  /**
   * Limit how many SelectedExpertises to update.
   */
  limit?: number
}

/**
 * SelectedExpertise updateManyAndReturn
 */
export type SelectedExpertiseUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SelectedExpertise
   */
  select?: Prisma.SelectedExpertiseSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SelectedExpertise
   */
  omit?: Prisma.SelectedExpertiseOmit<ExtArgs> | null
  /**
   * The data used to update SelectedExpertises.
   */
  data: Prisma.XOR<Prisma.SelectedExpertiseUpdateManyMutationInput, Prisma.SelectedExpertiseUncheckedUpdateManyInput>
  /**
   * Filter which SelectedExpertises to update
   */
  where?: Prisma.SelectedExpertiseWhereInput
  /**
   * Limit how many SelectedExpertises to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectedExpertiseIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SelectedExpertise upsert
 */
export type SelectedExpertiseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SelectedExpertise
   */
  select?: Prisma.SelectedExpertiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SelectedExpertise
   */
  omit?: Prisma.SelectedExpertiseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectedExpertiseInclude<ExtArgs> | null
  /**
   * The filter to search for the SelectedExpertise to update in case it exists.
   */
  where: Prisma.SelectedExpertiseWhereUniqueInput
  /**
   * In case the SelectedExpertise found by the `where` argument doesn't exist, create a new SelectedExpertise with this data.
   */
  create: Prisma.XOR<Prisma.SelectedExpertiseCreateInput, Prisma.SelectedExpertiseUncheckedCreateInput>
  /**
   * In case the SelectedExpertise was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SelectedExpertiseUpdateInput, Prisma.SelectedExpertiseUncheckedUpdateInput>
}

/**
 * SelectedExpertise delete
 */
export type SelectedExpertiseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SelectedExpertise
   */
  select?: Prisma.SelectedExpertiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SelectedExpertise
   */
  omit?: Prisma.SelectedExpertiseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectedExpertiseInclude<ExtArgs> | null
  /**
   * Filter which SelectedExpertise to delete.
   */
  where: Prisma.SelectedExpertiseWhereUniqueInput
}

/**
 * SelectedExpertise deleteMany
 */
export type SelectedExpertiseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SelectedExpertises to delete
   */
  where?: Prisma.SelectedExpertiseWhereInput
  /**
   * Limit how many SelectedExpertises to delete.
   */
  limit?: number
}

/**
 * SelectedExpertise without action
 */
export type SelectedExpertiseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SelectedExpertise
   */
  select?: Prisma.SelectedExpertiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SelectedExpertise
   */
  omit?: Prisma.SelectedExpertiseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectedExpertiseInclude<ExtArgs> | null
}
