
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UnlockedTalent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model UnlockedTalent
 * 
 */
export type UnlockedTalentModel = runtime.Types.Result.DefaultSelection<Prisma.$UnlockedTalentPayload>

export type AggregateUnlockedTalent = {
  _count: UnlockedTalentCountAggregateOutputType | null
  _avg: UnlockedTalentAvgAggregateOutputType | null
  _sum: UnlockedTalentSumAggregateOutputType | null
  _min: UnlockedTalentMinAggregateOutputType | null
  _max: UnlockedTalentMaxAggregateOutputType | null
}

export type UnlockedTalentAvgAggregateOutputType = {
  level: number | null
}

export type UnlockedTalentSumAggregateOutputType = {
  level: number | null
}

export type UnlockedTalentMinAggregateOutputType = {
  id: string | null
  characterId: string | null
  talentId: string | null
  unlockedAt: Date | null
  level: number | null
}

export type UnlockedTalentMaxAggregateOutputType = {
  id: string | null
  characterId: string | null
  talentId: string | null
  unlockedAt: Date | null
  level: number | null
}

export type UnlockedTalentCountAggregateOutputType = {
  id: number
  characterId: number
  talentId: number
  unlockedAt: number
  level: number
  _all: number
}


export type UnlockedTalentAvgAggregateInputType = {
  level?: true
}

export type UnlockedTalentSumAggregateInputType = {
  level?: true
}

export type UnlockedTalentMinAggregateInputType = {
  id?: true
  characterId?: true
  talentId?: true
  unlockedAt?: true
  level?: true
}

export type UnlockedTalentMaxAggregateInputType = {
  id?: true
  characterId?: true
  talentId?: true
  unlockedAt?: true
  level?: true
}

export type UnlockedTalentCountAggregateInputType = {
  id?: true
  characterId?: true
  talentId?: true
  unlockedAt?: true
  level?: true
  _all?: true
}

export type UnlockedTalentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UnlockedTalent to aggregate.
   */
  where?: Prisma.UnlockedTalentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UnlockedTalents to fetch.
   */
  orderBy?: Prisma.UnlockedTalentOrderByWithRelationInput | Prisma.UnlockedTalentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UnlockedTalentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UnlockedTalents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UnlockedTalents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UnlockedTalents
  **/
  _count?: true | UnlockedTalentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UnlockedTalentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UnlockedTalentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UnlockedTalentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UnlockedTalentMaxAggregateInputType
}

export type GetUnlockedTalentAggregateType<T extends UnlockedTalentAggregateArgs> = {
      [P in keyof T & keyof AggregateUnlockedTalent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUnlockedTalent[P]>
    : Prisma.GetScalarType<T[P], AggregateUnlockedTalent[P]>
}




export type UnlockedTalentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UnlockedTalentWhereInput
  orderBy?: Prisma.UnlockedTalentOrderByWithAggregationInput | Prisma.UnlockedTalentOrderByWithAggregationInput[]
  by: Prisma.UnlockedTalentScalarFieldEnum[] | Prisma.UnlockedTalentScalarFieldEnum
  having?: Prisma.UnlockedTalentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UnlockedTalentCountAggregateInputType | true
  _avg?: UnlockedTalentAvgAggregateInputType
  _sum?: UnlockedTalentSumAggregateInputType
  _min?: UnlockedTalentMinAggregateInputType
  _max?: UnlockedTalentMaxAggregateInputType
}

export type UnlockedTalentGroupByOutputType = {
  id: string
  characterId: string
  talentId: string
  unlockedAt: Date
  level: number
  _count: UnlockedTalentCountAggregateOutputType | null
  _avg: UnlockedTalentAvgAggregateOutputType | null
  _sum: UnlockedTalentSumAggregateOutputType | null
  _min: UnlockedTalentMinAggregateOutputType | null
  _max: UnlockedTalentMaxAggregateOutputType | null
}

type GetUnlockedTalentGroupByPayload<T extends UnlockedTalentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UnlockedTalentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UnlockedTalentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UnlockedTalentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UnlockedTalentGroupByOutputType[P]>
      }
    >
  >



export type UnlockedTalentWhereInput = {
  AND?: Prisma.UnlockedTalentWhereInput | Prisma.UnlockedTalentWhereInput[]
  OR?: Prisma.UnlockedTalentWhereInput[]
  NOT?: Prisma.UnlockedTalentWhereInput | Prisma.UnlockedTalentWhereInput[]
  id?: Prisma.StringFilter<"UnlockedTalent"> | string
  characterId?: Prisma.StringFilter<"UnlockedTalent"> | string
  talentId?: Prisma.StringFilter<"UnlockedTalent"> | string
  unlockedAt?: Prisma.DateTimeFilter<"UnlockedTalent"> | Date | string
  level?: Prisma.IntFilter<"UnlockedTalent"> | number
  character?: Prisma.XOR<Prisma.CharacterScalarRelationFilter, Prisma.CharacterWhereInput>
}

export type UnlockedTalentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  talentId?: Prisma.SortOrder
  unlockedAt?: Prisma.SortOrder
  level?: Prisma.SortOrder
  character?: Prisma.CharacterOrderByWithRelationInput
}

export type UnlockedTalentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  characterId_talentId?: Prisma.UnlockedTalentCharacterIdTalentIdCompoundUniqueInput
  AND?: Prisma.UnlockedTalentWhereInput | Prisma.UnlockedTalentWhereInput[]
  OR?: Prisma.UnlockedTalentWhereInput[]
  NOT?: Prisma.UnlockedTalentWhereInput | Prisma.UnlockedTalentWhereInput[]
  characterId?: Prisma.StringFilter<"UnlockedTalent"> | string
  talentId?: Prisma.StringFilter<"UnlockedTalent"> | string
  unlockedAt?: Prisma.DateTimeFilter<"UnlockedTalent"> | Date | string
  level?: Prisma.IntFilter<"UnlockedTalent"> | number
  character?: Prisma.XOR<Prisma.CharacterScalarRelationFilter, Prisma.CharacterWhereInput>
}, "id" | "characterId_talentId">

export type UnlockedTalentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  talentId?: Prisma.SortOrder
  unlockedAt?: Prisma.SortOrder
  level?: Prisma.SortOrder
  _count?: Prisma.UnlockedTalentCountOrderByAggregateInput
  _avg?: Prisma.UnlockedTalentAvgOrderByAggregateInput
  _max?: Prisma.UnlockedTalentMaxOrderByAggregateInput
  _min?: Prisma.UnlockedTalentMinOrderByAggregateInput
  _sum?: Prisma.UnlockedTalentSumOrderByAggregateInput
}

export type UnlockedTalentScalarWhereWithAggregatesInput = {
  AND?: Prisma.UnlockedTalentScalarWhereWithAggregatesInput | Prisma.UnlockedTalentScalarWhereWithAggregatesInput[]
  OR?: Prisma.UnlockedTalentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UnlockedTalentScalarWhereWithAggregatesInput | Prisma.UnlockedTalentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"UnlockedTalent"> | string
  characterId?: Prisma.StringWithAggregatesFilter<"UnlockedTalent"> | string
  talentId?: Prisma.StringWithAggregatesFilter<"UnlockedTalent"> | string
  unlockedAt?: Prisma.DateTimeWithAggregatesFilter<"UnlockedTalent"> | Date | string
  level?: Prisma.IntWithAggregatesFilter<"UnlockedTalent"> | number
}

export type UnlockedTalentCreateInput = {
  id?: string
  talentId: string
  unlockedAt?: Date | string
  level?: number
  character: Prisma.CharacterCreateNestedOneWithoutTalentsInput
}

export type UnlockedTalentUncheckedCreateInput = {
  id?: string
  characterId: string
  talentId: string
  unlockedAt?: Date | string
  level?: number
}

export type UnlockedTalentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  talentId?: Prisma.StringFieldUpdateOperationsInput | string
  unlockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  character?: Prisma.CharacterUpdateOneRequiredWithoutTalentsNestedInput
}

export type UnlockedTalentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  characterId?: Prisma.StringFieldUpdateOperationsInput | string
  talentId?: Prisma.StringFieldUpdateOperationsInput | string
  unlockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UnlockedTalentCreateManyInput = {
  id?: string
  characterId: string
  talentId: string
  unlockedAt?: Date | string
  level?: number
}

export type UnlockedTalentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  talentId?: Prisma.StringFieldUpdateOperationsInput | string
  unlockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UnlockedTalentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  characterId?: Prisma.StringFieldUpdateOperationsInput | string
  talentId?: Prisma.StringFieldUpdateOperationsInput | string
  unlockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UnlockedTalentListRelationFilter = {
  every?: Prisma.UnlockedTalentWhereInput
  some?: Prisma.UnlockedTalentWhereInput
  none?: Prisma.UnlockedTalentWhereInput
}

export type UnlockedTalentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UnlockedTalentCharacterIdTalentIdCompoundUniqueInput = {
  characterId: string
  talentId: string
}

export type UnlockedTalentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  talentId?: Prisma.SortOrder
  unlockedAt?: Prisma.SortOrder
  level?: Prisma.SortOrder
}

export type UnlockedTalentAvgOrderByAggregateInput = {
  level?: Prisma.SortOrder
}

export type UnlockedTalentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  talentId?: Prisma.SortOrder
  unlockedAt?: Prisma.SortOrder
  level?: Prisma.SortOrder
}

export type UnlockedTalentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  characterId?: Prisma.SortOrder
  talentId?: Prisma.SortOrder
  unlockedAt?: Prisma.SortOrder
  level?: Prisma.SortOrder
}

export type UnlockedTalentSumOrderByAggregateInput = {
  level?: Prisma.SortOrder
}

export type UnlockedTalentCreateNestedManyWithoutCharacterInput = {
  create?: Prisma.XOR<Prisma.UnlockedTalentCreateWithoutCharacterInput, Prisma.UnlockedTalentUncheckedCreateWithoutCharacterInput> | Prisma.UnlockedTalentCreateWithoutCharacterInput[] | Prisma.UnlockedTalentUncheckedCreateWithoutCharacterInput[]
  connectOrCreate?: Prisma.UnlockedTalentCreateOrConnectWithoutCharacterInput | Prisma.UnlockedTalentCreateOrConnectWithoutCharacterInput[]
  createMany?: Prisma.UnlockedTalentCreateManyCharacterInputEnvelope
  connect?: Prisma.UnlockedTalentWhereUniqueInput | Prisma.UnlockedTalentWhereUniqueInput[]
}

export type UnlockedTalentUncheckedCreateNestedManyWithoutCharacterInput = {
  create?: Prisma.XOR<Prisma.UnlockedTalentCreateWithoutCharacterInput, Prisma.UnlockedTalentUncheckedCreateWithoutCharacterInput> | Prisma.UnlockedTalentCreateWithoutCharacterInput[] | Prisma.UnlockedTalentUncheckedCreateWithoutCharacterInput[]
  connectOrCreate?: Prisma.UnlockedTalentCreateOrConnectWithoutCharacterInput | Prisma.UnlockedTalentCreateOrConnectWithoutCharacterInput[]
  createMany?: Prisma.UnlockedTalentCreateManyCharacterInputEnvelope
  connect?: Prisma.UnlockedTalentWhereUniqueInput | Prisma.UnlockedTalentWhereUniqueInput[]
}

export type UnlockedTalentUpdateManyWithoutCharacterNestedInput = {
  create?: Prisma.XOR<Prisma.UnlockedTalentCreateWithoutCharacterInput, Prisma.UnlockedTalentUncheckedCreateWithoutCharacterInput> | Prisma.UnlockedTalentCreateWithoutCharacterInput[] | Prisma.UnlockedTalentUncheckedCreateWithoutCharacterInput[]
  connectOrCreate?: Prisma.UnlockedTalentCreateOrConnectWithoutCharacterInput | Prisma.UnlockedTalentCreateOrConnectWithoutCharacterInput[]
  upsert?: Prisma.UnlockedTalentUpsertWithWhereUniqueWithoutCharacterInput | Prisma.UnlockedTalentUpsertWithWhereUniqueWithoutCharacterInput[]
  createMany?: Prisma.UnlockedTalentCreateManyCharacterInputEnvelope
  set?: Prisma.UnlockedTalentWhereUniqueInput | Prisma.UnlockedTalentWhereUniqueInput[]
  disconnect?: Prisma.UnlockedTalentWhereUniqueInput | Prisma.UnlockedTalentWhereUniqueInput[]
  delete?: Prisma.UnlockedTalentWhereUniqueInput | Prisma.UnlockedTalentWhereUniqueInput[]
  connect?: Prisma.UnlockedTalentWhereUniqueInput | Prisma.UnlockedTalentWhereUniqueInput[]
  update?: Prisma.UnlockedTalentUpdateWithWhereUniqueWithoutCharacterInput | Prisma.UnlockedTalentUpdateWithWhereUniqueWithoutCharacterInput[]
  updateMany?: Prisma.UnlockedTalentUpdateManyWithWhereWithoutCharacterInput | Prisma.UnlockedTalentUpdateManyWithWhereWithoutCharacterInput[]
  deleteMany?: Prisma.UnlockedTalentScalarWhereInput | Prisma.UnlockedTalentScalarWhereInput[]
}

export type UnlockedTalentUncheckedUpdateManyWithoutCharacterNestedInput = {
  create?: Prisma.XOR<Prisma.UnlockedTalentCreateWithoutCharacterInput, Prisma.UnlockedTalentUncheckedCreateWithoutCharacterInput> | Prisma.UnlockedTalentCreateWithoutCharacterInput[] | Prisma.UnlockedTalentUncheckedCreateWithoutCharacterInput[]
  connectOrCreate?: Prisma.UnlockedTalentCreateOrConnectWithoutCharacterInput | Prisma.UnlockedTalentCreateOrConnectWithoutCharacterInput[]
  upsert?: Prisma.UnlockedTalentUpsertWithWhereUniqueWithoutCharacterInput | Prisma.UnlockedTalentUpsertWithWhereUniqueWithoutCharacterInput[]
  createMany?: Prisma.UnlockedTalentCreateManyCharacterInputEnvelope
  set?: Prisma.UnlockedTalentWhereUniqueInput | Prisma.UnlockedTalentWhereUniqueInput[]
  disconnect?: Prisma.UnlockedTalentWhereUniqueInput | Prisma.UnlockedTalentWhereUniqueInput[]
  delete?: Prisma.UnlockedTalentWhereUniqueInput | Prisma.UnlockedTalentWhereUniqueInput[]
  connect?: Prisma.UnlockedTalentWhereUniqueInput | Prisma.UnlockedTalentWhereUniqueInput[]
  update?: Prisma.UnlockedTalentUpdateWithWhereUniqueWithoutCharacterInput | Prisma.UnlockedTalentUpdateWithWhereUniqueWithoutCharacterInput[]
  updateMany?: Prisma.UnlockedTalentUpdateManyWithWhereWithoutCharacterInput | Prisma.UnlockedTalentUpdateManyWithWhereWithoutCharacterInput[]
  deleteMany?: Prisma.UnlockedTalentScalarWhereInput | Prisma.UnlockedTalentScalarWhereInput[]
}

export type UnlockedTalentCreateWithoutCharacterInput = {
  id?: string
  talentId: string
  unlockedAt?: Date | string
  level?: number
}

export type UnlockedTalentUncheckedCreateWithoutCharacterInput = {
  id?: string
  talentId: string
  unlockedAt?: Date | string
  level?: number
}

export type UnlockedTalentCreateOrConnectWithoutCharacterInput = {
  where: Prisma.UnlockedTalentWhereUniqueInput
  create: Prisma.XOR<Prisma.UnlockedTalentCreateWithoutCharacterInput, Prisma.UnlockedTalentUncheckedCreateWithoutCharacterInput>
}

export type UnlockedTalentCreateManyCharacterInputEnvelope = {
  data: Prisma.UnlockedTalentCreateManyCharacterInput | Prisma.UnlockedTalentCreateManyCharacterInput[]
}

export type UnlockedTalentUpsertWithWhereUniqueWithoutCharacterInput = {
  where: Prisma.UnlockedTalentWhereUniqueInput
  update: Prisma.XOR<Prisma.UnlockedTalentUpdateWithoutCharacterInput, Prisma.UnlockedTalentUncheckedUpdateWithoutCharacterInput>
  create: Prisma.XOR<Prisma.UnlockedTalentCreateWithoutCharacterInput, Prisma.UnlockedTalentUncheckedCreateWithoutCharacterInput>
}

export type UnlockedTalentUpdateWithWhereUniqueWithoutCharacterInput = {
  where: Prisma.UnlockedTalentWhereUniqueInput
  data: Prisma.XOR<Prisma.UnlockedTalentUpdateWithoutCharacterInput, Prisma.UnlockedTalentUncheckedUpdateWithoutCharacterInput>
}

export type UnlockedTalentUpdateManyWithWhereWithoutCharacterInput = {
  where: Prisma.UnlockedTalentScalarWhereInput
  data: Prisma.XOR<Prisma.UnlockedTalentUpdateManyMutationInput, Prisma.UnlockedTalentUncheckedUpdateManyWithoutCharacterInput>
}

export type UnlockedTalentScalarWhereInput = {
  AND?: Prisma.UnlockedTalentScalarWhereInput | Prisma.UnlockedTalentScalarWhereInput[]
  OR?: Prisma.UnlockedTalentScalarWhereInput[]
  NOT?: Prisma.UnlockedTalentScalarWhereInput | Prisma.UnlockedTalentScalarWhereInput[]
  id?: Prisma.StringFilter<"UnlockedTalent"> | string
  characterId?: Prisma.StringFilter<"UnlockedTalent"> | string
  talentId?: Prisma.StringFilter<"UnlockedTalent"> | string
  unlockedAt?: Prisma.DateTimeFilter<"UnlockedTalent"> | Date | string
  level?: Prisma.IntFilter<"UnlockedTalent"> | number
}

export type UnlockedTalentCreateManyCharacterInput = {
  id?: string
  talentId: string
  unlockedAt?: Date | string
  level?: number
}

export type UnlockedTalentUpdateWithoutCharacterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  talentId?: Prisma.StringFieldUpdateOperationsInput | string
  unlockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UnlockedTalentUncheckedUpdateWithoutCharacterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  talentId?: Prisma.StringFieldUpdateOperationsInput | string
  unlockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UnlockedTalentUncheckedUpdateManyWithoutCharacterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  talentId?: Prisma.StringFieldUpdateOperationsInput | string
  unlockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
}



export type UnlockedTalentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  characterId?: boolean
  talentId?: boolean
  unlockedAt?: boolean
  level?: boolean
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["unlockedTalent"]>

export type UnlockedTalentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  characterId?: boolean
  talentId?: boolean
  unlockedAt?: boolean
  level?: boolean
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["unlockedTalent"]>

export type UnlockedTalentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  characterId?: boolean
  talentId?: boolean
  unlockedAt?: boolean
  level?: boolean
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["unlockedTalent"]>

export type UnlockedTalentSelectScalar = {
  id?: boolean
  characterId?: boolean
  talentId?: boolean
  unlockedAt?: boolean
  level?: boolean
}

export type UnlockedTalentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "characterId" | "talentId" | "unlockedAt" | "level", ExtArgs["result"]["unlockedTalent"]>
export type UnlockedTalentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}
export type UnlockedTalentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}
export type UnlockedTalentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  character?: boolean | Prisma.CharacterDefaultArgs<ExtArgs>
}

export type $UnlockedTalentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UnlockedTalent"
  objects: {
    character: Prisma.$CharacterPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    characterId: string
    talentId: string
    unlockedAt: Date
    level: number
  }, ExtArgs["result"]["unlockedTalent"]>
  composites: {}
}

export type UnlockedTalentGetPayload<S extends boolean | null | undefined | UnlockedTalentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UnlockedTalentPayload, S>

export type UnlockedTalentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UnlockedTalentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UnlockedTalentCountAggregateInputType | true
  }

export interface UnlockedTalentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UnlockedTalent'], meta: { name: 'UnlockedTalent' } }
  /**
   * Find zero or one UnlockedTalent that matches the filter.
   * @param {UnlockedTalentFindUniqueArgs} args - Arguments to find a UnlockedTalent
   * @example
   * // Get one UnlockedTalent
   * const unlockedTalent = await prisma.unlockedTalent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UnlockedTalentFindUniqueArgs>(args: Prisma.SelectSubset<T, UnlockedTalentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UnlockedTalentClient<runtime.Types.Result.GetResult<Prisma.$UnlockedTalentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UnlockedTalent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UnlockedTalentFindUniqueOrThrowArgs} args - Arguments to find a UnlockedTalent
   * @example
   * // Get one UnlockedTalent
   * const unlockedTalent = await prisma.unlockedTalent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UnlockedTalentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UnlockedTalentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UnlockedTalentClient<runtime.Types.Result.GetResult<Prisma.$UnlockedTalentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UnlockedTalent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnlockedTalentFindFirstArgs} args - Arguments to find a UnlockedTalent
   * @example
   * // Get one UnlockedTalent
   * const unlockedTalent = await prisma.unlockedTalent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UnlockedTalentFindFirstArgs>(args?: Prisma.SelectSubset<T, UnlockedTalentFindFirstArgs<ExtArgs>>): Prisma.Prisma__UnlockedTalentClient<runtime.Types.Result.GetResult<Prisma.$UnlockedTalentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UnlockedTalent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnlockedTalentFindFirstOrThrowArgs} args - Arguments to find a UnlockedTalent
   * @example
   * // Get one UnlockedTalent
   * const unlockedTalent = await prisma.unlockedTalent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UnlockedTalentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UnlockedTalentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UnlockedTalentClient<runtime.Types.Result.GetResult<Prisma.$UnlockedTalentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UnlockedTalents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnlockedTalentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UnlockedTalents
   * const unlockedTalents = await prisma.unlockedTalent.findMany()
   * 
   * // Get first 10 UnlockedTalents
   * const unlockedTalents = await prisma.unlockedTalent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const unlockedTalentWithIdOnly = await prisma.unlockedTalent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UnlockedTalentFindManyArgs>(args?: Prisma.SelectSubset<T, UnlockedTalentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnlockedTalentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UnlockedTalent.
   * @param {UnlockedTalentCreateArgs} args - Arguments to create a UnlockedTalent.
   * @example
   * // Create one UnlockedTalent
   * const UnlockedTalent = await prisma.unlockedTalent.create({
   *   data: {
   *     // ... data to create a UnlockedTalent
   *   }
   * })
   * 
   */
  create<T extends UnlockedTalentCreateArgs>(args: Prisma.SelectSubset<T, UnlockedTalentCreateArgs<ExtArgs>>): Prisma.Prisma__UnlockedTalentClient<runtime.Types.Result.GetResult<Prisma.$UnlockedTalentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UnlockedTalents.
   * @param {UnlockedTalentCreateManyArgs} args - Arguments to create many UnlockedTalents.
   * @example
   * // Create many UnlockedTalents
   * const unlockedTalent = await prisma.unlockedTalent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UnlockedTalentCreateManyArgs>(args?: Prisma.SelectSubset<T, UnlockedTalentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UnlockedTalents and returns the data saved in the database.
   * @param {UnlockedTalentCreateManyAndReturnArgs} args - Arguments to create many UnlockedTalents.
   * @example
   * // Create many UnlockedTalents
   * const unlockedTalent = await prisma.unlockedTalent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UnlockedTalents and only return the `id`
   * const unlockedTalentWithIdOnly = await prisma.unlockedTalent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UnlockedTalentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UnlockedTalentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnlockedTalentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UnlockedTalent.
   * @param {UnlockedTalentDeleteArgs} args - Arguments to delete one UnlockedTalent.
   * @example
   * // Delete one UnlockedTalent
   * const UnlockedTalent = await prisma.unlockedTalent.delete({
   *   where: {
   *     // ... filter to delete one UnlockedTalent
   *   }
   * })
   * 
   */
  delete<T extends UnlockedTalentDeleteArgs>(args: Prisma.SelectSubset<T, UnlockedTalentDeleteArgs<ExtArgs>>): Prisma.Prisma__UnlockedTalentClient<runtime.Types.Result.GetResult<Prisma.$UnlockedTalentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UnlockedTalent.
   * @param {UnlockedTalentUpdateArgs} args - Arguments to update one UnlockedTalent.
   * @example
   * // Update one UnlockedTalent
   * const unlockedTalent = await prisma.unlockedTalent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UnlockedTalentUpdateArgs>(args: Prisma.SelectSubset<T, UnlockedTalentUpdateArgs<ExtArgs>>): Prisma.Prisma__UnlockedTalentClient<runtime.Types.Result.GetResult<Prisma.$UnlockedTalentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UnlockedTalents.
   * @param {UnlockedTalentDeleteManyArgs} args - Arguments to filter UnlockedTalents to delete.
   * @example
   * // Delete a few UnlockedTalents
   * const { count } = await prisma.unlockedTalent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UnlockedTalentDeleteManyArgs>(args?: Prisma.SelectSubset<T, UnlockedTalentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UnlockedTalents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnlockedTalentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UnlockedTalents
   * const unlockedTalent = await prisma.unlockedTalent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UnlockedTalentUpdateManyArgs>(args: Prisma.SelectSubset<T, UnlockedTalentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UnlockedTalents and returns the data updated in the database.
   * @param {UnlockedTalentUpdateManyAndReturnArgs} args - Arguments to update many UnlockedTalents.
   * @example
   * // Update many UnlockedTalents
   * const unlockedTalent = await prisma.unlockedTalent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UnlockedTalents and only return the `id`
   * const unlockedTalentWithIdOnly = await prisma.unlockedTalent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UnlockedTalentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UnlockedTalentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnlockedTalentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UnlockedTalent.
   * @param {UnlockedTalentUpsertArgs} args - Arguments to update or create a UnlockedTalent.
   * @example
   * // Update or create a UnlockedTalent
   * const unlockedTalent = await prisma.unlockedTalent.upsert({
   *   create: {
   *     // ... data to create a UnlockedTalent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UnlockedTalent we want to update
   *   }
   * })
   */
  upsert<T extends UnlockedTalentUpsertArgs>(args: Prisma.SelectSubset<T, UnlockedTalentUpsertArgs<ExtArgs>>): Prisma.Prisma__UnlockedTalentClient<runtime.Types.Result.GetResult<Prisma.$UnlockedTalentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UnlockedTalents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnlockedTalentCountArgs} args - Arguments to filter UnlockedTalents to count.
   * @example
   * // Count the number of UnlockedTalents
   * const count = await prisma.unlockedTalent.count({
   *   where: {
   *     // ... the filter for the UnlockedTalents we want to count
   *   }
   * })
  **/
  count<T extends UnlockedTalentCountArgs>(
    args?: Prisma.Subset<T, UnlockedTalentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UnlockedTalentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UnlockedTalent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnlockedTalentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UnlockedTalentAggregateArgs>(args: Prisma.Subset<T, UnlockedTalentAggregateArgs>): Prisma.PrismaPromise<GetUnlockedTalentAggregateType<T>>

  /**
   * Group by UnlockedTalent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnlockedTalentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UnlockedTalentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UnlockedTalentGroupByArgs['orderBy'] }
      : { orderBy?: UnlockedTalentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UnlockedTalentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUnlockedTalentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UnlockedTalent model
 */
readonly fields: UnlockedTalentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UnlockedTalent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UnlockedTalentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  character<T extends Prisma.CharacterDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CharacterDefaultArgs<ExtArgs>>): Prisma.Prisma__CharacterClient<runtime.Types.Result.GetResult<Prisma.$CharacterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UnlockedTalent model
 */
export interface UnlockedTalentFieldRefs {
  readonly id: Prisma.FieldRef<"UnlockedTalent", 'String'>
  readonly characterId: Prisma.FieldRef<"UnlockedTalent", 'String'>
  readonly talentId: Prisma.FieldRef<"UnlockedTalent", 'String'>
  readonly unlockedAt: Prisma.FieldRef<"UnlockedTalent", 'DateTime'>
  readonly level: Prisma.FieldRef<"UnlockedTalent", 'Int'>
}
    

// Custom InputTypes
/**
 * UnlockedTalent findUnique
 */
export type UnlockedTalentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedTalent
   */
  select?: Prisma.UnlockedTalentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedTalent
   */
  omit?: Prisma.UnlockedTalentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedTalentInclude<ExtArgs> | null
  /**
   * Filter, which UnlockedTalent to fetch.
   */
  where: Prisma.UnlockedTalentWhereUniqueInput
}

/**
 * UnlockedTalent findUniqueOrThrow
 */
export type UnlockedTalentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedTalent
   */
  select?: Prisma.UnlockedTalentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedTalent
   */
  omit?: Prisma.UnlockedTalentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedTalentInclude<ExtArgs> | null
  /**
   * Filter, which UnlockedTalent to fetch.
   */
  where: Prisma.UnlockedTalentWhereUniqueInput
}

/**
 * UnlockedTalent findFirst
 */
export type UnlockedTalentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedTalent
   */
  select?: Prisma.UnlockedTalentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedTalent
   */
  omit?: Prisma.UnlockedTalentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedTalentInclude<ExtArgs> | null
  /**
   * Filter, which UnlockedTalent to fetch.
   */
  where?: Prisma.UnlockedTalentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UnlockedTalents to fetch.
   */
  orderBy?: Prisma.UnlockedTalentOrderByWithRelationInput | Prisma.UnlockedTalentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UnlockedTalents.
   */
  cursor?: Prisma.UnlockedTalentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UnlockedTalents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UnlockedTalents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UnlockedTalents.
   */
  distinct?: Prisma.UnlockedTalentScalarFieldEnum | Prisma.UnlockedTalentScalarFieldEnum[]
}

/**
 * UnlockedTalent findFirstOrThrow
 */
export type UnlockedTalentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedTalent
   */
  select?: Prisma.UnlockedTalentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedTalent
   */
  omit?: Prisma.UnlockedTalentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedTalentInclude<ExtArgs> | null
  /**
   * Filter, which UnlockedTalent to fetch.
   */
  where?: Prisma.UnlockedTalentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UnlockedTalents to fetch.
   */
  orderBy?: Prisma.UnlockedTalentOrderByWithRelationInput | Prisma.UnlockedTalentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UnlockedTalents.
   */
  cursor?: Prisma.UnlockedTalentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UnlockedTalents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UnlockedTalents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UnlockedTalents.
   */
  distinct?: Prisma.UnlockedTalentScalarFieldEnum | Prisma.UnlockedTalentScalarFieldEnum[]
}

/**
 * UnlockedTalent findMany
 */
export type UnlockedTalentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedTalent
   */
  select?: Prisma.UnlockedTalentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedTalent
   */
  omit?: Prisma.UnlockedTalentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedTalentInclude<ExtArgs> | null
  /**
   * Filter, which UnlockedTalents to fetch.
   */
  where?: Prisma.UnlockedTalentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UnlockedTalents to fetch.
   */
  orderBy?: Prisma.UnlockedTalentOrderByWithRelationInput | Prisma.UnlockedTalentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UnlockedTalents.
   */
  cursor?: Prisma.UnlockedTalentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UnlockedTalents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UnlockedTalents.
   */
  skip?: number
  distinct?: Prisma.UnlockedTalentScalarFieldEnum | Prisma.UnlockedTalentScalarFieldEnum[]
}

/**
 * UnlockedTalent create
 */
export type UnlockedTalentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedTalent
   */
  select?: Prisma.UnlockedTalentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedTalent
   */
  omit?: Prisma.UnlockedTalentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedTalentInclude<ExtArgs> | null
  /**
   * The data needed to create a UnlockedTalent.
   */
  data: Prisma.XOR<Prisma.UnlockedTalentCreateInput, Prisma.UnlockedTalentUncheckedCreateInput>
}

/**
 * UnlockedTalent createMany
 */
export type UnlockedTalentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UnlockedTalents.
   */
  data: Prisma.UnlockedTalentCreateManyInput | Prisma.UnlockedTalentCreateManyInput[]
}

/**
 * UnlockedTalent createManyAndReturn
 */
export type UnlockedTalentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedTalent
   */
  select?: Prisma.UnlockedTalentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedTalent
   */
  omit?: Prisma.UnlockedTalentOmit<ExtArgs> | null
  /**
   * The data used to create many UnlockedTalents.
   */
  data: Prisma.UnlockedTalentCreateManyInput | Prisma.UnlockedTalentCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedTalentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UnlockedTalent update
 */
export type UnlockedTalentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedTalent
   */
  select?: Prisma.UnlockedTalentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedTalent
   */
  omit?: Prisma.UnlockedTalentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedTalentInclude<ExtArgs> | null
  /**
   * The data needed to update a UnlockedTalent.
   */
  data: Prisma.XOR<Prisma.UnlockedTalentUpdateInput, Prisma.UnlockedTalentUncheckedUpdateInput>
  /**
   * Choose, which UnlockedTalent to update.
   */
  where: Prisma.UnlockedTalentWhereUniqueInput
}

/**
 * UnlockedTalent updateMany
 */
export type UnlockedTalentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UnlockedTalents.
   */
  data: Prisma.XOR<Prisma.UnlockedTalentUpdateManyMutationInput, Prisma.UnlockedTalentUncheckedUpdateManyInput>
  /**
   * Filter which UnlockedTalents to update
   */
  where?: Prisma.UnlockedTalentWhereInput
  /**
   * Limit how many UnlockedTalents to update.
   */
  limit?: number
}

/**
 * UnlockedTalent updateManyAndReturn
 */
export type UnlockedTalentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedTalent
   */
  select?: Prisma.UnlockedTalentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedTalent
   */
  omit?: Prisma.UnlockedTalentOmit<ExtArgs> | null
  /**
   * The data used to update UnlockedTalents.
   */
  data: Prisma.XOR<Prisma.UnlockedTalentUpdateManyMutationInput, Prisma.UnlockedTalentUncheckedUpdateManyInput>
  /**
   * Filter which UnlockedTalents to update
   */
  where?: Prisma.UnlockedTalentWhereInput
  /**
   * Limit how many UnlockedTalents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedTalentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UnlockedTalent upsert
 */
export type UnlockedTalentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedTalent
   */
  select?: Prisma.UnlockedTalentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedTalent
   */
  omit?: Prisma.UnlockedTalentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedTalentInclude<ExtArgs> | null
  /**
   * The filter to search for the UnlockedTalent to update in case it exists.
   */
  where: Prisma.UnlockedTalentWhereUniqueInput
  /**
   * In case the UnlockedTalent found by the `where` argument doesn't exist, create a new UnlockedTalent with this data.
   */
  create: Prisma.XOR<Prisma.UnlockedTalentCreateInput, Prisma.UnlockedTalentUncheckedCreateInput>
  /**
   * In case the UnlockedTalent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UnlockedTalentUpdateInput, Prisma.UnlockedTalentUncheckedUpdateInput>
}

/**
 * UnlockedTalent delete
 */
export type UnlockedTalentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedTalent
   */
  select?: Prisma.UnlockedTalentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedTalent
   */
  omit?: Prisma.UnlockedTalentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedTalentInclude<ExtArgs> | null
  /**
   * Filter which UnlockedTalent to delete.
   */
  where: Prisma.UnlockedTalentWhereUniqueInput
}

/**
 * UnlockedTalent deleteMany
 */
export type UnlockedTalentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UnlockedTalents to delete
   */
  where?: Prisma.UnlockedTalentWhereInput
  /**
   * Limit how many UnlockedTalents to delete.
   */
  limit?: number
}

/**
 * UnlockedTalent without action
 */
export type UnlockedTalentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedTalent
   */
  select?: Prisma.UnlockedTalentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedTalent
   */
  omit?: Prisma.UnlockedTalentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedTalentInclude<ExtArgs> | null
}
