
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models.js"
import { type PrismaClient } from "./class.js"

export type * from '../models.js'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.3.0
 * Query Engine version: 9d6ad21cbbceab97458517b147a6a09ff43aa735
 */
export const prismaVersion: PrismaVersion = {
  client: "7.3.0",
  engine: "9d6ad21cbbceab97458517b147a6a09ff43aa735"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  Character: 'Character',
  CultureSelection: 'CultureSelection',
  PathSelection: 'PathSelection',
  Attributes: 'Attributes',
  Skill: 'Skill',
  UnlockedTalent: 'UnlockedTalent',
  SelectedExpertise: 'SelectedExpertise',
  InventoryItem: 'InventoryItem',
  CharacterResources: 'CharacterResources',
  RadiantPath: 'RadiantPath',
  UnlockedSingerForm: 'UnlockedSingerForm',
  SpentPoints: 'SpentPoints'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "character" | "cultureSelection" | "pathSelection" | "attributes" | "skill" | "unlockedTalent" | "selectedExpertise" | "inventoryItem" | "characterResources" | "radiantPath" | "unlockedSingerForm" | "spentPoints"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    Character: {
      payload: Prisma.$CharacterPayload<ExtArgs>
      fields: Prisma.CharacterFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CharacterFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CharacterPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CharacterFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CharacterPayload>
        }
        findFirst: {
          args: Prisma.CharacterFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CharacterPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CharacterFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CharacterPayload>
        }
        findMany: {
          args: Prisma.CharacterFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CharacterPayload>[]
        }
        create: {
          args: Prisma.CharacterCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CharacterPayload>
        }
        createMany: {
          args: Prisma.CharacterCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CharacterCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CharacterPayload>[]
        }
        delete: {
          args: Prisma.CharacterDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CharacterPayload>
        }
        update: {
          args: Prisma.CharacterUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CharacterPayload>
        }
        deleteMany: {
          args: Prisma.CharacterDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CharacterUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CharacterUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CharacterPayload>[]
        }
        upsert: {
          args: Prisma.CharacterUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CharacterPayload>
        }
        aggregate: {
          args: Prisma.CharacterAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCharacter>
        }
        groupBy: {
          args: Prisma.CharacterGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CharacterGroupByOutputType>[]
        }
        count: {
          args: Prisma.CharacterCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CharacterCountAggregateOutputType> | number
        }
      }
    }
    CultureSelection: {
      payload: Prisma.$CultureSelectionPayload<ExtArgs>
      fields: Prisma.CultureSelectionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CultureSelectionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CultureSelectionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CultureSelectionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CultureSelectionPayload>
        }
        findFirst: {
          args: Prisma.CultureSelectionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CultureSelectionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CultureSelectionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CultureSelectionPayload>
        }
        findMany: {
          args: Prisma.CultureSelectionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CultureSelectionPayload>[]
        }
        create: {
          args: Prisma.CultureSelectionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CultureSelectionPayload>
        }
        createMany: {
          args: Prisma.CultureSelectionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CultureSelectionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CultureSelectionPayload>[]
        }
        delete: {
          args: Prisma.CultureSelectionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CultureSelectionPayload>
        }
        update: {
          args: Prisma.CultureSelectionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CultureSelectionPayload>
        }
        deleteMany: {
          args: Prisma.CultureSelectionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CultureSelectionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CultureSelectionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CultureSelectionPayload>[]
        }
        upsert: {
          args: Prisma.CultureSelectionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CultureSelectionPayload>
        }
        aggregate: {
          args: Prisma.CultureSelectionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCultureSelection>
        }
        groupBy: {
          args: Prisma.CultureSelectionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CultureSelectionGroupByOutputType>[]
        }
        count: {
          args: Prisma.CultureSelectionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CultureSelectionCountAggregateOutputType> | number
        }
      }
    }
    PathSelection: {
      payload: Prisma.$PathSelectionPayload<ExtArgs>
      fields: Prisma.PathSelectionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.PathSelectionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PathSelectionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.PathSelectionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PathSelectionPayload>
        }
        findFirst: {
          args: Prisma.PathSelectionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PathSelectionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.PathSelectionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PathSelectionPayload>
        }
        findMany: {
          args: Prisma.PathSelectionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PathSelectionPayload>[]
        }
        create: {
          args: Prisma.PathSelectionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PathSelectionPayload>
        }
        createMany: {
          args: Prisma.PathSelectionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.PathSelectionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PathSelectionPayload>[]
        }
        delete: {
          args: Prisma.PathSelectionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PathSelectionPayload>
        }
        update: {
          args: Prisma.PathSelectionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PathSelectionPayload>
        }
        deleteMany: {
          args: Prisma.PathSelectionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.PathSelectionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.PathSelectionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PathSelectionPayload>[]
        }
        upsert: {
          args: Prisma.PathSelectionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PathSelectionPayload>
        }
        aggregate: {
          args: Prisma.PathSelectionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregatePathSelection>
        }
        groupBy: {
          args: Prisma.PathSelectionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PathSelectionGroupByOutputType>[]
        }
        count: {
          args: Prisma.PathSelectionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PathSelectionCountAggregateOutputType> | number
        }
      }
    }
    Attributes: {
      payload: Prisma.$AttributesPayload<ExtArgs>
      fields: Prisma.AttributesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AttributesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttributesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AttributesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttributesPayload>
        }
        findFirst: {
          args: Prisma.AttributesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttributesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AttributesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttributesPayload>
        }
        findMany: {
          args: Prisma.AttributesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttributesPayload>[]
        }
        create: {
          args: Prisma.AttributesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttributesPayload>
        }
        createMany: {
          args: Prisma.AttributesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AttributesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttributesPayload>[]
        }
        delete: {
          args: Prisma.AttributesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttributesPayload>
        }
        update: {
          args: Prisma.AttributesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttributesPayload>
        }
        deleteMany: {
          args: Prisma.AttributesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AttributesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AttributesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttributesPayload>[]
        }
        upsert: {
          args: Prisma.AttributesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttributesPayload>
        }
        aggregate: {
          args: Prisma.AttributesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAttributes>
        }
        groupBy: {
          args: Prisma.AttributesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AttributesGroupByOutputType>[]
        }
        count: {
          args: Prisma.AttributesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AttributesCountAggregateOutputType> | number
        }
      }
    }
    Skill: {
      payload: Prisma.$SkillPayload<ExtArgs>
      fields: Prisma.SkillFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SkillFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SkillPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SkillFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SkillPayload>
        }
        findFirst: {
          args: Prisma.SkillFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SkillPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SkillFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SkillPayload>
        }
        findMany: {
          args: Prisma.SkillFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SkillPayload>[]
        }
        create: {
          args: Prisma.SkillCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SkillPayload>
        }
        createMany: {
          args: Prisma.SkillCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SkillCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SkillPayload>[]
        }
        delete: {
          args: Prisma.SkillDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SkillPayload>
        }
        update: {
          args: Prisma.SkillUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SkillPayload>
        }
        deleteMany: {
          args: Prisma.SkillDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SkillUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SkillUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SkillPayload>[]
        }
        upsert: {
          args: Prisma.SkillUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SkillPayload>
        }
        aggregate: {
          args: Prisma.SkillAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSkill>
        }
        groupBy: {
          args: Prisma.SkillGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SkillGroupByOutputType>[]
        }
        count: {
          args: Prisma.SkillCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SkillCountAggregateOutputType> | number
        }
      }
    }
    UnlockedTalent: {
      payload: Prisma.$UnlockedTalentPayload<ExtArgs>
      fields: Prisma.UnlockedTalentFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UnlockedTalentFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnlockedTalentPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UnlockedTalentFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnlockedTalentPayload>
        }
        findFirst: {
          args: Prisma.UnlockedTalentFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnlockedTalentPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UnlockedTalentFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnlockedTalentPayload>
        }
        findMany: {
          args: Prisma.UnlockedTalentFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnlockedTalentPayload>[]
        }
        create: {
          args: Prisma.UnlockedTalentCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnlockedTalentPayload>
        }
        createMany: {
          args: Prisma.UnlockedTalentCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UnlockedTalentCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnlockedTalentPayload>[]
        }
        delete: {
          args: Prisma.UnlockedTalentDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnlockedTalentPayload>
        }
        update: {
          args: Prisma.UnlockedTalentUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnlockedTalentPayload>
        }
        deleteMany: {
          args: Prisma.UnlockedTalentDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UnlockedTalentUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UnlockedTalentUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnlockedTalentPayload>[]
        }
        upsert: {
          args: Prisma.UnlockedTalentUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnlockedTalentPayload>
        }
        aggregate: {
          args: Prisma.UnlockedTalentAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUnlockedTalent>
        }
        groupBy: {
          args: Prisma.UnlockedTalentGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UnlockedTalentGroupByOutputType>[]
        }
        count: {
          args: Prisma.UnlockedTalentCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UnlockedTalentCountAggregateOutputType> | number
        }
      }
    }
    SelectedExpertise: {
      payload: Prisma.$SelectedExpertisePayload<ExtArgs>
      fields: Prisma.SelectedExpertiseFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SelectedExpertiseFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SelectedExpertisePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SelectedExpertiseFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SelectedExpertisePayload>
        }
        findFirst: {
          args: Prisma.SelectedExpertiseFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SelectedExpertisePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SelectedExpertiseFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SelectedExpertisePayload>
        }
        findMany: {
          args: Prisma.SelectedExpertiseFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SelectedExpertisePayload>[]
        }
        create: {
          args: Prisma.SelectedExpertiseCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SelectedExpertisePayload>
        }
        createMany: {
          args: Prisma.SelectedExpertiseCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SelectedExpertiseCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SelectedExpertisePayload>[]
        }
        delete: {
          args: Prisma.SelectedExpertiseDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SelectedExpertisePayload>
        }
        update: {
          args: Prisma.SelectedExpertiseUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SelectedExpertisePayload>
        }
        deleteMany: {
          args: Prisma.SelectedExpertiseDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SelectedExpertiseUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SelectedExpertiseUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SelectedExpertisePayload>[]
        }
        upsert: {
          args: Prisma.SelectedExpertiseUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SelectedExpertisePayload>
        }
        aggregate: {
          args: Prisma.SelectedExpertiseAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSelectedExpertise>
        }
        groupBy: {
          args: Prisma.SelectedExpertiseGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SelectedExpertiseGroupByOutputType>[]
        }
        count: {
          args: Prisma.SelectedExpertiseCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SelectedExpertiseCountAggregateOutputType> | number
        }
      }
    }
    InventoryItem: {
      payload: Prisma.$InventoryItemPayload<ExtArgs>
      fields: Prisma.InventoryItemFieldRefs
      operations: {
        findUnique: {
          args: Prisma.InventoryItemFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InventoryItemPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.InventoryItemFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InventoryItemPayload>
        }
        findFirst: {
          args: Prisma.InventoryItemFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InventoryItemPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.InventoryItemFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InventoryItemPayload>
        }
        findMany: {
          args: Prisma.InventoryItemFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InventoryItemPayload>[]
        }
        create: {
          args: Prisma.InventoryItemCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InventoryItemPayload>
        }
        createMany: {
          args: Prisma.InventoryItemCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.InventoryItemCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InventoryItemPayload>[]
        }
        delete: {
          args: Prisma.InventoryItemDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InventoryItemPayload>
        }
        update: {
          args: Prisma.InventoryItemUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InventoryItemPayload>
        }
        deleteMany: {
          args: Prisma.InventoryItemDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.InventoryItemUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.InventoryItemUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InventoryItemPayload>[]
        }
        upsert: {
          args: Prisma.InventoryItemUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InventoryItemPayload>
        }
        aggregate: {
          args: Prisma.InventoryItemAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateInventoryItem>
        }
        groupBy: {
          args: Prisma.InventoryItemGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.InventoryItemGroupByOutputType>[]
        }
        count: {
          args: Prisma.InventoryItemCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.InventoryItemCountAggregateOutputType> | number
        }
      }
    }
    CharacterResources: {
      payload: Prisma.$CharacterResourcesPayload<ExtArgs>
      fields: Prisma.CharacterResourcesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CharacterResourcesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CharacterResourcesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CharacterResourcesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CharacterResourcesPayload>
        }
        findFirst: {
          args: Prisma.CharacterResourcesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CharacterResourcesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CharacterResourcesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CharacterResourcesPayload>
        }
        findMany: {
          args: Prisma.CharacterResourcesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CharacterResourcesPayload>[]
        }
        create: {
          args: Prisma.CharacterResourcesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CharacterResourcesPayload>
        }
        createMany: {
          args: Prisma.CharacterResourcesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CharacterResourcesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CharacterResourcesPayload>[]
        }
        delete: {
          args: Prisma.CharacterResourcesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CharacterResourcesPayload>
        }
        update: {
          args: Prisma.CharacterResourcesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CharacterResourcesPayload>
        }
        deleteMany: {
          args: Prisma.CharacterResourcesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CharacterResourcesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CharacterResourcesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CharacterResourcesPayload>[]
        }
        upsert: {
          args: Prisma.CharacterResourcesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CharacterResourcesPayload>
        }
        aggregate: {
          args: Prisma.CharacterResourcesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCharacterResources>
        }
        groupBy: {
          args: Prisma.CharacterResourcesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CharacterResourcesGroupByOutputType>[]
        }
        count: {
          args: Prisma.CharacterResourcesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CharacterResourcesCountAggregateOutputType> | number
        }
      }
    }
    RadiantPath: {
      payload: Prisma.$RadiantPathPayload<ExtArgs>
      fields: Prisma.RadiantPathFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RadiantPathFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RadiantPathPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RadiantPathFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RadiantPathPayload>
        }
        findFirst: {
          args: Prisma.RadiantPathFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RadiantPathPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RadiantPathFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RadiantPathPayload>
        }
        findMany: {
          args: Prisma.RadiantPathFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RadiantPathPayload>[]
        }
        create: {
          args: Prisma.RadiantPathCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RadiantPathPayload>
        }
        createMany: {
          args: Prisma.RadiantPathCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RadiantPathCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RadiantPathPayload>[]
        }
        delete: {
          args: Prisma.RadiantPathDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RadiantPathPayload>
        }
        update: {
          args: Prisma.RadiantPathUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RadiantPathPayload>
        }
        deleteMany: {
          args: Prisma.RadiantPathDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RadiantPathUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RadiantPathUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RadiantPathPayload>[]
        }
        upsert: {
          args: Prisma.RadiantPathUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RadiantPathPayload>
        }
        aggregate: {
          args: Prisma.RadiantPathAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRadiantPath>
        }
        groupBy: {
          args: Prisma.RadiantPathGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RadiantPathGroupByOutputType>[]
        }
        count: {
          args: Prisma.RadiantPathCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RadiantPathCountAggregateOutputType> | number
        }
      }
    }
    UnlockedSingerForm: {
      payload: Prisma.$UnlockedSingerFormPayload<ExtArgs>
      fields: Prisma.UnlockedSingerFormFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UnlockedSingerFormFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnlockedSingerFormPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UnlockedSingerFormFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnlockedSingerFormPayload>
        }
        findFirst: {
          args: Prisma.UnlockedSingerFormFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnlockedSingerFormPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UnlockedSingerFormFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnlockedSingerFormPayload>
        }
        findMany: {
          args: Prisma.UnlockedSingerFormFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnlockedSingerFormPayload>[]
        }
        create: {
          args: Prisma.UnlockedSingerFormCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnlockedSingerFormPayload>
        }
        createMany: {
          args: Prisma.UnlockedSingerFormCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UnlockedSingerFormCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnlockedSingerFormPayload>[]
        }
        delete: {
          args: Prisma.UnlockedSingerFormDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnlockedSingerFormPayload>
        }
        update: {
          args: Prisma.UnlockedSingerFormUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnlockedSingerFormPayload>
        }
        deleteMany: {
          args: Prisma.UnlockedSingerFormDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UnlockedSingerFormUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UnlockedSingerFormUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnlockedSingerFormPayload>[]
        }
        upsert: {
          args: Prisma.UnlockedSingerFormUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnlockedSingerFormPayload>
        }
        aggregate: {
          args: Prisma.UnlockedSingerFormAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUnlockedSingerForm>
        }
        groupBy: {
          args: Prisma.UnlockedSingerFormGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UnlockedSingerFormGroupByOutputType>[]
        }
        count: {
          args: Prisma.UnlockedSingerFormCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UnlockedSingerFormCountAggregateOutputType> | number
        }
      }
    }
    SpentPoints: {
      payload: Prisma.$SpentPointsPayload<ExtArgs>
      fields: Prisma.SpentPointsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SpentPointsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SpentPointsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SpentPointsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SpentPointsPayload>
        }
        findFirst: {
          args: Prisma.SpentPointsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SpentPointsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SpentPointsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SpentPointsPayload>
        }
        findMany: {
          args: Prisma.SpentPointsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SpentPointsPayload>[]
        }
        create: {
          args: Prisma.SpentPointsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SpentPointsPayload>
        }
        createMany: {
          args: Prisma.SpentPointsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SpentPointsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SpentPointsPayload>[]
        }
        delete: {
          args: Prisma.SpentPointsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SpentPointsPayload>
        }
        update: {
          args: Prisma.SpentPointsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SpentPointsPayload>
        }
        deleteMany: {
          args: Prisma.SpentPointsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SpentPointsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SpentPointsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SpentPointsPayload>[]
        }
        upsert: {
          args: Prisma.SpentPointsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SpentPointsPayload>
        }
        aggregate: {
          args: Prisma.SpentPointsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSpentPoints>
        }
        groupBy: {
          args: Prisma.SpentPointsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SpentPointsGroupByOutputType>[]
        }
        count: {
          args: Prisma.SpentPointsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SpentPointsCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const CharacterScalarFieldEnum = {
  id: 'id',
  name: 'name',
  level: 'level',
  pendingLevelPoints: 'pendingLevelPoints',
  ancestry: 'ancestry',
  sessionNotes: 'sessionNotes',
  lastModified: 'lastModified'
} as const

export type CharacterScalarFieldEnum = (typeof CharacterScalarFieldEnum)[keyof typeof CharacterScalarFieldEnum]


export const CultureSelectionScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  name: 'name',
  description: 'description',
  expertise: 'expertise',
  suggestedNames: 'suggestedNames'
} as const

export type CultureSelectionScalarFieldEnum = (typeof CultureSelectionScalarFieldEnum)[keyof typeof CultureSelectionScalarFieldEnum]


export const PathSelectionScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  pathName: 'pathName'
} as const

export type PathSelectionScalarFieldEnum = (typeof PathSelectionScalarFieldEnum)[keyof typeof PathSelectionScalarFieldEnum]


export const AttributesScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  strength: 'strength',
  speed: 'speed',
  intellect: 'intellect',
  willpower: 'willpower',
  awareness: 'awareness',
  presence: 'presence'
} as const

export type AttributesScalarFieldEnum = (typeof AttributesScalarFieldEnum)[keyof typeof AttributesScalarFieldEnum]


export const SkillScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  skillName: 'skillName',
  value: 'value'
} as const

export type SkillScalarFieldEnum = (typeof SkillScalarFieldEnum)[keyof typeof SkillScalarFieldEnum]


export const UnlockedTalentScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  talentId: 'talentId',
  unlockedAt: 'unlockedAt',
  level: 'level'
} as const

export type UnlockedTalentScalarFieldEnum = (typeof UnlockedTalentScalarFieldEnum)[keyof typeof UnlockedTalentScalarFieldEnum]


export const SelectedExpertiseScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  name: 'name',
  source: 'source',
  sourceId: 'sourceId'
} as const

export type SelectedExpertiseScalarFieldEnum = (typeof SelectedExpertiseScalarFieldEnum)[keyof typeof SelectedExpertiseScalarFieldEnum]


export const InventoryItemScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  itemId: 'itemId',
  quantity: 'quantity',
  equipped: 'equipped'
} as const

export type InventoryItemScalarFieldEnum = (typeof InventoryItemScalarFieldEnum)[keyof typeof InventoryItemScalarFieldEnum]


export const CharacterResourcesScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  healthCurrent: 'healthCurrent',
  healthMax: 'healthMax',
  focusCurrent: 'focusCurrent',
  focusMax: 'focusMax',
  investitureCurrent: 'investitureCurrent',
  investitureMax: 'investitureMax',
  investitureActive: 'investitureActive'
} as const

export type CharacterResourcesScalarFieldEnum = (typeof CharacterResourcesScalarFieldEnum)[keyof typeof CharacterResourcesScalarFieldEnum]


export const RadiantPathScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  boundOrder: 'boundOrder',
  currentIdeal: 'currentIdeal',
  idealSpoken: 'idealSpoken',
  surgePair: 'surgePair',
  sprenType: 'sprenType'
} as const

export type RadiantPathScalarFieldEnum = (typeof RadiantPathScalarFieldEnum)[keyof typeof RadiantPathScalarFieldEnum]


export const UnlockedSingerFormScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  formId: 'formId',
  unlockedAt: 'unlockedAt'
} as const

export type UnlockedSingerFormScalarFieldEnum = (typeof UnlockedSingerFormScalarFieldEnum)[keyof typeof UnlockedSingerFormScalarFieldEnum]


export const SpentPointsScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  attributes: 'attributes',
  skills: 'skills',
  talents: 'talents'
} as const

export type SpentPointsScalarFieldEnum = (typeof SpentPointsScalarFieldEnum)[keyof typeof SpentPointsScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  character?: Prisma.CharacterOmit
  cultureSelection?: Prisma.CultureSelectionOmit
  pathSelection?: Prisma.PathSelectionOmit
  attributes?: Prisma.AttributesOmit
  skill?: Prisma.SkillOmit
  unlockedTalent?: Prisma.UnlockedTalentOmit
  selectedExpertise?: Prisma.SelectedExpertiseOmit
  inventoryItem?: Prisma.InventoryItemOmit
  characterResources?: Prisma.CharacterResourcesOmit
  radiantPath?: Prisma.RadiantPathOmit
  unlockedSingerForm?: Prisma.UnlockedSingerFormOmit
  spentPoints?: Prisma.SpentPointsOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

